### ISSUE TITLE
% VS value in case of sludge digested & non digested for carbon sequestration

### ISSUE THREAD

**Issue by harora16** [icra/ecam#101]
I have made manual calculation results were not matching so check the formula again. 
might be because of % VS values, it should be  
for digested sludge = 0.51
non digested sludge = 0.70
![ecam 3](https://user-images.githubusercontent.com/38723394/40625401-81ba8c42-62b2-11e8-87d2-f55822d83906.png)
@holalluis @Ranf16 @Porro1jc

**Comment by holalluis** [comment]
Hi, it's true, there was an error on detecting the sludge type, now it is corrected. thanks for spotting it
