### ISSUE TITLE
Opportunities page - biogas and typo

### ISSUE THREAD

**Issue by Porro1jc** [icra/ecam#105]
@holalluis @Ranf16 @harora16 

![image](https://user-images.githubusercontent.com/20580315/40675034-8da27b9a-6344-11e8-9e28-c15e2e2d619d.png)

**Comment by holalluis** [comment]
https://github.com/icra/ecam/blob/master/opps.php

**Comment by Porro1jc** [comment]
@holalluis ,  in addition to fixing the spelling and making text in red white, can you spend some time seeing if you can figure out the other fixes.  Maybe one hour.  This is important for the webinar next week.  Not sure if @gmatcha will be able to respond.

**Comment by holalluis** [comment]
I would be faster if I recode this page from zero instead. Shall I spend time in it as a priority?

**Comment by Porro1jc** [comment]
Delete asterisk* in description below from code

"title" : "Sludge disposal reduction*",  **DELETE ASTERISK**

            "dper" : function() { return Global.Opps.g_ww_slu_dper; },

            "ghg_em" : function(percent,i) {

              opps.g_ww_slu_opps_em = ((percent / 100) * opps.g_ww_slu_opps);

              var total_nrw = Global.General.TotalGHG() - opps.g_ww_slu_opps_em;

              var total_nrw_percent = ((Global.General.TotalGHG() - total_nrw) / Global.General.TotalGHG()) * 100;

              document.querySelector('#measure-body-reduction' + '-'.concat(i)).innerHTML = format(opps.g_ww_slu_opps_em);

              document.querySelector('#measure-body-total' + '-'.concat(i)).innerHTML = format(total_nrw);

              document.querySelector('#measure-body-percent-reduction' + '-'.concat(i)).innerHTML = format(total_nrw_percent);

              Global.Opps.g_ww_slu_dper = percent;

              opps.g_update_total();

**Comment by holalluis** [comment]
ok, done

**Comment by Porro1jc** [comment]
fix formula for:   c_wwc_vol_infl 

should be:  
wwc_rain_day * (wwc_wet_flow-wwc_dry_flow)

**Comment by Porro1jc** [comment]
Please get on skype so we can finish
