### ISSUE TITLE
WWT substage CH4 EF pull down 

### ISSUE THREAD

**Issue by Porro1jc** [icra/ecam#106]
@holalluis @Ranf16 @harora16

Only do this if it can be done quickly...

it would be easier for the user if the CH4 EF value in WW treatment substages would be a dropdown menu while still allowing the user to modify the value, i.e. the same way it is at the stage level.

**Comment by holalluis** [comment]
It's pretty difficult, because the selection is done in the description of the variable, not in the text box where the user inputs the number... This would mean recoding all the substages part which creates this table structure to make room for dropdown menus
