### ISSUE TITLE
GHG emissions outside and avoided tables - edit item descriptions 

### ISSUE THREAD

**Issue by Porro1jc** [icra/ecam#109]
@holalluis @Ranf16 @harora16

-	Hide the code of the variable i.e. “ww_SL_ghg_unc” and put the link instead in the description i.e. “CO2 eq from uncollected wastewater”. 

This would be a neat solution because in the table of the emissions of the utility, the words are also links. And it would let the table of avoided emissions shrink a bit and hence be less dominant. 

![github image](https://user-images.githubusercontent.com/20580315/40786335-cd69373a-64b8-11e8-9907-d235c041c1cd.png)

**Comment by holalluis** [comment]
ok, it will be done in about 15 minutes

**Comment by holalluis** [comment]
done, please check
