### ISSUE TITLE
N2O from treatment process - make output manually adjustable 

### ISSUE THREAD

**Issue by Porro1jc** [icra/ecam#110]
@holalluis @Ranf16 @harora16

wwt_KPI_GHG_tre_n2o 
Make this output so you can manually overwrite the calculated value if you want to use your own

**Comment by holalluis** [comment]
Ok, I think this works: I've included this new output and modified the output formula as follows:
![1](https://user-images.githubusercontent.com/1082644/40933202-150d3afc-6831-11e8-9f71-2ab6071a4ca7.png)

![2](https://user-images.githubusercontent.com/1082644/40933206-18399a4a-6831-11e8-8b23-33a3f531ffb0.png)

**Comment by holalluis** [comment]
please try it in the testing server and reopen the issue if it is not enough

**Comment by Porro1jc** [comment]
if you did it this way, then we should make it an "N2O emissions from treatment process correction factor".  They enter a value (either positive or negative to correct the value calculated by IPCC).  If zero, nothing happens.  Then  the formula for wwt_KPI_GHG_tre_n2o becomes... wwt_serv_pop * ct_fac_ic * ct_n2o_efp * Years * 1e-3 * ct_n2o_eq + wwt_GHG_tre_n2o

**Comment by holalluis** [comment]
done, please check

**Comment by Porro1jc** [comment]
Copy paste for description of variable... 

N2O emissions from treatment process correction factor (can be positive or negative).  If you have country-specific or site-specific emission factors from actual measurements, you can calculate the emissions based on these factors and then using the correction factor, either add or subtract the difference between your emissions and those calculated by ECAM based on the IPCC generic emission factor.  The emissions calculated by ECAM will automatically be updated based on the value you enter to correct the emissions.

**Comment by holalluis** [comment]
ok, done
