### ISSUE TITLE
Prefilling energy for pumping and volume pumped 

### ISSUE THREAD

**Issue by Porro1jc** [icra/ecam#112]
@Ranf16 @holalluis @harora16

![image](https://user-images.githubusercontent.com/20580315/40924401-2d4d91d0-67e5-11e8-929a-f272954102ad.png)

**Comment by holalluis** [comment]
The question is: when these values have to be prefilled? prefilling means assigning a value to those variables from the code, and this is easy to do, but what is not easy to do is deciding exactly when this should be triggered. I assume that should be in tier A only? please confirm

**Comment by Ranf16** [comment]
The prefilling should work for all substages, therefore triggering it at tier A is not a good option. I propose to trigger it when the user activates the filter "do you want to evaluate pump efficiency"
