### ISSUE TITLE
Total GHG emission sum not correct!

### ISSUE THREAD

**Issue by harora16** [icra/ecam#113]
![capture](https://user-images.githubusercontent.com/38723394/40985590-c0e8de36-68e4-11e8-9eeb-766312f0dc0c.PNG)

The value should be the sum of all the emissions avoided. 
@holalluis @Ranf16 @Porro1jc

**Comment by holalluis** [comment]
That's true, sorry, when I was told to change the ghg avoided formulas I forgot to reflect the change in the total ghg avoided formula, it is corrected

**Comment by holalluis** [comment]
I'll close the issue when it is in the server
