### ISSUE TITLE
Reset button

### ISSUE THREAD

**Issue by Porro1jc** [icra/ecam#117]
@holalluis @Ranf16 @harora16 

Fix reset button so values not shown in Tier A (eg. sludge production) are not reset to zero but rather set to original Tier A estimation values.  We can discuss and go over example before you start to make sure it is feasible and we understand each other.

**Comment by holalluis** [comment]
The original estimation is zero for all variables. It is choosing an option from this part what triggers the different types of estimations!
![captura de pantalla 2018-06-21 a las 14 36 24](https://user-images.githubusercontent.com/1082644/41719530-93bf3724-7560-11e8-8224-37f1fb099488.png)

**Comment by Ranf16** [comment]
@holalluis @Ranf16 @harora16

Would it be possible that in the drop down menu "Select main treatment type" there is an additional option called "Select" or "Choose technology". After clicking on the reset button this option should be shown, thereby it would be clear to the users that they have to chose an option again.

This would solve the issue

**Comment by Ranf16** [comment]
@Porro1jc @holalluis @harora16 

Thanks for updating the reset button

Please change however the "None" to "Select" 
Reason is that "None" can be misunderstood for no treatment technology which would also produce emissions. 

![image](https://user-images.githubusercontent.com/33861734/41764974-f3b49faa-7602-11e8-9816-05582e43b299.png)

**Comment by holalluis** [comment]
ok, changed. thanks
