### ISSUE TITLE
Opportunities Page edits 

### ISSUE THREAD

**Issue by Porro1jc** [icra/ecam#118]
o	change descriptions for "non-revenue water" to water loss 
o	fix calculation for I/I opportunities - let's discuss quickly.  It has to do with units but easier to explain via skype
o	description of "biogas opportunities" – change to "biogas emissions" 

![image](https://user-images.githubusercontent.com/20580315/41723609-83f32138-7539-11e8-9211-182f08783257.png)

**Comment by holalluis** [comment]
ok done
