### ISSUE TITLE
Consider in the discharge stage that all water can be reused.

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#121]
In the case the utility reuses all the wastewater and does not discharge anything to the water body (e.g. like it is the case in Jordan), ECAM shows “missing value” in the last column of the output table. 

What to do:
EDIT: What to do:
In case the volume of discharged water ( wwd_vol_disc ) is zero, then the marked outputs should say "N/A"

![image](https://user-images.githubusercontent.com/33861734/41720181-8d1ab662-7562-11e8-986f-2f5ced513e4a.png)

If possible to change only the output table in the discharge separately then rename the title of the last column to "kg CO2 per **discharged** m³".

![image](https://user-images.githubusercontent.com/33861734/41721294-cdc446d0-7565-11e8-9c83-27ced4052ea9.png)

**Comment by Ranf16** [comment]
EDIT: What to do:
In case the volume of discharged water ( wwd_vol_disc ) is zero, then the marked outputs should say "N/A"

If possible to change only the output table in the discharge separately then write "kg CO2 per **discharged** m³".

**Comment by Porro1jc** [comment]
INSTEAD of indicating NA, Marked outputs should consider sum of wwd_vol_disc and wwd_vol_nonp instead of only wwd_vol_disc.
