### ISSUE TITLE
Remove the "Emtpying" stage and include a filter for it in each of the tree other FSM stages

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#123]
Remove the emtpying stage and include the same inputs that into each of the other 3 stages within a filter.

![image](https://user-images.githubusercontent.com/33861734/44467761-f805dc80-a623-11e8-8d96-b132a177f722.png)

**The name of the filter shall be slightly different in the stages:**

- In the containment stage the filter shall be "Evaluate emtptying and transport of faecal sludge?"

- In "Treatment" and "Reuse/Disposal" the filter shall be called "Evaluate transport of faecal sludge?"

![image](https://user-images.githubusercontent.com/33861734/44467787-0e139d00-a624-11e8-848e-28015652a037.png)

![image](https://user-images.githubusercontent.com/33861734/44467842-33081000-a624-11e8-8f97-53d96685be76.png)

![image](https://user-images.githubusercontent.com/33861734/44467875-49ae6700-a624-11e8-93d9-6087e9792128.png)

**Comment by holalluis** [comment]
done, please check @Ranf16
