### ISSUE TITLE
Update inputs in Treatment stage

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#125]
1. Update the dropdown menu for CH4 emission factor as shown in the table:

Main treatment technology | CH4 Emission factor (containment) | % BOD sludge
-- | -- | --
Select | 0 | 0
No Treatment | 0 | 0
Anaerobic Digester | 0,48 | 10
Imhoff Tanks | 0,48 | 10
Anaerobic Reactors – CH4 recovery not   considered | 0,48 | 10
Anaerobic Reactors – CH4 recovery   considered | 0 | 10
Stabilization Ponds (<2 m depth) | 0,12 | 30
Stabilization Ponds (> 2m depth) | 0.48 | 10
Sludge Drying Beds | 0 | 0
Wetlands – surface flow | 0,24 | 30
Wetlands – Horizontal subsurface flow | 0,06 | 65
Wetlands – Vertical subsurface flow | 0,006 | 65
Composting | 0.0013 | 0
Activated Sludge (well managed) | 0 | 65
Activated Sludge – minor poorly aerated zones | 0,06 | 65
Activated Sludge - Some aerated zones | 0,12 | 65
Activated Sludge – Not well managed | 0,18 | 65
Trickling Filter | 0,036 | 65

2. The inputs for fuel engines should only appear if the option is activated on the configuration page:
![image](https://user-images.githubusercontent.com/33861734/44468951-b460a200-a626-11e8-9f6a-68e197b1f21a.png)

**Comment by holalluis** [comment]
solved
