### ISSUE TITLE
Let "recommended" values be calculated.

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#127]
**1. In containment:**

-  the input "Containments emptied" shall be used to calculate "recommended" values for "FS emtpied" and "BOD removed as FS".
- the influent BOD load is also recommended. 

the formulas are as follows:

![image](https://user-images.githubusercontent.com/33861734/44541323-e1d24c00-a709-11e8-91a7-2dbc20a5f438.png)

**2. In Treatment:**

![image](https://user-images.githubusercontent.com/33861734/44541417-24942400-a70a-11e8-9b25-92fb46718dbf.png)

**Comment by holalluis** [comment]
the influent BOD in containment, the influent BOD in treatment, the BOD removed as sludge, the effluent BOD in treatment and the biogas produced already have a button next to them for the estimations, check it @Ranf16. Now I'm working in the other ones

**Comment by holalluis** [comment]
done and created issues #130 and #131
