### ISSUE TITLE
Add FSM Indicators to Tier A outputs and update translations

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#128]
**2. On Tier A page:**
- add the indicator "Total GHG in Faecal Sludge Mangement" in the unit kg CO2e/year/serv.pop.
- add the indicator "Serviced population with onsite sanitation" unit is %.
   The formula for this is= Population with onsite treatment / resident population (FSM) * 100
![image](https://user-images.githubusercontent.com/33861734/44645809-3b23cf00-a9d9-11e8-9e02-7088789c0a38.png)

**3. Modify the English and Spanish text:**
- change the text of the wastewater coverage indicator below.

Language | Old | New
-- | -- | --
English | serviced population (% of resident population) | Resident population serviced with wastewater treatment
Spanish | Población servida con tratamiento de aguas residuales   (respecto a la población residente) | Población residente servida con tratamiento de aguas   residuales

![image](https://user-images.githubusercontent.com/33861734/44645844-6a3a4080-a9d9-11e8-9e11-9c4b0beaf57c.png)

**Comment by holalluis** [comment]
done, please check

**Comment by Ranf16** [comment]
Works, great. 

On the left side there are however more lines than on the right side. Can you please remove the marked lines in the between the boxes. The last line on the left side should be further down to match the right side.

![image](https://user-images.githubusercontent.com/33861734/45020825-4e194d80-b030-11e8-9094-31316b1879fb.png)

**Comment by holalluis** [comment]
fixed
![captura de pantalla de 2018-09-04 18-35-22](https://user-images.githubusercontent.com/1082644/45044768-55148000-b071-11e8-82da-2531b5a0125c.png)
