### ISSUE TITLE
opening old json files

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#132]
If you try to open older json files in the ECAM 2.2 nothing happens. 

Here is an example json file that opens in ECAM 2.1 but not in 2.2:

https://www.dropbox.com/s/gs5q49u8ckpnc5k/SEDACUSC%202016%20with%20sludge%20.json?dl=0

**Comment by holalluis** [comment]
I've tried on my end and it works. Can you try to load the file with the console open? (To open the console on most browsers just right click anywhere, select "Inspect / Inspect element") and then click on the second tab which says "Console". Then, try to load the file and screenshot the error messages you've got.

**Comment by Ranf16** [comment]
Now it works after having deleted the cache.
