### ISSUE TITLE
Align the logos and text on the configuration page

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#133]
Currently it looks like this:
![image](https://user-images.githubusercontent.com/33861734/45018690-db59a380-b02a-11e8-8deb-20f2cf17262c.png)

Can you please align the logo with the other logos for Water Supply and Wastewater and wrap the text in 2 lines so that it fits. See below:

![image](https://user-images.githubusercontent.com/33861734/45019003-836f6c80-b02b-11e8-9891-d9536c38f501.png)

**Comment by holalluis** [comment]
fixed
