### ISSUE TITLE
Update formula for Population whose wastewater is uncollected

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#134]
The formula for [ww_uncl_pop
](http://84.89.61.64:8030/ecam/variable.php?id=ww_uncl_pop) needs to be changed since ww_onsi_pop does not exist anymore. 

The emissions from uncollected wastewater shall be calcualted by the population that is not connected to the sewerage considering that some of those people might be serviced with onsite treatment. However we must consider the following two:

1. it could be the case that someone assesses FSM and without assessing wastewater 
2.  The user assesses different systems in wastewater and faecal sludge, and it could be the case that the population serviced with onsite treatment is larger than the population not connected to sewerage.

Therefore I propose that the formula is updated with the population with onsite treatment, however if the equation gives a negative result the value should be zero. 

Something like this:
ww_uncl_pop = if (ww_resi_pop-ww_conn_pop - Population with onsite treatment (FSM) >0; then ww_resi_pop-ww_conn_pop - Population with onsite treatment (FSM); otherwise 0)

![image](https://user-images.githubusercontent.com/33861734/45020333-f9290780-b02e-11e8-8662-515b6cefd714.png)

**Comment by holalluis** [comment]
ok fixed.

The old formula already considers that the min value is 0, this is the part where it takes the maximum value between either the value computed or 0. So, if it's negative, the maximum will be 0.
