### ISSUE TITLE
Containment stage: Rearrange the order of inputs

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#135]
The inputs should be in the order the user has to fill them in. This is important since only then the estimation buttons make sense.

1, Energy consumed from the grid
2. Influent BOD load
**3. Is the containment experiencing flooding or groundwater infiltration?
4. CH4 emission factor
5. Containments emptied
6. FS density
7. FS emptied
8. BOD concentration of FS
9. BOD removed as FS**

![image](https://user-images.githubusercontent.com/33861734/45022060-88d0b500-b033-11e8-8952-4cde698492b7.png)

**Comment by holalluis** [comment]
![captura de pantalla de 2018-09-04 17-37-31](https://user-images.githubusercontent.com/1082644/45041735-56da4580-b069-11e8-9955-59b35822af94.png)

**Comment by holalluis** [comment]
ok fixed
