### ISSUE TITLE
Add a column to the output table of the FSM stages

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#136]
Add column to the new stages with the unit "kg CO2 per year and pop. with onsite treatment"

the displayed emissions shall by the emissions devided by the "Population with onsite treatment" specified in the population page.

![image](https://user-images.githubusercontent.com/33861734/45022269-17453680-b034-11e8-90ff-76b60ab72ef5.png)

**Comment by holalluis** [comment]
ok fixed

**Comment by holalluis** [comment]
![captura de pantalla de 2018-09-04 17-55-51](https://user-images.githubusercontent.com/1082644/45042784-ccdfac00-b06b-11e8-808f-b156ef51eb73.png)
