### ISSUE TITLE
Add key numbers at the top of each FSM stage page

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#137]
In water supply and wastewater there are these numbers on top of the pages of each stage; see below:

![image](https://user-images.githubusercontent.com/33861734/45025456-d2250280-b03b-11e8-91b1-8baeca82becc.png)

In the FSM stages this is missing:
![image](https://user-images.githubusercontent.com/33861734/45025683-7313bd80-b03c-11e8-9d7a-bfb8ab64751b.png)

Please add also the following in the same manner to the FSM stages:

- Assessment period
- Resident population 
- Population with onsite treatment
- Emission factor for grid electricity

**Comment by holalluis** [comment]
done

![captura de pantalla de 2018-09-04 18-14-42](https://user-images.githubusercontent.com/1082644/45043759-6c9e3980-b06e-11e8-9a8f-205ff21f486b.png)
