### ISSUE TITLE
% of "Dry weight sent to land application / landfill" values for each type of faecal sludge

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#140]
(edit: I removed the already done ones)
### **2. The following needs to be estimated based on the Tier A selections:**
**Reuse /Discharge**
- Dry weight of sludge (land application / landfill) - I will provide the formula later

**Comment by holalluis** [comment]
add 2 more: 
- are you producing biogas? (yes/no)
- are you valorizing biogas? (yes/no)

**Comment by Ranf16** [comment]
The front size of the old and new drop down menus is not the same. I propose to use for the FSM dropdown menus the same size as in the wastewater dropdown menus:

![image](https://user-images.githubusercontent.com/33861734/45139090-f2290300-b1ae-11e8-8621-76fdf3d4fa2f.png)

**Comment by Ranf16** [comment]
Please use for question regarding flooding  the same YES/NO type as the the questions for biogas

So in this question:
![image](https://user-images.githubusercontent.com/33861734/45139169-34524480-b1af-11e8-8bce-c4276d7a17de.png)


Use this selection
![image](https://user-images.githubusercontent.com/33861734/45139202-4502ba80-b1af-11e8-88ac-59360e10bd2b.png)

**Comment by Ranf16** [comment]
-  Add one more column called "% Dry weight" to the table below. 
- the provisional values for this shall be **10%** for all types of faecal sludge. 

![image](https://user-images.githubusercontent.com/33861734/45493961-49f7d900-b770-11e8-94f2-60412a11b401.png)





 What is missing is that when the user selects in Tier A the Type of faecal sludge disposed, the tool estimates the following:

**1. Volume dumped** 
The volume dumped shall be the volume of faecal sludge emptied which is calulated in the containment stage:
 _Volume dumped (fsr_vol_dumping) = Faecal sludge emptied (fsc_fslu_emp)_


**2.  dry weight that is disposed in the case of landfilling and landapplication**
The dry weight shall be calculated with the new value (% Dry weight) added to the table above. The estimated dry weight shall be the same for landfilling and land application.

_Dry weight sent to land application (fsr_mass_landapp) = Faecal sludge emptied (fsc_fslu_emp) * Faecal sludge density (fsc_fdensity) * % Dry weight_

_Dry weight sent to landfill (fsr_mass_landfil)= Faecal sludge emptied (fsc_fslu_emp) * Faecal sludge density (fsc_fdensity) * % Dry weight_



**Note: For now we will have to use these provisional values. I guess I can only give you the final values next week.**

**Comment by holalluis** [comment]
ok, for now I've written the following toy values, to check that everything is working:
![captura de pantalla 2018-09-13 a las 21 25 40](https://user-images.githubusercontent.com/1082644/45510827-a91f1300-b79b-11e8-88a5-aa312c2b47c0.png)

**Comment by holalluis** [comment]
![captura de pantalla 2018-09-14 a las 1 16 23](https://user-images.githubusercontent.com/1082644/45520912-ebf0e300-b7bb-11e8-9dcb-c61b91b99db3.png)

Estimations for landfill and land application done, please check

**Comment by Ranf16** [comment]
works.

**Comment by holalluis** [comment]
@Ranf16 I would leave this issue open until you send the values for dry_weight for each type of FS

**Comment by Ranf16** [comment]
Please change the name from "dry weight" to "Total Solids" in the table below and also in the formulas for:

- fsr_mass_landapp 
- fsr_mass_landfil

![image](https://user-images.githubusercontent.com/33861734/46816733-e3b9a280-cd7d-11e8-96dd-20ea044b54f5.png)

![image](https://user-images.githubusercontent.com/33861734/46816786-faf89000-cd7d-11e8-8c56-bd74c2e2715f.png)

I will provide the values by Monday.

**Comment by Ranf16** [comment]
Here are the default values for the estimations:



Type | Total N [% of dry   weight] | TVS [% of dry   weight] | TS [%]
-- | -- | -- | --
Untreated faecal sludge | 0.24% | 70.00% | 4.00%
Treated faecal sludge (Typical) | 3% | 40% | 22.00%
Pit hummus | 4% | 65% | 7.00%
Dried faeces | 3.00% | 70.00% | 27.00%
Composted faecal sludge | 3% | 80.00% | 8.00%
Septic  tank sludge | 0.03% | 60.00% | 2.00%

Please note also the previous comment, regarding renaming and making those values available as inputs. 

Please see the image below to avoid confusion regarding what value in the table belongs to what in the Tool. 

![image](https://user-images.githubusercontent.com/33861734/47286237-1c634280-d5ee-11e8-867e-07b10a048ea4.png)

**Comment by holalluis** [comment]
![captura de pantalla 2018-10-23 a las 19 30 59](https://user-images.githubusercontent.com/1082644/47379092-3ab66480-d6fa-11e8-8fb8-9130f46640f6.png)

**Comment by holalluis** [comment]
still missing the part of renaming, this kind of edits are dangerous, I'm making sure it does not affect any calculation
