### ISSUE TITLE
Fix error of estimate buttons when the selected unit is gramm

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#142]
The estimate buttons work fine if the unit is kg, but if you change the unit to gramm, some values, i.e. the ones related to BOD,  are wrong by a factor of 1000.

See video below:
https://www.dropbox.com/s/ogjdyu8vejkh1i8/ECAM_estimate%20buttons_problem.mp4?dl=0

**Comment by holalluis** [comment]
thanks for noticing, I forgot to add the multiplier factor when changing units, now it is solved
