### ISSUE TITLE
Allow the unit tonnes for the inputs in FSM and in Wastewater

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#143]
Please add the unit **t** (tonne) also the the following inputs. Therefore you need to devide the value with the unit kg by 1000;

**Wastewater treatment:**
![image](https://user-images.githubusercontent.com/33861734/45079119-f8a57500-b0f1-11e8-9acd-e724d6ffc3f4.png)

**Sludge mangement** 
![image](https://user-images.githubusercontent.com/33861734/45079203-28ed1380-b0f2-11e8-8639-0efad558665b.png)

**FSM - collection**
![image](https://user-images.githubusercontent.com/33861734/45079229-4326f180-b0f2-11e8-9a4c-7283fe8e50d4.png)

**FSM - treatment**
![image](https://user-images.githubusercontent.com/33861734/45079287-6c478200-b0f2-11e8-9c25-11f37e3700f1.png)

**FSM - reuse**
![image](https://user-images.githubusercontent.com/33861734/45079348-9dc04d80-b0f2-11e8-887e-5e264b5b899f.png)

**Comment by holalluis** [comment]
ok, solved, now we can use 't' as mass unit
