### ISSUE TITLE
Add text to the drop down menu for land application

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#144]
Please add the following text to the drop down menu for land application in FSM and Wastewater:

-	fine-textured **(>30% clay)**
-	coarse-textured **(<  30% clay)**

Wastewater - Treatment
![image](https://user-images.githubusercontent.com/33861734/45088939-d9ffa800-b10a-11e8-9d6a-1cde76277e18.png)

FSM - Reuse:

![image](https://user-images.githubusercontent.com/33861734/45088888-b0df1780-b10a-11e8-94be-bc74425d8636.png)
![image](https://user-images.githubusercontent.com/33861734/45088988-fe5b8480-b10a-11e8-8e75-52317e163cdc.png)

**Comment by holalluis** [comment]
done
