### ISSUE TITLE
The FSM stages Treatment and Reuse should have also the filter for fuel engines

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#145]
If on the configuration page the filter for fuel engines is activated (see below), then in the FSM stages **Treatment** and **Reuse** the corresponding inputs should appear.

**Note: in Containment this option is not required.**

![image](https://user-images.githubusercontent.com/33861734/45097528-5b633480-b123-11e8-9a80-b97556f29df5.png)

**Comment by holalluis** [comment]
done
