### ISSUE TITLE
Add a page with abbreviations

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#150]
We use now several abbreviations in ECAM that we should explain somewhere. Can you please add a page with a simple table like below for the following abbreviations. 

Abbreviation | Name
-- | --
BOD | Biological Oxygen Demand
BOD5 | Biological Oxygen Demand after 5 day test
CCF | climate-carbon feedbacks
CO2eq | CO2 equivalent
FS | Faecal sludge
FSM | Faecal sludge mangement
GHG | Greenhouse gas
pop | population
serv | serviced
WS | Water supply
WW | Wastewater

More abbreviations might follow.

I propose to add a link to it on the Tier A page:
![image](https://user-images.githubusercontent.com/33861734/45144215-c4978600-b1bd-11e8-9bd4-051feccdafce.png)
 

**Note that in the other languages there will be also abbreviations.**

**Comment by holalluis** [comment]
ok, done
![captura de pantalla 2018-09-06 a las 16 02 53](https://user-images.githubusercontent.com/1082644/45162468-5a4b0980-b1ee-11e8-8ff2-a5b22dd21667.png)
