### ISSUE TITLE
UNFCCC category of GHG emissions from CH4 in FSM Containment (fsc_KPI_GHG_cont)?

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#152]
@Ranf16 this emission is not inside any equation of UNFCCC
![captura de pantalla 2018-09-06 a las 18 08 53](https://user-images.githubusercontent.com/1082644/45170351-f6314100-b1ff-11e8-9dba-0a049b416d8a.png)

maybe it fits in 5A? 5B? 5D?
![captura de pantalla 2018-09-06 a las 18 10 54](https://user-images.githubusercontent.com/1082644/45170452-3abcdc80-b200-11e8-9f33-81ed5863f071.png)

**Comment by Ranf16** [comment]
Thanks for noticing. Please add it to the following category:


Waste - Wastewater treatment and Discharge | unfccc_5D
-- | --

**Comment by holalluis** [comment]
solved
