### ISSUE TITLE
Move emissions from onsite treatment to FSM stage

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#153]
Do you agree @Ranf16 ?
![captura de pantalla 2018-09-06 a las 23 42 27](https://user-images.githubusercontent.com/1082644/45186690-a1f18580-b22e-11e8-9407-162dc1cac19d.png)
![captura de pantalla 2018-09-06 a las 23 42 37](https://user-images.githubusercontent.com/1082644/45186691-a5850c80-b22e-11e8-89bf-b8a6cd859138.png)
![captura de pantalla 2018-09-06 a las 23 42 44](https://user-images.githubusercontent.com/1082644/45186693-a74ed000-b22e-11e8-9d50-8846984274e5.png)
![captura de pantalla 2018-09-06 a las 23 42 57](https://user-images.githubusercontent.com/1082644/45186695-a9189380-b22e-11e8-9d45-9ab770d72e4e.png)

**Comment by Ranf16** [comment]
Thanks for noticing this. These 3 outputs can actually be removed because what is calculted in the FSM-containment stage is actually what these outputs where for. So delete all 3:
- ww_SL_ghg_ons
- ww_SL_ghg_ons_ch4
- ww_SL_ghg_ons_n2o

**Comment by holalluis** [comment]
solved
