### ISSUE TITLE
Containment stage: Put the input for electricity within the filter 

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#154]
Put the input for electricity within the filter "Evaluate emptying and transport of faecal sludge". 

![image](https://user-images.githubusercontent.com/33861734/45217526-b40e0b00-b2a4-11e8-8970-b3f2c1d85001.png)

**Comment by holalluis** [comment]
done

**Comment by Ranf16** [comment]
I still see the input outside of the filter.

**Comment by holalluis** [comment]
the server is updated, now you should see it correctly
