### ISSUE TITLE
Rename Outputs

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#156]
**FSM Reuse / Discharge stage:**
- the total of that stage should be called "Total emissions in Reuse/Discharge"
![image](https://user-images.githubusercontent.com/33861734/45219779-58e01680-b2ac-11e8-9e07-2d37063e8937.png)

**Wastewater Discharge/Reuse stage:**
It should say reuse instead of recovery.
- GHG emissions avoided due to Nitrogen recovery > GHG emissions avoided due to Nitrogen **reuse**
- GHG emissions avoided due to Phosphorus recovery > GHG emissions avoided due to Phosphorus **reuse**
- GHG emissions avoided due to nutrient recovery displacing synthetic fertilizer use > GHG emissions avoided due to nutrient **reuse** displacing synthetic fertilizer use
![image](https://user-images.githubusercontent.com/33861734/45220073-4f0ae300-b2ad-11e8-9f1f-5deeb8901fdc.png)

**Comment by holalluis** [comment]
solved

**Comment by Ranf16** [comment]
I also can't see this change. Did you maybe forget to update the server?
