### ISSUE TITLE
Remove logos Gobierno de Espana and Unió Europea

### ISSUE THREAD

**Issue by TobiasGIZ** [icra/ecam#159]
Dear LluisB, could you please remove the two logos from Gobierno de Espana and Unió Europea at the about page. Logos should be arrange like at the landing page of the tool:

http://wacclim.org/ecam/about.php

There is also a new logo from the german ministry of environment (BMU). Could that be updated on the "landing page" and "about page"? 

Thanks a lot, Tobias - GIZ

**Comment by Ranf16** [comment]
Dear Lluis,

can you please do those changes? Let us know if you need further clarification.

Below is the updated logo of the BMU that needs to be replaced. 

![01 bmu_2018_en_colour](https://user-images.githubusercontent.com/33861734/45351489-9ac3d200-b5b6-11e8-9e98-f24180af60eb.png)

**Comment by holalluis** [comment]
ok done
![captura de pantalla de 2018-09-12 12-33-05](https://user-images.githubusercontent.com/1082644/45419600-09249500-b688-11e8-83f7-976cf96d7a75.png)

**Comment by holalluis** [comment]
@TobiasGIZ @Ranf16 you can check it at the development server (http://84.89.61.64:8030/ecam/)
