### ISSUE TITLE
Wastewater treatment: Fix error in formula for CH4 emissions from landfilling

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#160]
![ch4 emissions from landfilling](https://user-images.githubusercontent.com/33861734/45368516-125c2600-b5e4-11e8-9526-006bfb3aab32.PNG)

**Comment by holalluis** [comment]
So, the formula is the same disregarding the sludge type?

**Comment by Ranf16** [comment]
No. it's not the same. see the underlined variable that is different.

![image](https://user-images.githubusercontent.com/33861734/45417793-46d2ef00-b683-11e8-9d13-38f407f0a9ad.png)

**Comment by holalluis** [comment]
ok, I see

**Comment by holalluis** [comment]
solved
