### ISSUE TITLE
Rename outputs

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#161]
**Wastewater treatment:**
- Rename "From sludge mangement" to "Sludge Mangement"
- Rename "Biogas emissions" to "Biogas"
![image](https://user-images.githubusercontent.com/33861734/45409850-9bb93a00-b670-11e8-8d7e-03ed002d660d.png)

**FS Containment:**
- replace "FS" by "faecal sludge" - I think there is enough space so that we do not need abbreviations here
- Rename "FS Transport" to "Transport"
- Rename "From CH4" to "Methane emissions"
- Rename "Total GHG FSM Containment" to "Total GHG Faecal Sludge Containment"
![image](https://user-images.githubusercontent.com/33861734/45409641-10d83f80-b670-11e8-8c93-fdf30c49ee7b.png)

**FS Treatment**
- Rename "FS Transport" to "Transport"
- Rename "Total GHG in FSM Treatment" to "Total GHG Faecal Sludge Treatment"
![image](https://user-images.githubusercontent.com/33861734/45409923-cc996f00-b670-11e8-99ff-80927aedd09d.png)

**FS Reuse/Discharge**
- Rename "BOD concentration of FS" to "BOD concentration of faecal sludge"
- Rename "FS Transport" to "Transport"
- Rename "Total GHG in Reuse/Disposal" to "Total GHG Faecal Sludge Reuse/Disposal"
![image](https://user-images.githubusercontent.com/33861734/45410049-1a15dc00-b671-11e8-9030-b141c3c938d4.png)
![image](https://user-images.githubusercontent.com/33861734/45410190-6b25d000-b671-11e8-8e92-040e35907e99.png)

**Comment by Ranf16** [comment]
**Tier A**
- rename "Serviced population in FSM" to "Serviced population in Faecal Sludge Mangement"
- Rename "Resident population serviced with wastewater treatment" to "Resident population serviced with **W**astewater **T**reatment

![image](https://user-images.githubusercontent.com/33861734/45413928-95c85680-b67a-11e8-9b20-17efa18cc027.png)

**Comment by holalluis** [comment]
solved
