### ISSUE TITLE
Fix the message that appears if you click on the next button but only FSM stages are active

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#163]
1. If  only FSM stages are activated and you click on "Next" then the following message appears "here are no active stages. Click on the table to activate some.".

![image](https://user-images.githubusercontent.com/33861734/45429556-d9838600-b6a3-11e8-8b54-25d115aaf2ef.png)

2. One suggestion, I think we should add these "Previous" and "Next" buttons also on the end of each page. Just because some people rather work with the buttons. What do you think?
![image](https://user-images.githubusercontent.com/33861734/45429703-1e0f2180-b6a4-11e8-97b5-039418e66a47.png)

**Comment by holalluis** [comment]
solved and moved suggestion to a new issue
