### ISSUE TITLE
Insert the icons into ECAM

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#165]
**System icon**
![fsm_system](https://user-images.githubusercontent.com/33861734/45470515-55c2ab80-b72e-11e8-8791-f9bc37d54e2f.png)

**Containment icon**

![fsm_containment](https://user-images.githubusercontent.com/33861734/45470668-ee592b80-b72e-11e8-8fc6-390c543a35ab.png)

**Treatment icon**
![fsm_treatment](https://user-images.githubusercontent.com/33861734/45470684-fe710b00-b72e-11e8-9d24-659466b04b4b.png)

**Reuse/Disposal icon**

![fsm_reuse](https://user-images.githubusercontent.com/33861734/45470701-09c43680-b72f-11e8-8e50-5f96486ff21a.png)

--
**Insert these icons here:**
![image](https://user-images.githubusercontent.com/33861734/45470539-6bd06c00-b72e-11e8-9573-e08d82c8dd9b.png)

![image](https://user-images.githubusercontent.com/33861734/45470749-37a97b00-b72f-11e8-8157-7f601b147d30.png)

![image](https://user-images.githubusercontent.com/33861734/45470763-46902d80-b72f-11e8-80b5-41913c12e770.png)
![image](https://user-images.githubusercontent.com/33861734/45470801-5c055780-b72f-11e8-8955-087d8555ae8e.png)

**Comment by holalluis** [comment]
Thanks @Ranf16.
We still need the icons for when the stages are inactive (with grey background):

**Comment by holalluis** [comment]
![captura de pantalla 2018-09-13 a las 16 53 56](https://user-images.githubusercontent.com/1082644/45496392-a01b4b00-b775-11e8-8010-fe862b09fb04.png)
