### ISSUE TITLE
Fuel input in Tier A - activate filter in containment and save the total value only to that stage

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#166]
**Tier A - Fuel consumed**
- The fuel consumed in FSM is most likely only used for emtpying and transport from the containment stage to the treatment stage. Therefore, the value entered for fuel consumed (Transport) in Tier A should not be devided by 3 and written into each stage, instead save the whole value only to the input in the containment stage, i.e. fsc_trck_typ. 

**_**Note: Let me know if this is complicated to implement. We could discuss it. I know that it is different in the other systems but here it makes sense to do it.**_** 

- If a value for fuel in FSM is entered at Tier A level, the filter for "Evaluate emptying and transport of faecal sludge?" should be activated. Right now it remains deactivateded (as are the transport filters in the other stages)

**Comment by holalluis** [comment]
done. Please check. 

If you want, from now on, I'll leave the issues open and let you close them, as you check them.

(you can only close the issues that you opened)

**Comment by Ranf16** [comment]
works

**Comment by Ranf16** [comment]
Well, it what works is that if you enter in Tier A the value it only gets stored into the containmet stage. However, the following also needs to happen:
- if in Tier B you add also values for fuel (trasport) in the treatment stage or the reuse stage it should get added to the Tier A value and the input in Tier A should get the locked

**Comment by Ranf16** [comment]
If what I mentioned in the last comment can not be done, then please undo this change. 

That means the fuel from Tier A should be evenly splittet over the tree stages and the corresponding filters should be activated. If the user modifies the values in Tier B, the value in Tier A should be locked.

**Comment by holalluis** [comment]
done, please check
