### ISSUE TITLE
Rename "No containment" and update emission factor

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#167]
- Rename the Containment technology "No containment" to "No containment (open defecation)"
- Change the emission factor from 0 to 0.027045
--

![image](https://user-images.githubusercontent.com/33861734/45492230-0e5b1000-b76c-11e8-8c1d-0977bbae33bc.png)

**Comment by holalluis** [comment]
In this table we have two emission factors: depending on "is the containment experiencing flooding (yes/no)" we have a number or another, see screenshot:
![captura de pantalla 2018-09-13 a las 17 02 14](https://user-images.githubusercontent.com/1082644/45496945-cdb4c400-b776-11e8-956f-1085b418b992.png)

Shall I set both to 0.027045?

**Comment by Ranf16** [comment]
Yes, in both cases it is the same value.

**Comment by holalluis** [comment]
ok, done
