### ISSUE TITLE
Add estimate buttons to Wastewater treatment stage

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#169]
- Add estimate buttons that work the same way as in FSM to the wastewater treatment stage. At stage level it is only needed for the following tree values. 
The formula should be the same as what is applied in the in the already used estimations: see: http://84.89.61.64:8030/ecam/estimations.php

![image](https://user-images.githubusercontent.com/33861734/45498448-5123e480-b77a-11e8-9ba4-2f5d5a9d9be6.png)

**Comment by Ranf16** [comment]
Not sure if it is possible to have the estimate buttons also in the substages. I think they could at least write the value to the main stage.

If yes, then please add also these in the wastewater treatment substage:

![image](https://user-images.githubusercontent.com/33861734/45501956-ffcc2300-b782-11e8-9276-baec69bb9d22.png)

![image](https://user-images.githubusercontent.com/33861734/45501997-183c3d80-b783-11e8-966b-34323aec9a5d.png)

![image](https://user-images.githubusercontent.com/33861734/45502080-4d489000-b783-11e8-8c52-6e4fa23b9471.png)

**Comment by holalluis** [comment]
maybe we can think of moving the biogas question to stage level, I think it's important enough to do it (just because it appears in tier A)

**Comment by Ranf16** [comment]
But all the sludge management inputs are also important and they also appear in Tier A. I was actually thinking of putting them at stage level too. I think it would be clearer, but I am a bit afraid that it would be too many inputs at Tier A level. If you want you can do it.

**Comment by holalluis** [comment]
It's not too bad, considering that now we can fold sections corresponding to each filter, it would look like this:
![captura de pantalla 2018-09-13 a las 22 51 30](https://user-images.githubusercontent.com/1082644/45515154-a2969880-b7a7-11e8-92ec-e40fd4062fab.png)

If you agree, I'll keep it like the image above

**Comment by holalluis** [comment]
done, please check

**Comment by holalluis** [comment]
done, please check
