### ISSUE TITLE
reset button at tier A: include FSM new estimations

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#172]

**Comment by holalluis** [comment]
@Ranf16 this has been done. Please check if it is working as expected.
![captura de pantalla 2018-09-17 a las 19 44 49](https://user-images.githubusercontent.com/1082644/45640190-3b802900-bab2-11e8-8006-564b3792605d.png)

**Comment by Ranf16** [comment]
Just checked. works. You can close this issue
