### ISSUE TITLE
Issues when opening (old) json files

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#174]
1. In ECAM V.2.2 it shows emissions even from deactivated stages, i.e. wastewater treatment.

ECAM .V.2.
![image](https://user-images.githubusercontent.com/33861734/45631283-de2cad80-ba9a-11e8-9910-b21c524bbf43.png)

**Proposed solution**
-> If a stage is deactivated there should be no emissions from it in the graphs and tables. 

2. If you have ECAM open with FSM stages activated including inserted FSM values, and then you open an old json  file that was created with ECAM 2.0,  then the FSM stages remain activated and the values are still there. 

3. When opening files created with ECAM 2.0, we had the issue that some inputs were changed and need to be re-entered.  There is however the following issue: if you have an ECAM file open where the connected population is 100, then you open a file created with V.2.0 in which the connected Population was 500, then the value of 100 remains as input. This is very prone to errors in case the user does not realise that there where changes in the numbers. It would be better if the value were zero instead.

**Proposed solution**
-> Can you make that when a json file is opened, the tool first celares all existing values before loading the values of the json file. This should solve not only the issue that FSM is activated, but that some values are stored in the memory and appear in a file that you open.

**Comment by holalluis** [comment]
I think that this can be solved adding a new variable that is "N2O emission factor" that is 0 by default, and removing the constant 3.2 gN2O/person/day
![captura de pantalla 2018-09-18 a las 21 08 51](https://user-images.githubusercontent.com/1082644/45710516-1e695a00-bb87-11e8-85ba-6da90d914213.png)

**Comment by holalluis** [comment]
And for the issue of FSM, it should work with the new Substages structure. This was because each cookie for each stage was a different one. Now all the info for Substages is in a single cookie

**Comment by Ranf16** [comment]
Regarding issue 2 and 3: 

> 2. If you have ECAM open with FSM stages activated including inserted FSM values, and then you open an old json file that was created with ECAM 2.0, then the FSM stages remain activated and the values are still there.

> 3. When  opening files created with ECAM 2.0, we had the issue that some inputs were changed and need to be re-entered. There is however the following issue: if you have an ECAM file open where the connected population is 100, then you open a file created with V.2.0 in which the connected Population was 500, then the value of 100 remains as input. This is very prone to errors in case the user does not realise that there where changes in the numbers. It would be better if the value were zero instead.

I just tried and the issue is still there. The issue of no. 3 not only affects the population numbers but also other values that have changed between V.2.0 and 2.1. for example also the BOD5 value specified on the configuration page.

I can record a video tomorrow to demonstrate it, or we skype in the afternoon at 4 pm.

**Comment by holalluis** [comment]
I can skype tomorrow at 4pm

**Comment by Ranf16** [comment]
Please see the following video that shows the issues No. 2 and 3:

https://www.dropbox.com/s/p0sz065lzxgvwn1/Isse%20opening%20old%20files.mp4?dl=0

**Comment by holalluis** [comment]
[Madaba Q4- 2017_Final28032018.txt](https://github.com/icra/ecam/files/2398066/Madaba.Q4-.2017_Final28032018.txt)

**Comment by holalluis** [comment]
Hi, I've implemented the proposed solution. All issues commented here should be solved. Please check
