### ISSUE TITLE
When hoving over the estimate buttons there are 2 context windows on top of each other

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#175]
See screenshot. It would be nice if you could actually see the formula however the desciption covers it.

![image](https://user-images.githubusercontent.com/33861734/45677481-98242800-bb34-11e8-88fb-78cbdb4941e3.png)

**Comment by holalluis** [comment]
Hi, I've solved this making that the description only appears when the mouse is over the text, not the cell. please check
