### ISSUE TITLE
in level2 and level3: hide related questions when user clicks at 'hide' filter 

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#177]
Example: SM
All the related filters for SM should hide when the user hides/folds SM
![captura de pantalla 2018-09-18 a las 19 21 21](https://user-images.githubusercontent.com/1082644/45704746-0ccc8600-bb78-11e8-887e-3d61770f2f13.png)

**Comment by Ranf16** [comment]
This is done at stage level, but at substage level it still does not hide the related filters. 

![image](https://user-images.githubusercontent.com/33861734/45748133-261d1300-bc08-11e8-99b4-59ed171c1916.png)
