### ISSUE TITLE
Update the EF for containment

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#178]
See updated values and names in the table below (changes are marked in red):
![image](https://user-images.githubusercontent.com/33861734/45739016-2c07f980-bbf2-11e8-9d00-185d8450fe00.png)

Note that the value of the septic tank is always 0.6; it is not affected by the question "Is the containment experiencing flooding or groundwater infiltration?"

![image](https://user-images.githubusercontent.com/33861734/45737976-7fc51380-bbef-11e8-9fba-190b11a4878e.png)

**Comment by holalluis** [comment]
done please check

**Comment by Ranf16** [comment]
- Please change the steptic tank again as follows and rename it:

![image](https://user-images.githubusercontent.com/33861734/45780315-9dc95d00-bc5d-11e8-9afb-12a1e257a0e2.png)

- Change the value for "open defecation" to 0.027 (less digits)
![image](https://user-images.githubusercontent.com/33861734/45780496-00baf400-bc5e-11e8-831d-b1bdb2bf02e2.png)

**Comment by holalluis** [comment]
done, please check
