### ISSUE TITLE
Add also methane emissions from effluent

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#181]
We have partially omitted this so far, but it would be more correct to include it:

**1. FSM reuse stage:**

- Create a new filter "Evaluate emissions from effluent discharge" (everything in here is not assessed in Tier A):
- Add 1 new input "Effluent BOD load" in kg
- Add 1 new emission factor "CH4 emission factor" (drop down menu):
  
```
The options in the drop down menu shall be:

-Select (0)
-Stagnant sewer and anaerobic water bodies (0.3)
-Sea and aerobic water bodies (0.06)
-Fast flowing and well maintained sewers (0)
-Soil infiltration (0)
```

- Create new output "methane emissions from effluent"
= Effluent BOD load * CH4 emission factor  * ct_ch4_eq  

- Create new output to sum up CH4 and N2O from effluent "Emissions from effluent discharge":
= methane emissions from effluent + fsr_KPI_GHG_tre_n2o

- show "Emissions from effluent discharge" instead of fsr_KPI_GHG_tre_n2o in the output table

- Put also fsr_n2o_effl and fsr_vol_disc into this new filter:
![image](https://user-images.githubusercontent.com/33861734/45777405-f85ebb00-bc55-11e8-8301-c6265845c194.png)

**2. Wastewater discharge stage**
- Add new input "Effluent BOD load". This shall have an estimate button which shall get the same value already stored in wwt_bod_effl. If possible this shall happen already in Tier A. 
- Add 1 new emission factor "CH4 emission factor" (drop down menu):
  
```
The options in the drop down menu shall be:

-Select (0)
-Stagnant sewer and anaerobic water bodies (0.3)
-Sea and aerobic water bodies (0.06) <- default value
-Fast flowing and well maintained sewers (0)
```
- Create new output "methane emissions from effluent"
= Effluent BOD load * CH4 emission factor  * ct_ch4_eq  

- Create new output to sum up CH4 and N2O from effluent "Emissions from effluent discharge":
= methane emissions from effluent + wwd_KPI_GHG_tre_n2o

- show "Emissions from effluent discharge" instead of wwd_KPI_GHG_tre_n2o in output table

**3. Add these new methane emissions also to the graphs:**
  - Source Graph: add to CH4 emissions

  - UNFCC categories:
![image](https://user-images.githubusercontent.com/33861734/45777286-ac137b00-bc55-11e8-9ad5-cbb2029bc2c4.png)
  

  - Sources (detailed) Graph:
![image](https://user-images.githubusercontent.com/33861734/45777222-7ec6cd00-bc55-11e8-987a-485834e53b6b.png)

**Comment by Ranf16** [comment]
works. 

But please change the name of the outputs

![image](https://user-images.githubusercontent.com/33861734/45801430-2f63b980-bcb4-11e8-8e82-05bf67ee7ce1.png)

![image](https://user-images.githubusercontent.com/33861734/45801489-4f937880-bcb4-11e8-99c8-5458ed184306.png)

**Comment by holalluis** [comment]
ok, it's almost done.
@Ranf16 There are two emission factors in FSM Reuse:
1. CH4 emission factor for effluent discharge
2. CH4 emission factor for dumping 

The option "Soil infiltration (0)" should be only in dumping, or in both?
Thanks

**Comment by holalluis** [comment]
done please check
