### ISSUE TITLE
Tier A inputs are folded when you open a file

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#183]
Did you do this for a reason? My immediate thought would be that it would be better if this is still unfolded.

![image](https://user-images.githubusercontent.com/33861734/45803043-caf72900-bcb8-11e8-82c5-865cef15e354.png)

**Comment by holalluis** [comment]
This is because of setting to 0 all inputs when loading a file from previous issue. There are some internal variables saved inside cookies also called "expanded" which control if the stage is visible or not. If expanded equals 0, then the stage becomes invisible. I'll change this

**Comment by holalluis** [comment]
done, please check
