### ISSUE TITLE
Decrease the width of the GHG summary table

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#184]
The table of GHG summary has changed. I think the rectangulars are now too long and it looked overall nicer before. 

**- Please use the design from before.** 
do these adaptions to how it looked before
- put the population not in bold letters
- use bold letters for the GHG numbers

See image blow
![image](https://user-images.githubusercontent.com/33861734/45885373-923d7980-bdb6-11e8-8a09-a4781f58941b.png)

**Now it looks like this, please update change the design the the what is described above:**
![image](https://user-images.githubusercontent.com/33861734/45874432-21399a00-bd95-11e8-8bdd-131a2f1254f0.png)

**Comment by holalluis** [comment]
It's fixed, sorry, I tried to add the icon of the stage but I made the whole cell wider
