### ISSUE TITLE
Emission factors are shown as zero if they are too small

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#185]
Small emissions factors, for exaple from Composting which is 0.0013 ae shown as 0 even though they aren't . I think this is not good.
-  Can you specify that at least at least 3 decimals are shown. Then  it should still display it as 0.001

![image](https://user-images.githubusercontent.com/33861734/45889792-99b65000-bdc1-11e8-929e-350d9bf8c1cc.png)

![image](https://user-images.githubusercontent.com/33861734/45889825-ad61b680-bdc1-11e8-8267-33a0ce8ff70f.png)

**Comment by holalluis** [comment]
I created a special rule that if the number is below 0.01, then the number of decimals is 4, so now the number appears correctly

**Comment by Ranf16** [comment]
good idea. 

In this case I think we should show the whole value of "No containment - open defecation" of 0.027 and not only 0.03. This might be misleading

**Comment by holalluis** [comment]
Hi, having solved the issue #186 solved this one. please check
