### ISSUE TITLE
Define rules for the number of decimals of numbers in tables

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#186]
The values shown in the tables sometimes have decimals and sometimes not (see screenshots). This is not helpful if you want to compare the values. This affects:
- tables of graphs
- GHG summary
- tables of outputs in the stages and substages

_Proposed solution: Can you define rules as following:?_

**A: for the tables, excpet the values per person/assessment period and per m³** 
- values have by default no decimals
- Exceptions are values that a lower than 100, these can have 2 decimals

**B: Values per person/assessment period and per m³**
- values have by default 2 decimals 
- Exceptions are values that are smaller than 0.01, these can have 4 decimals. 

![image](https://user-images.githubusercontent.com/33861734/45941785-04dd6d80-bfe0-11e8-8895-517761d4b6c7.png)

![image](https://user-images.githubusercontent.com/33861734/45941550-f6db1d00-bfde-11e8-984b-8ef098723cb5.png)

![image](https://user-images.githubusercontent.com/33861734/45941869-6b628b80-bfe0-11e8-8732-e4f30b29581c.png)

![image](https://user-images.githubusercontent.com/33861734/45941894-892ff080-bfe0-11e8-8976-3271f870791e.png)

**Comment by holalluis** [comment]
Hi, I've adopted this solution for the whole tool:
![captura de pantalla 2018-09-28 a las 23 29 40](https://user-images.githubusercontent.com/1082644/46234416-89304780-c376-11e8-9cdb-fa9c506a8fdd.png)
I think it improves the overall readability
