### ISSUE TITLE
Create A new filter for N2O correction factor and adapt the description

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#187]
Create a filter "Do you want to revise the default N2O emissions?"

Put this input into this filter
![image](https://user-images.githubusercontent.com/33861734/46012033-1ac65d80-c0c8-11e8-9924-8931643b45b8.png)

Change the description of this input to the following:

#wwt_GHG_tre_n2o_expla |    ECAM uses a generic   emissions factor from IPCC to calculate N2O emissions. If you have more   accurate values of N2O emissions you can add the positive or negative   difference to calculated value to adapt the result.
-- | --

**Comment by holalluis** [comment]
done, please check
