### ISSUE TITLE
Include Energy in the Tier A graph heading

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#189]
1/ The energy consumption sum that is displayed in the bracket does not include the FS part.  When there is consumption by water supply and wastewater part it only sums those two components, even if it displays the FS contribution in the pie chart and the table.
  
![image](https://user-images.githubusercontent.com/33861734/46295834-4ef2c000-c599-11e8-8218-c9f9b1ce796f.png)

As it is shown on the below graph, there is energy consumption in the FS part but the quantity is shown as “zero” which is wrong.
 
![image](https://user-images.githubusercontent.com/33861734/46295839-51edb080-c599-11e8-8f67-8277b69098b5.png)

**Comment by holalluis** [comment]
solved, please check
