### ISSUE TITLE
Remove magic number from GHG emissions avoided due to reuse

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#193]
**- Replace the 4 in the following equations by:**

- Name: Credit for Nitrogen; value: 4; unit  kg CO2/kg N

![image](https://user-images.githubusercontent.com/33861734/46335503-fddddd00-c627-11e8-989f-0a1afb3f1e45.png)
![image](https://user-images.githubusercontent.com/33861734/46335517-06ceae80-c628-11e8-9a03-eedf6ddfdcb9.png)

**- Replace the 2 in the following equations by:**

- Name: Credit for Phosphorus; value 2; unit kg CO2/kg P

![image](https://user-images.githubusercontent.com/33861734/46335612-49908680-c628-11e8-80a8-8528d7d84ab9.png)
![image](https://user-images.githubusercontent.com/33861734/46335629-5a40fc80-c628-11e8-80fa-9542fc99e7cb.png)

**Comment by holalluis** [comment]
done please check
