### ISSUE TITLE
Remove magic number from carbon sequestration

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#194]
Replace the 0.25 in the equations below by:

- Name: Carbon sequestration rate; value: 0.25; unit kg CO2e/kg

![image](https://user-images.githubusercontent.com/33861734/46338106-988dea00-c62f-11e8-943e-43cf1f7b4913.png)
![image](https://user-images.githubusercontent.com/33861734/46338968-e73c8380-c631-11e8-9bac-a5bb9cbdb629.png)
![image](https://user-images.githubusercontent.com/33861734/46338979-ec99ce00-c631-11e8-852f-dfcfb25639df.png)

**Comment by holalluis** [comment]
done please check
