### ISSUE TITLE
Remove Magic numbers from landfilling

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#195]
General comment:
- Insert space between  the actual formula and the part where it takes the values from the tables. 

**1. Carbon sequestration from landfilling**

![image](https://user-images.githubusercontent.com/33861734/46343554-6cc63080-c63e-11e8-8059-25d2aed6bcb1.png)
- 0.2: undecomposable organic fraction; no unit
- 44/12: C to CO2 conversion, no unit
- 0.56: Fraction of organic carbon in volatile solids

**2. fsr_KPI_GHG_landfil_n2o - Landfilling (N2O)**
![image](https://user-images.githubusercontent.com/33861734/46343828-5f5d7600-c63f-11e8-8ebb-6e966ac3749e.png)

- 0.015 N2O landfill emissions for low C:N ratio [%] (or make it 1.5%)

**3. fsr_KPI_GHG_landfil_ch4 - Landfilling (CH4) and also in wastewater treatment**
![image](https://user-images.githubusercontent.com/33861734/46344047-283b9480-c640-11e8-9a77-558943178628.png)
![image](https://user-images.githubusercontent.com/33861734/46344104-5caf5080-c640-11e8-8fdf-42d95d13bc14.png)

 

- DOCf – 80% - no unit
- Landfill uncertainty factor – 0.9 - no unit
- % decomposed in first 3 years – 69.9 - no unit
- C to CH4 conversion factor – 4/3, no unit
- Ch4 in landfill gas – 50%, no unit

**Comment by holalluis** [comment]
done please check
