### ISSUE TITLE
Add Thai translation

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#196]
edited: solved

**Comment by holalluis** [comment]
There are these ones still missing:

Missing tags in "es.json" | English text (currently not translated in "es.json")
-- | --
#below | below
#wwt_correction_factor | Do you want to revise the default N2O emissions
#wwd_KPI_GHG_tre_descr | Effluent discharge
#wwd_KPI_GHG_tre_ch4_descr | CH4 from effluent discharge
#wwd_bod_effl_descr | Effluent BOD load
#wwd_ch4_efac_descr | CH4 emission factor
#fsr_bod_effl_descr | Effluent BOD load
#fsr_effluent | Evaluate emissions from effluent discharge
#Fast flowing and well maintained sewers | Fast flowing and well maintained sewers
#Soil infiltration | Soil infiltration
#ww_ch4_efac_unt_descr | CH4 emission factor (untreated wastewater)
#ww_ch4_efac_unc_descr | CH4 emission factor (uncollected wastewater)
#fsr_KPI_GHG_tre_ch4_descr | CH4 from effluent discharge
#fsr_KPI_GHG_tre_descr | Effluent discharge
#fsr_ch4_efac_dumping_descr | CH4 emission factor
#fsr_ch4_efac_dumping_expla | Methane emission factor for faecal sludge dumping

**Comment by Ranf16** [comment]
Here are the items that you are said were missing, but I think it is already included above
:


Missing tags in    "es.json" | Thai translation
-- | --
#below | ด้านล่าง
#wwt_correction_factor | ต้องการเปลี่ยนค่าแฟกเตอร์การเกิดก๊าซ N2O
#wwd_KPI_GHG_tre_descr | น้ำเสียที่ผ่านการบำบัด
#wwd_KPI_GHG_tre_ch4_descr | ก๊าซ CH4 จากน้ำเสียที่ผ่านการบำบัด
#wwd_bod_effl_descr | ค่า BOD ในน้ำเสียที่ผ่านการบำบัด
#wwd_ch4_efac_descr | ค่าแฟกเตอร์การเกิดก๊าซ CH4
#fsr_bod_effl_descr | ค่า BOD ในน้ำเสียที่ผ่านการบำบัด
#fsr_effluent | ประเมินก๊าซเรือนกระจกจากน้ำเสียที่ผ่านการบำบัด
#Fast flowing and well maintained sewers | ลักษณะมีการไหลอย่างรวดเร็ว   และ ระบบท่อรวบรวมน้ำเสียได้รับการดูแลอย่างดี
#Soil infiltration | ซึมผ่านดิน
#ww_ch4_efac_unt_descr | ค่าแฟกเตอร์การเกิดก๊าซ CH4 (น้ำเสียที่ไม่ผ่านการบำบัด)
#ww_ch4_efac_unc_descr | ค่าแฟกเตอร์การเกิดก๊าซ CH4 (น้ำเสียที่ไม่ได้รับการรวบรวม)
#fsr_KPI_GHG_tre_ch4_descr | ก๊าซ CH4 จากการปล่อยน้ำเสียที่ผ่านการบำบัดสู่แหล่งน้ำ
#fsr_KPI_GHG_tre_descr | น้ำเสียที่ผ่านการบำบัดปล่อยสู่แหล่งน้ำ
#fsr_ch4_efac_dumping_descr | ค่าแฟกเตอร์การเกิดก๊าซ CH4
#fsr_ch4_efac_dumping_expla | ค่าแฟกเตอร์การเกิดก๊าซ   CH4 จากการเทกองสิ่งปฏิกูล

**Comment by holalluis** [comment]
done please check

**Comment by Ranf16** [comment]
The message that appear when you hove over the lock symbol in Tier A is not included in the translation .. It applies for the water supply, wastewater and FSM section

![image](https://user-images.githubusercontent.com/33861734/47375803-64b75900-d6f1-11e8-9f0c-0d82015dd390.png)


English | Thai
-- | --
Since you have entered more   detailed data in Tier B stage, you cannot modify this input. Now it displays   the sum of its related to Water supply stage´s inputs. If you still want to   modify it, please set its related inputs to 0 in Tier B. | เนื่องจากมีการเติมข้อมูลในระดับ B ค่านี้จึงไม่สามารถเปลี่ยนแปลงได้   ค่าที่แสดงนี้เป็นผลรวมของระบบน้ำ ที่ได้เลือกไว้ ถ้าต้องการเปลี่ยนแปลงค่านี้   ให้ตั้งค่าที่เกี่ยวข้องนี้ในระดับ B เป็น 0
Since you have entered more   detailed data in Tier B stage, you cannot modify this input. Now it   displays the sum of its related to Wastewater stage´s inputs. If you still   want to modify it, please set its related inputs to 0 in Tier B. | เนื่องจากมีการเติมข้อมูลในระดับ B ค่านี้จึงไม่สามารถเปลี่ยนแปลงได้   ค่าที่แสดงนี้เป็นผลรวมของระบบน้ำเสีย ที่ได้เลือกไว้   ถ้าต้องการเปลี่ยนแปลงค่านี้ ให้ตั้งค่าที่เกี่ยวข้องนี้ในระดับ B เป็น 0
Since you have entered more   detailed data in Tier B stage, you cannot modify this input. Now it displays   the sum of its related to Facecal Sludge Management stage´s inputs. If you   still want to modify it, please set its related inputs to 0 in Tier B. | เนื่องจากมีการเติมข้อมูลในระดับ B ค่านี้จึงไม่สามารถเปลี่ยนแปลงได้   ค่าที่แสดงนี้เป็นผลรวมของการจัดการสิ่งปฏิกูล ที่ได้เลือกไว้   ถ้าต้องการเปลี่ยนแปลงค่านี้ ให้ตั้งค่าที่เกี่ยวข้องนี้ในระดับ B เป็น 0

**Comment by Ranf16** [comment]
the description of the arrows in the substages is not included in the translation
![image](https://user-images.githubusercontent.com/33861734/47375863-8ca6bc80-d6f1-11e8-8232-55d09bb2e6d4.png)


Old | New
-- | --
Update the   stage value using this the total value | อัพเดทค่าในกระบวนการนี้เป็นผลรวมของหน่วยย่อย
Split the value among the substages | แบ่งค่านี้ตามแต่ละหน่วยย่อย

**Comment by Ranf16** [comment]
The "Tips" are not included in the translation.
![image](https://user-images.githubusercontent.com/33861734/47375899-9e885f80-d6f1-11e8-93ff-fbbd17974b87.png)


English | Thai
-- | --
Move the   mouse over outputs to highlight related inputs | เลื่อนเคอร์เซอร์เหนือผลลัพธ์   จะแสดงไฮไลท์ค่าที่ใช้ในการคำนวณ
Click on the   `untitled`substage header to change its name | กดเลือกที่นี่เพื่อเปลี่ยนชื่อ
Double click a graph to download it | กดเลือกสองครั้งที่กราฟเพื่อดาวน์โหลดกราฟ
Export results to Excel at Main Menu/Other/Export | ส่งออกผลการประเมินไปยังไฟล์ Excel ที่เมนูหลัก / อื่นๆ / ส่งออก
Move the mouse over   an output to see itsformula | เลื่อนเคอร์เซอร์เหนือผลลัพธ์ เพื่อแสดงสูตรการคำนวณ
Press ↑ and ↓ when   editing inputs to quickly increase/decrease the number | กดเครื่องหมาย ↑ และ↓ ตอนที่เติมข้อมูลเพื่อเพิ่มหรือลดค่าได้ง่ายขึ้น
Use fullscreen mode in your browser   to work more comfortably | กดขยายเต็มหน้าจอในหน้าเบราเซอร์เพื่อให้ใช้งานได้สะดวกขึ้น
Use the TAB key (⇥) to input values faster | กด TAB เพื่อให้ง่ายต่อการเติมข้อมูล

**Comment by Ranf16** [comment]
The explainations #ww_ch4_efac_unt_expla and #ww_ch4_efac_unc_expla of the two new emission factors in wastewater collection is missing from the translation:
![image](https://user-images.githubusercontent.com/33861734/47375953-c5469600-d6f1-11e8-93d0-73dce568e9d3.png)


  | English | New
-- | -- | --
ww_ch4_efac_unt_expla | Methane emission factor for untreated   wastewater. | ค่าแฟกเตอร์การเกิดก๊าซมีเทน สำหรับน้ำเสียที่ไม่ได้รับการบำบัด
ww_ch4_efac_unc | Methane emission factor for uncollected   wastewater. | ค่าแฟกเตอร์การเกิดก๊าซมีเทน   สำหรับน้ำเสียที่ไม่ได้รับการรวบรวม
