### ISSUE TITLE
Add Spanish translation

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#197]
edited (solved request)

**Comment by holalluis** [comment]
Missing tags in "es.json" | English text (currently not translated in "es.json")
-- | --
#below | below
#wwt_correction_factor | Do you want to revise the default N2O emissions
#wwd_KPI_GHG_tre_descr | Effluent discharge
#wwd_KPI_GHG_tre_ch4_descr | CH4 from effluent discharge
#wwd_bod_effl_descr | Effluent BOD load
#wwd_ch4_efac_descr | CH4 emission factor
#fsr_bod_effl_descr | Effluent BOD load
#fsr_effluent | Evaluate emissions from effluent discharge
#Fast flowing and well maintained sewers | Fast flowing and well maintained sewers
#Soil infiltration | Soil infiltration
#ww_ch4_efac_unt_descr | CH4 emission factor (untreated wastewater)
#ww_ch4_efac_unc_descr | CH4 emission factor (uncollected wastewater)
#fsr_KPI_GHG_tre_ch4_descr | CH4 from effluent discharge
#fsr_KPI_GHG_tre_descr | Effluent discharge
#fsr_ch4_efac_dumping_descr | CH4 emission factor
#fsr_ch4_efac_dumping_expla | Methane emission factor for faecal sludge dumping

**Comment by Ranf16** [comment]
Here are the missing ones:


Code | Spanish
-- | --
#below | abajo
#wwt_correction_factor | Quiere revisar los valores por defecto de las emisiones   de N2O
#wwd_KPI_GHG_tre_descr | Descarga del efluente
#wwd_KPI_GHG_tre_ch4_descr | CH4 de la descarga del efluente
#wwd_bod_effl_descr | Carga de DBO del efluente
#wwd_ch4_efac_descr | Factor de emisión del CH4
#fsr_bod_effl_descr | Carga de DBO del efluente
#fsr_effluent | Evaluar las emisiones de la descarga del efluente
#Fast flowing and well maintained sewers | Alcantarillado rápido y en buenas condiciones
#Soil infiltration | Infiltración del suelo
#ww_ch4_efac_unt_descr | Factor de emisión del CH4 (agua residual sin tratar)
#ww_ch4_efac_unc_descr | Factor de emisión del CH4 (agua residual sin   recolectar)
#fsr_KPI_GHG_tre_ch4_descr | CH4 de la descarga del efluente
#fsr_KPI_GHG_tre_descr | Descarga del efluente
#fsr_ch4_efac_dumping_descr | Factor de emisión del CH4
#fsr_ch4_efac_dumping_expla | Factor de emisión del metano en el vertimiento de lodos   fecales
#Septic Tanks | Tanques sépticos

**Comment by holalluis** [comment]
done please check

**Comment by Ranf16** [comment]
The translation for abbreviation is missing. 
![image](https://user-images.githubusercontent.com/33861734/46787705-a5e65b00-cd38-11e8-8166-fe73706d733d.png)

In Spanish it is "Abreviaciones" I will provide the other translations later.

**Comment by Ranf16** [comment]
The information in the reset button is not included in the translations.

![image](https://user-images.githubusercontent.com/33861734/46787996-6e2be300-cd39-11e8-835d-45f7dc308928.png)


For Spanish it is the following, I will provide the other languages later:

El botón de reiniciado hace diferentes cosas

Old | New
-- | --
Sets the tier B values to 0, except the tier A        ones. | Fija los valores del Nivel B 0 , excepto los del Nivel A
Sets "Are you producing biogas?" to        "No". | Fija en “No”, la pregunta “ ¿Está produciendo biogás?
Sets "Are you valorizing biogas?" to        "No". | Fija en “No”, la pregunta “ ¿Está valorizando el biogás?
Sets "Select main treatment type" to        "None". | Fija “Seleccione principal tipo de tratamiento” en ninguno
Sets "Select sludge disposal method"        to "None". | Fija “Seleccione el método de disposición de lodos “ en   ninguno
Sets the 4 options for Faecal Sludge Management        to default (Containment type, treatment type, disposal type and type of        faecal sludge). | Fija las 4 opciones predeterminadas para la gestión de los lodos fecales

Todos los valores de entrada que tienen estimaciones se ponen en cero

Old | New
-- | --
Wastewater estimations set to 0: | Estimaciones del agua residual fijadas en 0:
Biogas produced = 0 | Biogás producido=0
Percentage of methane in biogas = 0 | Porcentaje de metano en el biogás
Biogas valorised = 0 | Biogás valorizado
Biogas flared = 0 | Biogás quemado
Influent BOD load = 0 | Carga de DBO del afluente
Effluent BOD load = 0 | Carga de DBO del efluente
BOD removed as sludge = 0 | DBO removido como lodo
CH4 emission factor = 0 | Factor de emisión del CH4
Sludge produced in WWTPs = 0 | Lodo producido en las PTARs
Dry weight in sludge produced = 0 | Peso seco de los lodos producidos
Sludge composted = 0 | Lodo compostado
Sludge incinerated = 0 | Lodo incinerado
Sludge sent to land application = 0 | Lodos enviado a aplicación en suelos
Sludge sent to landfilling = 0 | Lodo enviado a rellono sanitario
Sludge stockpiled = 0 | Lodo amontonado
Fluidized Bed Reactor Temperature = 0 | Temperatura del reactor de lecho fluidizado



Old | New
-- | --
Wastewater estimations set to 0: | Estimaciones del agua residual fijadas en 0:
Biogas produced = 0 | Biogás producido=0
Percentage of methane in biogas = 0 | Porcentaje de metano en el biogás
Biogas valorised = 0 | Biogás valorizado
Biogas flared = 0 | Biogás quemado
Influent BOD load = 0 | Carga de DBO del afluente
Effluent BOD load = 0 | Carga de DBO del efluente
BOD removed as sludge = 0 | DBO removido como lodo
CH4 emission factor = 0 | Factor de emisión del CH4
Sludge produced in WWTPs = 0 | Lodo producido en las PTARs
Dry weight in sludge produced = 0 | Peso seco de los lodos producidos
Sludge composted = 0 | Lodo compostado
Sludge incinerated = 0 | Lodo incinerado
Sludge sent to land application = 0 | Lodos enviado a aplicación en suelos
Sludge sent to landfilling = 0 | Lodo enviado a rellono sanitario
Sludge stockpiled = 0 | Lodo amontonado
Fluidized Bed Reactor Temperature = 0 | Temperatura del reactor de lecho fluidizado

Las estimaciones serán recalculadas nuevamente, rellenando los campos de los valores de entrada y las opciones. Tenga en cuenta que este botón no afecta a las posibles subetapas que el usuario ha creado previamente.

**Comment by Ranf16** [comment]
The message that appear when you hove over the lock symbol in Tier A is not included in the translation .. It applies for the water supply, wastewater and FSM section 

![image](https://user-images.githubusercontent.com/33861734/46788427-56089380-cd3a-11e8-8983-d0a7324630e5.png)


Here is the Spanish translation:


Old | New
-- | --
Since you have entered more   detailed data in Tier B stage, you cannot modify this input. Now it displays   the sum of its related to Water supply stage´s inputs. If you still want to   modify it, please set its related inputs to 0 in Tier B. | Ya que se han ingresado datos más detallados en el   Nivel B, no puede modificar este valor de entrada. Ahora, esta muestra la   suma de los valores de entrada relacionados con la etapa de suministro de   agua. Si aún desea modificarlo, por favor fije todos los valores de entrada   del Nivel B en 0.
Since you have entered more   detailed data in Tier B stage, you cannot modify this input. Now it   displays the sum of its related to Wastewater stage´s inputs. If you still   want to modify it, please set its related inputs to 0 in Tier B. | Ya que se han ingresado datos más detallados en el   Nivel B, no puede modificar este valor de entrada. Ahora, esta muestra la   suma de los valores de entrada relacionados con la etapa de aguas residuales.   Si aún desea modificarlo, por favor fije todos los valores de entrada del   Nivel B en 0.
Since you have entered more   detailed data in Tier B stage, you cannot modify this input. Now it displays   the sum of its related to Facecal Sludge Management stage´s inputs. If you   still want to modify it, please set its related inputs to 0 in Tier B. | Ya que se han ingresado datos más detallados en el Nivel   B, no puede modificar este valor de entrada. Ahora, esta muestra la suma de   los valores de entrada relacionados con la etapa de gestión de lodos fecales.   Si aún desea modificarlo, por favor fije todos los valores de entrada del   Nivel B en 0.

**Comment by Ranf16** [comment]
The description of the arrows in the substages is not included in the translation

![image](https://user-images.githubusercontent.com/33861734/46788938-97e60980-cd3b-11e8-9fed-d6454725d09c.png)

Here is the Spanish translation

Old | New
-- | --
Update the   stage value using this the total value | Actualizar el   valor de la etapa usando este valor total
Split the value among the substages | Dividir el valor   entre las subetapas

**Comment by Ranf16** [comment]
The "Tips" are not included in the translation.

![image](https://user-images.githubusercontent.com/33861734/46789110-07f48f80-cd3c-11e8-856c-41bcc75d8c8b.png)



Here is the Spanish translation:


Old | New
-- | --
Move the   mouse over outputs to highlight related inputs | Mueva el ratón   sobre los resultados para resaltar los valores de entrada relacionados
Click on the   `untitled`substage header to change its name | Haga click en el   encabezado de la subetapa “sin título”    para cambiar el nombre
Double click a graph to download it | Haga doble click   en un gráfico para descargarlo
Export results to Excel at Main Menu/Other/Export | Exporte los   resultados a Excel en el menú principal/Otro/exportar
Move the mouse over   an output to see itsformula | Mueva el ratón   sobre el resultado para ver su ecuación
Press ↑ and ↓ when   editing inputs to quickly increase/decrease the number | Presione ↑ y ↓ para editar, aumentar, disminuir, los valores   de entrada rápidamente.
Use fullscreen mode in your browser   to work more comfortably | Utilice el modo   de pantalla completa en su navegador para trabajar más cómodamente
Use the TAB key (⇥) to input values faster | Use la tecla TAB   () para introducir los valores de entrada más rápidamente.

**Comment by Ranf16** [comment]
The explainations **#ww_ch4_efac_unt_expla** and  **#ww_ch4_efac_unc_expla** of the two new emission factors in wastewater collection is missing from the translation:

![image](https://user-images.githubusercontent.com/33861734/46789734-7ede5800-cd3d-11e8-97d9-e992d004b923.png)


  | English | Spanish
-- | -- | --
ww_ch4_efac_unt_expla | Methane emission factor for   untreated wastewater. | Factor   de emisión del metano de aguas residuales no tratadas
ww_ch4_efac_unc | Methane   emission factor for uncollected wastewater. | Factor   de emisión del metano de aguas residuales no colectadas[RF1]

**Comment by Ranf16** [comment]
The word "People" in the stages and substages of Wastewater collection, wastewater treatment is not translated. Please add the translations:


English | Spanish | French | Thai
-- | -- | -- | --
People | Personas | Personnes | คน

**Comment by holalluis** [comment]
Comments:
1. There are several variables without explanation for all languages, I'll create a separate issue for this
2. I'll create a separate issue for tips
3. I'll create a separate issue for the translation of the reset button on tier A
4. There is a small complexity for the descriptions of lock symbols on tier A, I'll create separate issue.
5. The rest of requests is done
