### ISSUE TITLE
Add French translation

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#198]
edited: solved

**Comment by holalluis** [comment]
done please check

**Comment by Ranf16** [comment]
this is missing in the translations:
![image](https://user-images.githubusercontent.com/33861734/47157202-2123b000-d2e9-11e8-9d9c-df59a8ef5dd5.png)

"Entrez la population vivant à chaque niveau de votre système"

**Comment by Ranf16** [comment]
The translation for abbreviation is missing.
![image](https://user-images.githubusercontent.com/33861734/47157270-40224200-d2e9-11e8-889a-fafd933e2ead.png)

**abréviations**

**Comment by Ranf16** [comment]
The message that appear when you hove over the lock symbol in Tier A is not included in the translation .. It applies for the water supply, wastewater and FSM section
![image](https://user-images.githubusercontent.com/33861734/47157740-4b29a200-d2ea-11e8-98f4-d63b70c921ad.png)


**Translation:**

Since you have entered   more detailed data in Tier B stage, you cannot modify this input. Now it   displays the sum of its related to Facecal Sludge Management stage´s inputs.   If you still want to modify it, please set its related inputs to 0 in Tier B. | Comme vous avez   entré des données plus détaillées pour l’étape du tier B, vous ne pouvez pas   modifier cette entrée. Elle affiche maintenant la somme des entrées   correspondantes liées à l’étape de gestion des boues fécales. Si vous   souhaitez tout de même la modifier, fixez les entrées correspondantes dans le   tier B à 0.       .
-- | --
Since you have entered more detailed data in Tier B stage, you cannot   modify this input. Now it displays the sum of its related to   Wastewater stage´s inputs. If you still want to modify it, please set its   related inputs to 0 in Tier B. | Comme vous avez   entré des données plus détaillées pour l’étape du tier B, vous ne pouvez pas   modifier cette entrée. Elle affiche maintenant la somme des entrées   correspondantes liées à l’étape de gestion des eaux usées. Si vous souhaitez   tout de même la modifier, fixez les entrées correspondantes dans le tier B à   0
Since you have entered   more detailed data in Tier B stage, you cannot modify this input. Now it   displays the sum of its related to Water supply stage´s inputs. If you still   want to modify it, please set its related inputs to 0 in Tier B. | Comme vous avez   entré des données plus détaillées pour l’étape du tier B, vous ne pouvez pas   modifier cette entrée. Elle affiche maintenant la somme des entrées   correspondantes liées à l’étape d’approvisionnement en eau. Si vous souhaitez   tout de même la modifier, fixez les entrées correspondantes dans le tier B à   0.

**Comment by Ranf16** [comment]
The description of the arrows in the substages is not included in the translation
![image](https://user-images.githubusercontent.com/33861734/47157916-afe4fc80-d2ea-11e8-999f-7396bb4863fe.png)


Split stage value   (15,819,951) among substages | Partager la valeur   d’étape (15,819,951) entre les sous-étapes.
-- | --
Update the stage value   using this the total value | Mettre   à jour la valeur d’étape en utilisant la valeur totale
Split the value among the substages | Partager la valeur   entre les sous-étapes.

**Comment by Ranf16** [comment]
The "Tips" are not included in the translation.
![image](https://user-images.githubusercontent.com/33861734/47157965-db67e700-d2ea-11e8-8cd5-de2bed25c374.png)


Move the mouse over outputs to highlight related inputs | Déplacez la souris sur les sorties pour mettre en   évidence les entrées associées
-- | --
Click on the `untitled`substage header to change its   name | Cliquez sur l’en-tête `sans-titre` pour changer son   nom.
Double click a graph to download it | Double-cliquez sur un graphique pour le télécharger
Export results to Excel at   Main Menu/Other/Export | Exporter les résultats ver Excel dans le Menu Principal / Autre /   Exporter
Move the mouse over an output to see   itsformula | Déplacez la souris sur une sortie pour voir la   formule utilisée
Press ↑ and ↓ when editing inputs to quickly   increase/decrease the number | Appuyez ↑ et ↓ lors de l’édition des entrées pour augmenter / diminuer   rapidement la valeur
Use fullscreen mode in your   browser to work more comfortably | Utilisez le mode plein écran   dans votre navigateur pour travailler plus confortablement
Use the TAB key (⇥) to input values faster | Utilisez la touche TAB (→) pour   saisir les valeurs plus rapidement

**Comment by Ranf16** [comment]
The explainations #ww_ch4_efac_unt_expla and #ww_ch4_efac_unc_expla of the two new emission factors in wastewater collection is missing from the translation:
![image](https://user-images.githubusercontent.com/33861734/47158030-00f4f080-d2eb-11e8-8829-1991e2d6d3ee.png)



  | English | Spanish
-- | -- | --
ww_ch4_efac_unt_expla | Methane emission factor for untreated wastewater. | FFacteur d’émission de méthane pour les eaux usées   non traitées.
ww_ch4_efac_unc | Methane emission factor for uncollected wastewater. | FFacteur d’émission de méthane pour les eaux usées   non-collectées.

**Comment by Ranf16** [comment]
The word "People" in the stages and substages of Wastewater collection, wastewater treatment is not translated. Please add the translations:

English | Spanish | French | Thai
-- | -- | -- | --
People | Personas | Personnes |คน

**Comment by Ranf16** [comment]
Here is the French translation that was still missing:


Variable | French
-- | --
fsc_cont_emp | Fraction des boues de fécales vidangée du   confinement durant la période d'évaluation. La fraction doit être adaptée si   la vidange n'est que partielle.
fsc_fslu_emp | Volume des boues fécales   vidangées du confinement
fsc_vol_trck       fst_vol_trck       sr_vol_trck | Volume   de carburant consommé (Camions)
fsc_trck_typ       fst_trck_typ       fsr_trck_typ | Type   de carburant (Camions)
fst_biog_pro | Biogaz   produits pendant la période d'évaluation par chaque usine de traitement des   boues fécales gérée par l'entreprise
fst_biog_val | Biogaz   valorisés dans l'usine de traitement, pour chauffer les digesteurs ou le   bâtiment et / ou faire fonctionner un cogénérateur pour générer de la chaleur   et de l'électricité par exemple
fst_biog_fla | Une torche à   biogaz désigne le biogaz qui est brûlé par des systèmes de torche à gaz sans   valorisation de l'électricité ou de la chaleur
fst_KPI_GHG | GES totaux   pour le traitement des boues fécales
fst_SL_GHG_avoided | Émissions de   GES évitées grâce à la valorisation des biogaz
  |  
fsr_mass_landfil | Poids   sec envoyé dans des centres d'enfouissement
fsr_fslu_typ_lf | Type   de boues (fécales) éliminées
fsr_disp_typ | Type   d’enfouissement
fsr_KPI_GHG_landfil_ch4 | Quantité de CO2,eq dues aux émissions de  CH4  provenant des   boues (fécales) épandues dans les décharges
fsr_KPI_GHG_landfil_n2o | Quantité de CO2,eq dues aux émissions de N2O provenant des boues (fécales)   épandues dans les décharges
fsr_KPI_GHG_landfil | Émissions   totales de GES issues des boues (fécales) envoyées à la décharge
fsr_ghg_avoided_landfil | Quantité   d’émissions en CO2,eq évitée par la   séquestration du dioxyde de carbone dans les sites d’enfouissement
  |  
fsr_mass_landapp | Quantité   de boues (fécales) envoyée à l’épandage (poids sec)
fsr_fslu_typ_la | Type   de boues (fécales) envoyées à l’épandage
fsr_soil_typ | Typologie du   sol sur laquelle les boues sont appliquées. Remarque: si vous ne connaissez   pas la typologie du sol, laissez-la en tant que "Texture fine".
fsr_KPI_GHG_landapp | Quantité de CO2,eq dues aux émissions de N2O provenant des boues fécales   envoyées à l’épandage
  |  
fsr_vol_dumping | Le volume de boues   fécales déversé
fsr_KPI_GHG_dumping_ch4 | Quantité de CO2,eq dues aux émissions de  CH4  provenant des   boues (fécales) déversées
fsr_KPI_GHG_dumping_n2o | Quantité de CO2,eq dues aux émissions de  N2O  provenant des boues (fécales) déversées
fsr_KPI_GHG_dumping | Émissions   totales de GES issues des boues (fécales) déversées
  |  
fsr_N_urine | Quantité   d’azote totale dans l’urine épandu
fsr_KPI_GHG_urine | Quantité de CO2,eq dues aux émissions de N2O provenant de l’épandage des   urines
  |  
fsr_reused_N | Quantité   d’azote totale réutilisée remplaçant les engrais synthétiques
fsr_reused_P | Quantité   de phosphore totale réutilisée remplaçant les engrais synthétiques
fsr_ghg_avoided_reuse_N | Émissions   de GES évitées par la réutilisation de l’azote
fsr_ghg_avoided_reuse_P | Émissions   de GES évitées par la réutilisation du phosphore
fsr_ghg_avoided_reuse | Émissions   de GES évitées par la réutilisation des nutriments remplaçant les engrais   synthétiques
