### ISSUE TITLE
constants descriptions are not translated

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#20]
they don't have a language tag associated

**Comment by holalluis** [comment]
they don't have a language tag associated

**Comment by holalluis** [comment]
![captura de pantalla 2018-05-15 a las 22 33 45](https://user-images.githubusercontent.com/1082644/40082030-115dc3a0-5890-11e8-977b-0b12e69a214a.png)

**Comment by ElaChe00** [comment]
For the translation at the end (January/February), it would be great to have some kind of module, where our translator can see the words easily and than write the translation next to it. This way, we might not overlook words that need to be translated. 

Is a translation interface feasible, Lluis? Nothing fancy, but maybe more intuitive as the current process of inserting the words via wordpad.

**Comment by ElaChe00** [comment]
@holalluis : Let's **close this issue** for now. We might need to start a whole new different process.
