### ISSUE TITLE
Fix formula for landfilling 

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#200]
There is an error in the formula. Instead of fsr_n2o_effl it should multiply by N_content of the respective sludge type (i.e. the new input, see other issue)

![image](https://user-images.githubusercontent.com/33861734/46816391-2cbd2700-cd7d-11e8-8bd2-27ed194e94f1.png)
![image](https://user-images.githubusercontent.com/33861734/46816424-3cd50680-cd7d-11e8-98b4-916558570039.png)

**Comment by Ranf16** [comment]
The formula is still the same - did you update the server?

**Comment by holalluis** [comment]
> The formula is still the same - did you update the server?

yes! http://84.89.61.64:8030/ecam/variable.php?id=fsr_KPI_GHG_landfil_n2o

![image](https://user-images.githubusercontent.com/1082644/47445469-3c932d00-d7b9-11e8-8fba-66caf16951f8.png)
