### ISSUE TITLE
Add missing descriptions 

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#202]
Please see the table below. I am still waiting for the French translation. 

Variable | English | Spanish | French | Thai
-- | -- | -- | -- | --
fsc_cont_emp | Fraction of produced faecal sludge that is emptied from containments   during the assessment period. If only partial emptying is done it should be   reflected in the fraction. | Fracción del lodo fecal producido que es vaciado de los contenedores   durante el periodo de evaluación |   | สัดส่วนจำนวนครั้งของการสูบสิ่งปฏิกูลจากวัสดุกักเก็บตลอดระยะเวลาเก็บข้อมูล
fsc_fslu_emp | Volume of faecal sludge emptied from the containment | Volumen de lodo fecal vaciado de los contenedores |   | ปริมาณสิ่งปฏิกูลที่สูบออกจากวัสดุกักเก็บ
fsc_vol_trck       fst_vol_trck       sr_vol_trck | Volume of fuel consumed (Trucks) | Volumen de consumo de combustible (camiones) | Volume de carburant consommé (Camions) | ปริมาณเชื้อเพลิงที่ใช้กับการขนส่ง
fsc_trck_typ       fst_trck_typ       fsr_trck_typ | Fuel type (Trucks) | Tipo de combustible (Camiones) | Type de carburant (Camions) | ชนิดเชื้อเพลิงที่ใช้กับการขนส่ง
fst_biog_pro | Biogas produced during the assessment period by each   faecal sludge treatment plant managed by the undertaking | Biogás producido durante el periodo de evaluación para   cado uno de los tratamiento del lodo fecal manejados por la empresa |   | ปริมาณก๊าซชีวภาพที่ผลิตได้จากระบบบำบัดสิ่งปฏิกูล   ในช่วงระยะเวลาเก็บข้อมูล
fst_biog_val | Biogas valorized in the treatment plant, for example   to heat the digesters or the building and/or to run a Co-generator to   generate heat and electricity | Biogás valorizado in la planta de tratamiento, por   ejemplo, para el calentamiento de los digestores o la construcción y/ó   funcionamiento de  un cogenerador para   la generación de calor y energía |   | ปริมาณก๊าซชีวภาพที่นำไปใช้ประโยชน์ภายในระบบบำบัด   เช่น นำไปให้ความร้อน กับถังย่อยสลาย หรือภายในอาคาร และ/หรือ   นำไปผลิตกระแสไฟฟ้า หรือพลังงานความร้อนในเครื่องผลิตกระแสไฟฟ้าร่วม
fst_biog_fla | Biogas flared refers to the biogas that is combusted   by flare gas systems without electricity or heat valorisation | Biogás quemado se refiere al biogás que es quemado en   una antorcha quemadora, sin la valorización de electricidad o calor. |   | ปริมาณก๊าซชีวภาพที่นำไปเผาทิ้ง   หรือ ก๊าซชีวภาพที่นำไปเผาทิ้งในระบบเตาเผา โดยไม่มีการนำไปใช้ประโยชน์   เพื่อการผลิตความร้อน หรือกระแสไฟฟ้า
fst_KPI_GHG | Total GHG Faecal sludge Treatment | GEI totales de la gestión de lodos fecales |   | ผลรวมปริมาณก๊าซเรือนกระจกจากระบบบำบัดสิ่งปฏิกูล
fst_SL_GHG_avoided | GHG emissions avoided due to biogas valorization | Emisiones de GEI evitados debido a la valorización del   biogás |   | ปริมาณก๊าซชีวภาพที่สามารถหลีกเลี่ยงการปลดปล่อยได้จากการนำมาใช้ประโยชน์
Landfilling |   |   |  
fsr_mass_landfil | Dry weight sent to landfill | Lodo fecal seco enviado al relleno sanitario |   | น้ำหนักแห้งที่ส่งไปยังหลุมฝังกลบ
fsr_fslu_typ_lf | Type of (faecal) sludge disposed |   |   | ชนิดของกากตะกอนที่นำไปกำจัด
fsr_disp_typ | Type of the landfilling | Tipo de lodo fecal desechado |   | ชนิดของการฝังกลบ
fsr_KPI_GHG_landfil_ch4 | Amount of CO2,eq emissions due to CH4    emission from (faecal) sludge applied   to landfill | Cantidad de CO2 eq debido a las emisiones de CH4 de los   lodos (fecales) depositados en rellenos sanitarios |   | ปริมาณก๊าซ CO2 เทียบเท่า จากก๊าซ CH4 ที่มาจากกระบวนการฝังกลบ
fsr_KPI_GHG_landfil_n2o | Amount of CO2,eq emissions due to N2O  emission from (faecal) sludge applied to   landfill | Cantidad de CO2 eq debido a las emisiones de N2O de los   lodos (fecales) depositados en rellenos sanitarios |   | ปริมาณก๊าซ CO2 เทียบเท่า จากก๊าซ N2O ที่มาจากกระบวนการฝังกลบ
fsr_KPI_GHG_landfil | Total GHG from (faecal) sludge sent to landfilling | GEI totales del envió de los  lodos fecales a rellenos sanitarios |   | ผลรวมปริมาณก๊าซเรือนกระจกจากการนำสิ่งปฏิกูลไปกำจัดด้วยวิธีฝังกลบ
fsr_ghg_avoided_landfil | Amount of CO2,eq emissions avoided from   carbon sequestration of landfilling | Emisiones de GEI evitadas debido al secuestro de   carbono en el relleno sanitario |   | ปริมาณก๊าซ CO2   เทียบเท่า ที่สามารถหลีกเลี่ยงการปล่อยได้จากการสะสมคาร์บอนในการฝังกลบ
Land   application |   |   |  
fsr_mass_landapp | Amount of (faecal) sludge that is sent to land   application (dry weight) | Lodo fecal seco enviado para la aplicación en el suelo |   | ปริมาณกากตะกอนที่นำไปใช้ปรับปรุงดิน   (น้ำหนักแห้ง)
fsr_fslu_typ_la | Type of (faecal) sludge sent to land application | Tipo de lodo fecal aplicado en el suelo |   | ชนิดของกากตะกอนที่นำไปใช้ปรับปรุงดิน
fsr_soil_typ | Soil typology the sludge is applied on. Note: if you   don't know the soil typology, leave it as 'Fine-textured' | Tipología del suelo donde el lodo es aplicado. Nota: si   no se conoce la tipología del suelo, deje el tipo 'Fine-textured' |   | ลักษณะของดินในพื้นที่   ที่นำกากตะกอนมาปรับปรุงดิน  กรณีไม่ทราบให้เลือกเป็นลักษณะดินละเอียด
fsr_KPI_GHG_landapp | Amount of CO2,eq emissions due to N2O  emission from faecal sludge sent to land   application | Cantidad de CO2 eq debido a las emisiones de N2O de los   lodos (fecales) aplicados en el suelo |   | ปริมาณก๊าซ CO2 เทียบเท่า จากก๊าซ N2O ที่เกิดจากการปรับปรุงดิน
Dumping |   |   |  
fsr_vol_dumping | The volume of faecal sludge dumped | Volumen de lodo fecal vertido |   | ปริมาณกากตะกอนที่ทิ้งไม่ถูกสุขลักษณะ
fsr_KPI_GHG_dumping_ch4 | Amount of CO2,eq emissions due to CH4  emission from (faecal) sludge dumped | Cantidad de CO2 eq debido a las emisiones de CH4 de los   lodos (fecales) vertidos |   | ปริมาณก๊าซ CO2 เทียบเท่า จากก๊าซ CH4 ที่เกิดจากการทิ้งกากตะกอนไม่ถูกสุขลักษณะ
fsr_KPI_GHG_dumping_n2o | Amount of CO2,eq emissions due to N2O  emission from (faecal) sludge dumped | Cantidad de CO2 eq debido a las emisiones de N2O de los   lodos (fecales) vertidos |   | ปริมาณก๊าซ CO2 เทียบเท่า จากก๊าซ N2O ที่เกิดจากการทิ้งกากตะกอนไม่ถูกสุขลักษณะ
fsr_KPI_GHG_dumping | Total GHG missions due to (faecal) sludge dumping | Emisiones totales de GEI debido al vertimiento de lodos   fecales |   | ผลรวมปริมาณก๊าซเรือนกระจกจากการทิ้งกากตะกอนไม่ถูกสุขลักษณะ
Urine   application |   |   |  
fsr_N_urine | Total Nitrogen in urine applied to land | Nitrógeno total en la orina aplicada en suelos |   | ปริมาณไนโตรเจนทั้งหมด   ในปัสสาวะที่นำไปใช้เพื่อการปรับปรุงดิน
fsr_KPI_GHG_urine | Amount of CO2,eq emissions due to N2O  emission from land application of urine | Cantidad de CO2 eq debido a las emisiones de N2O de los   lodos (fecales) vertidos de la orina   aplicada en suelos |   | ปริมาณก๊าซ CO2  เทียบเท่า จากก๊าซ N2O ที่เกิดจากการนำปัสสาวะไปปรับปรุงดิน
Reusing   nutrients |   |   |  
fsr_reused_N | Amount of total Nitrogen reused that displaces   synthetic fertilizer | Nitrógeno total reusado desplazando fertilizantes   sintéticos |   | ปริมาณไนโตรเจนทั้งหมด ที่ถูกนำกลับมาใช้ทดแทนปุ๋ยเคมี
fsr_reused_P | Amount of total Phosphorus reused that displaces   synthetic fertilizer | Fósforo total reusado desplazando fertilizantes   sintéticos |   | ปริมาณฟอสฟอรัสทั้งหมด   ที่ถูกนำกลับมาใช้ทดแทนปุ๋ยเคมี
fsr_ghg_avoided_reuse_N | Amount of CO2,eq emissions avoided due to   Nitrogen reuse | Cantidad de CO2 eq evitadas debido al reúso de   nitrógeno |   | ปริมาณก๊าซ CO2 เทียบเท่า   ที่สามารถหลีกเลี่ยงการปล่อยจากการนำไนโตรเจนกลับมาใช้
fsr_ghg_avoided_reuse_P | Amount of CO2,eq emissions avoided due to   Phosphorus reuse | Cantidad de CO2 eq evitadas debido al reúso de fósforo |   | ปริมาณก๊าซ CO2 เทียบเท่า   ที่สามารถหลีกเลี่ยงการปล่อยจากการนำฟอสฟอรัสกลับมาใช้
fsr_ghg_avoided_reuse | Amount of CO2,eq emissions avoided due to   nutrients reused displacing synthetic fertilizer | Cantidad de CO2 eq evitadas debido al reúso de   nutrientes desplazando fertilizantes sintéticos |   | ผลรวมปริมาณก๊าซ CO2เทียบเท่า ที่สามารถหลีกเลี่ยงการปล่อยจากการนำสารอาหารกลับมาใช้ทดแทนปุ๋ยเคมี

**Comment by holalluis** [comment]
moved to #203
