### ISSUE TITLE
Using the estimations for Total Nitrogen, and TVS are not triggered in Tier A

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#209]
The emissions from FSM landfilling and land application are currently always zero in Tier A because the estimations of the newly added inputs below are not used in the computation in Tier A.
- fsr_lf_N_cont
- fsr_lf_TVS
- fsr_la_N_cont

See screenshot, the estimations are there but the "current value" field is empty.
![image](https://user-images.githubusercontent.com/33861734/47846965-0d3c7b80-ddca-11e8-9e1d-4c133afaa20c.png)

![image](https://user-images.githubusercontent.com/33861734/47846983-1decf180-ddca-11e8-9e01-a2a911cc478a.png)

**Comment by holalluis** [comment]
done please check
