### ISSUE TITLE
tips are not translated

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#21]
they don't have a language tag associated

**Comment by holalluis** [comment]
they don't have a language tag associated

**Comment by holalluis** [comment]
The "Tips" are not included in the translation.
![image](https://user-images.githubusercontent.com/33861734/47375899-9e885f80-d6f1-11e8-93ff-fbbd17974b87.png)


English | Thai
-- | --
Move the   mouse over outputs to highlight related inputs | เลื่อนเคอร์เซอร์เหนือผลลัพธ์   จะแสดงไฮไลท์ค่าที่ใช้ในการคำนวณ
Click on the   `untitled`substage header to change its name | กดเลือกที่นี่เพื่อเปลี่ยนชื่อ
Double click a graph to download it | กดเลือกสองครั้งที่กราฟเพื่อดาวน์โหลดกราฟ
Export results to Excel at Main Menu/Other/Export | ส่งออกผลการประเมินไปยังไฟล์ Excel ที่เมนูหลัก / อื่นๆ / ส่งออก
Move the mouse over   an output to see itsformula | เลื่อนเคอร์เซอร์เหนือผลลัพธ์ เพื่อแสดงสูตรการคำนวณ
Press ↑ and ↓ when   editing inputs to quickly increase/decrease the number | กดเครื่องหมาย ↑ และ↓ ตอนที่เติมข้อมูลเพื่อเพิ่มหรือลดค่าได้ง่ายขึ้น
Use fullscreen mode in your browser   to work more comfortably | กดขยายเต็มหน้าจอในหน้าเบราเซอร์เพื่อให้ใช้งานได้สะดวกขึ้น
Use the TAB key (⇥) to input values faster | กด TAB เพื่อให้ง่ายต่อการเติมข้อมูล

**Comment by holalluis** [comment]
The "Tips" are not included in the translation.

![image](https://user-images.githubusercontent.com/33861734/46789110-07f48f80-cd3c-11e8-856c-41bcc75d8c8b.png)



Here is the Spanish translation:


Old | New
-- | --
Move the   mouse over outputs to highlight related inputs | Mueva el ratón   sobre los resultados para resaltar los valores de entrada relacionados
Click on the   `untitled`substage header to change its name | Haga click en el   encabezado de la subetapa “sin título”    para cambiar el nombre
Double click a graph to download it | Haga doble click   en un gráfico para descargarlo
Export results to Excel at Main Menu/Other/Export | Exporte los   resultados a Excel en el menú principal/Otro/exportar
Move the mouse over   an output to see itsformula | Mueva el ratón   sobre el resultado para ver su ecuación
Press ↑ and ↓ when   editing inputs to quickly increase/decrease the number | Presione ↑ y ↓ para editar, aumentar, disminuir, los valores   de entrada rápidamente.
Use fullscreen mode in your browser   to work more comfortably | Utilice el modo   de pantalla completa en su navegador para trabajar más cómodamente
Use the TAB key (⇥) to input values faster | Use la tecla TAB   (⇥) para introducir los valores de entrada más rápidamente.

**Comment by holalluis** [comment]
The "Tips" are not included in the translation.
![image](https://user-images.githubusercontent.com/33861734/47157965-db67e700-d2ea-11e8-8cd5-de2bed25c374.png)


Move the mouse over outputs to highlight related inputs | Déplacez la souris sur les sorties pour mettre en   évidence les entrées associées
-- | --
Click on the `untitled`substage header to change its   name | Cliquez sur l’en-tête `sans-titre` pour changer son   nom.
Double click a graph to download it | Double-cliquez sur un graphique pour le télécharger
Export results to Excel at   Main Menu/Other/Export | Exporter les résultats ver Excel dans le Menu Principal / Autre /   Exporter
Move the mouse over an output to see   itsformula | Déplacez la souris sur une sortie pour voir la   formule utilisée
Press ↑ and ↓ when editing inputs to quickly   increase/decrease the number | Appuyez ↑ et ↓ lors de l’édition des entrées pour augmenter / diminuer   rapidement la valeur
Use fullscreen mode in your   browser to work more comfortably | Utilisez le mode plein écran   dans votre navigateur pour travailler plus confortablement
Use the TAB key (⇥) to input values faster | Utilisez la touche TAB (→) pour   saisir les valeurs plus rapidement

**Comment by Ranf16** [comment]
Thanks. You can close this. I can't
