### ISSUE TITLE
Add a sepate input for BOD per person and day for FSM

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#210]
We need to be able to define separate BOD values per person and day for wastewater and faecal sludge. therefore please do the following changes:

1. Add an additional input for BOD in faecal sludge to the configuration page. When you select a country the value of this new BOD variable shall be the same as the existing BOD variable. The user shall be able to adapt this value.

2. Use the names indicated below for the two BOD variables:
- BOD generation (wastewater) <- this is the existing variable
- BOD generation (Faecal sludge)

![image](https://user-images.githubusercontent.com/33861734/47852424-01f24b80-dddc-11e8-90ed-b92a493ad893.png)

3. The old BOD variable (wastewater) needs to be replaced by the new BOD variable (faecal slduge) in this equation: 

 
![image](https://user-images.githubusercontent.com/33861734/47852285-960fe300-dddb-11e8-8601-87b871fb966c.png)

**Comment by Ranf16** [comment]
Here is the translation for the changes. Thai follows shortly:


English | Spanish | French | Thai
-- | -- | -- | --
BOD5   generation (wastewater) | DBO5   generado (aguas residuales) | DBO5 généré (eaux   usées) |  
BOD5   generation (faecal sludge) | DBO5   generado (lodos fecales) | DBO5 généré (boues de vidange) |

**Comment by holalluis** [comment]
done please check
