### ISSUE TITLE
Fix ECAM spelling in Titel

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#211]
**this is low priority and could be done after the launch

Except the "and" all words should start with a capital letter.

Energy **P**erformance and Carbon **E**missions Assessment and Monitoring Tool
 
![image](https://user-images.githubusercontent.com/33861734/48009146-5b7bb280-e11b-11e8-9e7c-01e6773e1d29.png)

**Comment by holalluis** [comment]
Hi Ranjin, I think that the logic here is make capital the words corresponding to ECAM (**E**nergy, **C**arbon, **A**ssessment, **M**onitoring)

**Comment by holalluis** [comment]
done
