### ISSUE TITLE
Make "Total nitrogen" and "Total Volitile Solids" also modifiable in the wastewater stage

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#212]
Dear Lluis,

I know this is not part of the recent contract, but could you please do still the following:

The inputs for Total nitrogen and total volatile solids in for landfilling and land application should be also modifiable in the wastewater treatment stage, just as it is the case in the FSM reuse stage. This means in Tier A these values shall be estimated according to the existing formulas, but in Tier B the user shall be also able to modify the values. The estimate buttons shall be also there.

1. **Landfilling**
- Make "vs_content" in the formula for "wwt_slu_landfill_ch4" an input named "Total Volatile Solids (% of dry weight)" , the default estimation for this value shall be according to the current formula
![image](https://user-images.githubusercontent.com/33861734/48718663-1d52b880-ec1c-11e8-9bf4-e074bfb4864a.png)

- Make the marked numbers an input named "total Nitrogen (% dry weight)". The default values shall be still 3% and 4% depending on if it's digested or undigested. 
![image](https://user-images.githubusercontent.com/33861734/48719431-c77f1000-ec1d-11e8-97ce-970b7580d577.png)

**2. Land application**
- Make the marked numbers an input named "Total Nitrogen (% of dry weight)". The default values shall be still 3%  and 4% depending on if it's digested or undigested. 
![image](https://user-images.githubusercontent.com/33861734/48720021-1d07ec80-ec1f-11e8-818e-ea46e9bb74ac.png)

3. Add the translation for these new inputs:

English | Spanish | French | Thai
-- | -- | -- | --
Total Nitrogen (% of dry weight) | Nitrógeno   Total (% materia seca) | Azote   total (% poids sec) | ไนโตรเจนทั้งหมด (%น้ำหนักแห้ง)
Total Volatile Solids (% of dry weight) | Sólidos Totales Volátiles (% materia seca) | Solides volatils totaux (% poids sec) | ของแข็งระเหยได้ทั้งหมด (%น้ำหนักแห้ง)

**Comment by Ranf16** [comment]
The result would look like what we have in FSM stage of reuse:
![image](https://user-images.githubusercontent.com/33861734/48733354-b1d01180-ec42-11e8-848d-1bb3f94dd9ec.png)

**Comment by holalluis** [comment]
done, please check (in the testing server: http://84.89.61.64:8030/ecam/)

**Comment by Ranf16** [comment]
There is an error with the unit.

The estimated default values should be 51% and 70% and not 0.51% abd 0.70%. See screenshot.
![image](https://user-images.githubusercontent.com/33861734/49015353-18918580-f183-11e8-80df-0e6cc10f9a6b.png)
![image](https://user-images.githubusercontent.com/33861734/49015417-58586d00-f183-11e8-97c2-f3eb4900ad43.png)


Besides that, everything works. Thanks a lot. Once the two estimations are fixed, please update the server

**Comment by Ranf16** [comment]
OK. now it works. Please release this version

**Comment by Ranf16** [comment]
Dear Lluis,

when we open older json files these new inputs are zero and the results are different. The user may not know why though.

Is there an easy fix so that when we open old-json files the default values are used and you don't need to click first on the estimate button?
