### ISSUE TITLE
German language File

### ISSUE THREAD

**Issue by TobiasGIZ** [icra/ecam#213]
Dear Lluis,

we prepared a german language file for ECAM and I would like to ask you to integrate this in the existing set of language options. Please find the de.json file attached, or should I upload the file directly to ecam/languages ?

[german.zip](https://github.com/icra/ecam/files/2643961/german.zip)

Thanks for your support
Tobias

**Comment by holalluis** [comment]
hi it's done, please check http://wacclim.org/ecam/
