### ISSUE TITLE
Arabic language option

### ISSUE THREAD

**Issue by TobiasGIZ** [icra/ecam#214]
Dear Lluis,
is it possible to create a arabic language option which can be seen in the list of languages without having a translated file ready yet? It could maybe look something like this:

![ecam_language_options](https://user-images.githubusercontent.com/43165578/49443838-be6d7180-f7cd-11e8-8023-c07cc3e39016.PNG)

The green flag is only an example and does not represent a general way to  symbolise arabic language. I will ask our colleagues from Jordan for some Input. Until we have a better solution we might want to use jordan flag instead.

Thanks and best regards
Tobias

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/49526399-05339800-f8b0-11e8-88e1-837e5054f50b.png)

Hi for now I've put the two new flags, and a message of "translation under development" for arabic. I'll let you know when the server is updated

**Comment by holalluis** [comment]
hi it's done, please check http://wacclim.org/ecam/
