### ISSUE TITLE
Update ECAM methodology guide

### ISSUE THREAD

**Issue by TobiasGIZ** [icra/ecam#215]
Hi, 
would it be possible to update ECAM methodology guide with the enclosed version 2.2? 

[ECAM Methodology Guide v2.2.pdf](https://github.com/icra/ecam/files/2646254/ECAM.Methodology.Guide.v2.2.pdf)

Thanks a lot,
Tobias

**Comment by holalluis** [comment]
hi it's done, please check http://wacclim.org/ecam/

**Comment by ElaChe00** [comment]
Hi Lluis,
there's a new [ECAM Methodology 2.2](http://wacclim.org/library/ecam-methodology-guide/ 
). Can this be updated on the **help** page?

Thanks much,
Elaine

**Comment by holalluis** [comment]
It's done.
Regards
