### ISSUE TITLE
tCO2e

### ISSUE THREAD

**Issue by Porro1jc** [icra/ecam#216]
give option in configuration to show GHG results in tCO2e or kg CO2e

**Comment by Porro1jc** [comment]
sorry it should affect Opportunities page as well.  and just in case it was not obvious, the output tables in each stage

**Comment by Porro1jc** [comment]
let's just do this if it is not more than one day.

**Comment by Porro1jc** [comment]
let me know how long it will take.

**Comment by holalluis** [comment]
I think that it would be approximately one full day because kg of CO2 is everywhere in the tool. What it would be easier is if it is only in ghg summary

**Comment by Porro1jc** [comment]
Ok let’s just do GHG summary and opportunities page for now. Let me know how long you think that would be.
