### ISSUE TITLE
Color of input cells 

### ISSUE THREAD

**Issue by Porro1jc** [icra/ecam#217]
use different color for input cells, so the user will be guided quickly where to enter data

**Comment by holalluis** [comment]
The current color for input cells is very clear, I don't see a problem with it
![captura de pantalla de 2018-12-17 15-35-35](https://user-images.githubusercontent.com/1082644/50093632-8aed0700-0211-11e9-8df0-3b9529e80dea.png)

**Comment by Porro1jc** [comment]
maybe a different color than grey.  grey sometimes means you can't edit.  maybe a light blue or light yellow?  if it does not look good then we can leave it.
