### ISSUE TITLE
catalog of solutions 

### ISSUE THREAD

**Issue by Porro1jc** [icra/ecam#218]
When you click [Catalogue of Solutions] link from opportunities page, it should not go directly to page, it should open up in separate window so that you can keep ECAM open.  

![image](https://user-images.githubusercontent.com/20580315/49884003-dcf0ef80-fe01-11e8-8122-0cfadccd3a4f.png)

**Comment by holalluis** [comment]
please check at http://84.89.61.64:8030/ecam/ and close the issue if it is working as expected.
