### ISSUE TITLE
Add Wastewater treatment coverage to Opportunities 

### ISSUE THREAD

**Issue by Porro1jc** [icra/ecam#220]
Still need to work this out.  Finding some problems.  Will update this issue later...

Add Wastewater Treatment coverage to both Opportunities table and to Measures table in Opportunities page.  

For calculation in both tables:

- Opportunities table: opportunity should be..."Wastewater treatment coverage" and value shown should be 0.01 x ww_KPI_GHG_unt

- Measures table: Measure should be.."Wastewater treatment service coverage" and for the calculation, it should be % time

**Comment by holalluis** [comment]
please make a final and clear issue statement before adding a new issue

**Comment by holalluis** [comment]
It's not deleted, it's closed. When clear, please reopen
