### ISSUE TITLE
untreated and uncollected wastewater EF

### ISSUE THREAD

**Issue by Porro1jc** [icra/ecam#221]
When opening an existing file, why are these zero in collection stage?

**Comment by holalluis** [comment]
because they have been added recently, and they don't have an initial value fixed

**Comment by holalluis** [comment]
I did a little bit of testing and the default values are 0.06 and 0.3 when starting from scratch. But when opening an old file, they are 0 because they didn't exist in the previous version, the solution is to fill the values, and save the file again, this way both variables will be inside the file
