### ISSUE TITLE
Sort out commas and decimals 

### ISSUE THREAD

**Issue by Porro1jc** [icra/ecam#224]
•	If you enter 34,000,000.00 than the system discards everything behind the “,”. If you enter 34000000 the systems accepts the figure and showed it this way “34,000,000”

**Comment by holalluis** [comment]
you should always enter the numbers without commas... this depends on how each browser treats the numbers, and different countries have different meaning for the commas, so the easiest is that the user enters only numbers and dot for decimals, not commas
