### ISSUE TITLE
Explanation of substages 

### ISSUE THREAD

**Issue by Porro1jc** [icra/ecam#226]
If you hover mouse over substage button, it should read the following:

If the stage is comprised of multiple substages, then you can enter data on a substage level by entering the data for the inputs listed under the substage and adding substages/data as necessary.  You can also use the single substage fields to enter more detailed data for the stage if it is not broken up into multiple substages.  

For example, there may be only one abstraction well but you would like to enter the pump efficiency information to assess pump efficiency.  You would then enter the pumping details at the substage level even if there is only one stage and no substages. The same approach is followed for treatment facilities, pumping facilities, and distribution and sewer network zones.

**Comment by holalluis** [comment]
and the rest of languages?

**Comment by Porro1jc** [comment]
let's just do it for English for now.  make a note that we still need to do other languages
