### ISSUE TITLE
Acknowledgement KWB

### ISSUE THREAD

**Issue by TobiasGIZ** [icra/ecam#227]
Dear Lluis,
could you please add the following phrase and Logo to the ECAM acknowledgment site:

“technical support by Komptenzzentrum Wasser Berlin gGmbH"

KWB reviewed ECAM tool and provided the german language file.
Thanks a lot.

![kwb logo](https://user-images.githubusercontent.com/43165578/51667123-95907e00-1fbf-11e9-847d-23a0164ee191.png)

**Comment by holalluis** [comment]
Dear Tobias, it's done.
Regards,
Lluís
