### ISSUE TITLE
Estimations for Total Nitrogen, and TVS (wastewater system) are not triggered in Tier A

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#228]
When selecting in Tier A a disposal method (wastewater system) the following estimations are not triggered but they should be. 

![image](https://user-images.githubusercontent.com/33861734/52294825-9390cc80-297a-11e9-86b5-97e2908a2490.png)

![image](https://user-images.githubusercontent.com/33861734/52294891-b8853f80-297a-11e9-9161-67dc51b9e94a.png)

**Comment by TobiasGIZ** [comment]
Ok, thanks for implementing.
