### ISSUE TITLE
Add functionality to assess pump efficiency

### ISSUE THREAD

**Issue by TobiasGIZ** [icra/ecam#231]
Add the functionality to assess pump efficiency, electromechanical efficiency and pumping opportunities also to the faecal sludge management stages. Basically the same inputs and outputs as we have them in wastewater collection should be added to the faecal sludge stages. While doing so, please make shure this assessment exists in the same form also in all the water supply and wastewater stages.

**Comment by TobiasGIZ** [comment]
I will send you the information where to copy the code.

**Comment by TobiasGIZ** [comment]
Please find the needed input in attached pdf:

[ECAM Issue 231.pdf](https://github.com/icra/ecam/files/3578386/ECAM.Issue.231.pdf)

**Comment by holalluis** [comment]
Under the water and wastewater stages the evaluation of pump efficiency and electromechanical
efficiency is sometimes asked, sometimes not. Also pump opportunities are not coherently assessed,
even if pump efficiency is asked. This should undergo some alignment, if applicable.

**Comment by holalluis** [comment]
the FSM part is done, but still not this one:

`Under the water and wastewater stages the evaluation of pump efficiency and electromechanical
efficiency is sometimes asked, sometimes not. Also pump opportunities are not coherently assessed,
even if pump efficiency is asked. This should undergo some alignment, if applicable.`

**Comment by TobiasGIZ** [comment]
Great job Lluis. Issue can be closed.
