### ISSUE TITLE
Changes on About page

### ISSUE THREAD

**Issue by TobiasGIZ** [icra/ecam#232]
Dear LLuis, 
could you please update the name of BMUB to the new official title, abbreviated BMU: The German Federal Minister for the Environment, Nature Conservation and Nuclear Safety. 

[About_page.pdf](https://github.com/icra/ecam/files/3088219/About_page.pdf)

![Landing Page](https://user-images.githubusercontent.com/43165578/56266640-65a3d300-60f5-11e9-9420-bbcd397ff4cb.PNG)

I'm not sure if this is part of the language files. In case it is, I can update the language files myself and pull a request to update them on GitHub. Please advise.

Best regards, Tobias

**Comment by holalluis** [comment]
dear tobias, it is done, sorry for the delay, please check http://wacclim.org/ecam/about.php
