### ISSUE TITLE
Missing translations in german

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#236]
Missing tags in "de.json" | English text (currently not translated in "de.json")
-- | --
#tier_A_lock_symbol | Since you have entered more detailed data in Tier B stage, you cannot modify this input. If you still want to modify it, please set its related inputs to 0 in Tier B.
#wwt_slu_lf_N_cont_descr | Total Nitrogen (% of dry weight)
#wwt_slu_lf_N_cont_expla | Total Nitrogen (% of dry weight)
#wwt_slu_lf_TVS_descr | Total Volatile Solids (% of dry weight)
#wwt_slu_lf_TVS_expla | Total Volatile Solids (% of dry weight)
#wwt_slu_la_N_cont_descr | Total Nitrogen (% of dry weight)
#wwt_slu_la_N_cont_expla | Total Nitrogen (% of dry weight)
#Coarse-Textured (<30% clay) | Coarse-Textured (<30% clay)
#Note: the emissions above have not been added in the totals presented in the GHG emissions summary | Note: the emissions above have not been added in the totals presented in the GHG emissions summary
#Split stage value among substages | Split stage value among substages

**Comment by AljoshaVieth** [comment]
I´d love to help you with that

**Comment by holalluis** [comment]
thank you @AljoshaVieth
