### ISSUE TITLE
Saving a json file in MS Edge is not possible.

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#239]
It is not possible to save json files when using Microsoft Edge browser. When you click on the button to save, nothing happens. Please see the video below.

https://www.dropbox.com/s/51o1tzhk7l0eeug/ECAM%20Edge%20not%20saving.mp4?dl=0

**Comment by holalluis** [comment]
I close this issue, since the save function is being redone from scratch, because of changes to backend. It will be possible to save with every browser correctly in v3
