### ISSUE TITLE
Data is not loading when opening a json file

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#240]
When trying to open some json files the data is not loaded.  The behaviour is different for the different browsers:

**1. Google Chrome:** 
- When trying to open the file attached (created with Firefox some days agao), all the values remain zero. 
When trying to open the file without clearing the existing data, nothing happens, i.e. the old values remain 

**2. Firefox:**
- When trying to open a file without clearing the existing data, nothing happens, i.e. the old values remain.
- When clearing the existing data however beforehand, the values are properly loaded. 

**3. Edge:**
- Loads everything fine. The issues that occur for Chrome and Firefox don't occur.

**Video demonstration with all 3 browsers:**
https://www.dropbox.com/s/p05ocydohceudft/Issue%20with%20opening%20files.mp4?dl=0

The json file that I used are attached as zip file.
[ECAMV2 Example.zip](https://github.com/icra/ecam/files/3885925/ECAMV2.Example.zip)

**More information regarding which json files cause this problem.** This issue is not limited to old json files. Even when creating new json files, this issue occurs. Strangely, it seems that soemtimes the issue does not occur if you save only few data, but then when making additional changes and save the file, it does not oppen anymore. However there does not seem to be a clear number of inputs, or a specific input that causes the problem. Sometimes I was able to fill out the whole Tier A, sometimes not.

**Comment by Ranf16** [comment]
Note: This issues seem to be new and were probably caused by the latest updates to ECAM

**Comment by Ranf16** [comment]
Another addition to **Edge:** even though older files open in Edge, the graphs in Tier A don't, and it displays only "loading" see screenshot: 

![grafik](https://user-images.githubusercontent.com/33861734/69816956-c94cbd80-11f9-11ea-9f57-12e851a236fe.png)

The graphs only start to appear if you make any changes to the inputs, or if you change the display language of the tool.

**Comment by holalluis** [comment]
thanks ranjin. v3 will aim to support all browsers. We will need a function that checks that the loaded file is compatible, since now it just accepts everything loaded, and files may be outdated, corrupted, not compatible, etc.

**Comment by holalluis** [comment]
I close this issue, since the loading files function is being recoded from scratch in v3, and will use another backend aproach.
