### ISSUE TITLE
When leaving Tier A page, the drop down selections for wastewater are lost

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#242]
When using Google Chrome, the drop down selections for wastewater in Tier A are lost when leaving the Tier A page. This affects also the results. 

**See video presentation of the issue:**
https://www.dropbox.com/s/gqh5u2sn2l4jtgu/ECAM-Bug_lost_drop_down_menus.mp4?dl=0
The file used in the video can be downloaded here: [TaskI-Group1.zip](https://github.com/icra/ecam/files/3927019/TaskI-Group1.zip)

**Note:** that this issue does not seem to appear on all computers. I was not able to replicate this error.

**Comment by holalluis** [comment]
maybe the problem was due to not resetting the cache? I've tried with Chrome (in Linux) and it works fine.

**Comment by holalluis** [comment]
I close this issue, since Tier A has been recoded from scratch in v3, and this does not happen anymore
