### ISSUE TITLE
Update descriptions for FSM variables

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#245]
Some variables of the FSM system should be further clarified by updating the descriptions, the wording of a large number of variable descriptions should be complemented by “during the assessment period” at the end. The following screenshots and tables show what variables need to be updated and what the updated description should be. 

**Important note:** The updated descriptions would need to be also updated in the different languages and should be translated for this purpose.

**1. Population page** 

![grafik](https://user-images.githubusercontent.com/33861734/70245359-391cf400-1776-11ea-8827-7ab05f345477.png)

Display   name | Current Description | Updated Description
-- | -- | --
Resident   population | Resident   population (FSM) | Number of   permanent residents within the assessment area for faecal sludge management.
Population   with onsite treatment | Population   with onsite treatment | Serviced   population refers to the number of inhabitants within the assessment area for   faecal sludge management that has access to some sort of sanitation facility.   If the emissions from open defecation shall be considered, the population practicing   it need to be included as well.

**2. Tier A**
![grafik](https://user-images.githubusercontent.com/33861734/70245409-4a660080-1776-11ea-8ae2-bac8b59523c3.png)

Display   Name | Current Description | Updated Description
-- | -- | --
Volume of   fuel consumed (transport) | Volume of   fuel consumed (transport) | Volume of fuel consumed during the assessment period for   example for transport or generators.       Note: this same update of Description should be also   done for fuel inputs in water. supply and wastewater system. In Tier A they   are only shown if on the configuration page the option is activated.
Energy   consumed from the grid in FSM stages | Energy   consumed from the grid in FSM stages | Energy   consumed from the grid during the assessment period related to faecal sludge   management.
Containments emptied | Fraction   of produced faecal sludge that is emptied from containments during the   assessment period. If only partial emptying is done it should be reflected in   the fraction. | Fraction   of produced faecal sludge that is emptied from containments during the   assessment period. If only partial emptying is done it should be reflected in   the fraction. Open defecation should be considered with a value of zero.

**3. Tier B**

Variable | Current Description | Updated Description
-- | -- | --
fsc_fslu_emp | Volume of   faecal sludge emptied from the containment | Volume of   faecal sludge emptied from the containment during the assessment period
fsc_bod_conc_fs | BOD   concentration of FS | Average   BOD concentration of faecal sludge during the assessment period after   emptying from containment or after open defecation.
fsc_cont_emp | Fraction   of produced faecal sludge that is emptied from containments during the   assessment period. If only partial emptying is done it should be reflected in   the fraction. | Fraction   of produced faecal sludge that is emptied from containments during the   assessment period. If only partial emptying is done it should be reflected in   the fraction. Open defecation should be considered with a value of zero.
fsc_bod_infl | BOD load   entering the containment before any treatment. It can be estimated from the   population. | BOD load during   the assessment period that enters that is produced before any further   treatment. It can be estimated from the serviced population.
fst_nrg_cons | Energy consumed from the grid | Energy consumed from the grid during the assessment period
sc_nrg_cons | Energy consumed from the grid | Energy consumed from the grid during the assessment period
fsr_nrg_cons | Energy consumed from the grid | Energy consumed from the grid during the assessment period
fsc_vol_trck | Volume of fuel consumed (trucks) | Volume of fuel consumed during the assessment period for   example for transport or generators.       Note: this same   update of Description   should be also done for fuel inputs in water supply and wastewater system
fsr_n2o_effl | Total Nitrogen load in the effluent | Total Nitrogen load in the effluent during the assessment   period
fsr_vol_disc | Volume of discharged effluent to water body | Volume of discharged effluent to water body during the   assessment period
fsr_bod_effl | Effluent BOD load | Effluent BOD load during the assessment period
fsr_mass_landfil | Dry weight sent to landfill | Dry weight sent to landfill during the assessment period
fsr_vol_dumping | Volume dumped | Volume dumped over the assessment period
fsr_reused_N | Total Nitrogen in urine applied to land | Total Nitrogen in urine applied to land over the   assessment period
fsr_reused_P | Total Phosphorus   reused that displaces synthetic fertilizer | Total Phosphorus   reused that displaces synthetic fertilizer assessment period

**Comment by ElaChe00** [comment]
Hey Lluis, I will re-check the definitions with colleagues who focus on FSM and then get back to you with translations. Best, Elaine

**Comment by holalluis** [comment]
updated
