### ISSUE TITLE
Detailed GHG sources of "Wastewater Treatment" misleading?

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#247]
**Dear Lluis, the "Detailed GHG Sources" of the Wastewater Treatment stage in the "GHG Summary" are a little bit misleading.**

- _"Treatment Process"_ includes (N2O + CH4) - Screenshot 1

- For people who don't know that the _Treatment process_ includes N2O and CH4, the results can be misleading, they might think that all of the detailed sources are summarized and shown in the summary whereas only "Treatment Process" is taken into account - Screenhot 2

- "Detailed GHG Sources" show "_Treatment Process"_, "_N2O from Treatment Process_" AND "_CH4 from Treatment Process_", - Screenshot 3

- It would be enough to have _"N2O from Treatment process"_ and _"CH4 from Treatment Process"_, instead of showing all of them?

- Additionally, it is difficult to read the "Detailed GHG Sources" with the pop-up indicating the "H**ighest GHG Emission"** - Screenshot 4

Let me know what you think?

Best,
Elaine

![1  Treatment process including N2o and CH4](https://user-images.githubusercontent.com/45791540/78001930-b3c9da80-7336-11ea-8781-130a9fb8b517.png)
![2  Detailed GHG sources listing Treatment process + N2O](https://user-images.githubusercontent.com/45791540/78001934-b4fb0780-7336-11ea-89af-5eacac407ca2.png)
![3  Detailed GHG sources listing Treatment process + N2O + CH4](https://user-images.githubusercontent.com/45791540/78001947-bb897f00-7336-11ea-846d-e016b7ca7f86.png)
![4  Detailed GHG sources difficult to read with pop-up](https://user-images.githubusercontent.com/45791540/78001948-bc221580-7336-11ea-91d1-f050ca66078d.png)

**Comment by holalluis** [comment]
Dear Elaine, thank you for your comment and screenshots. I'll fix those things during development of v3

**Comment by holalluis** [comment]
closing this since this page design changed in v3
