### ISSUE TITLE
Change contact from info@wacclim.org to wacclim@giz.de

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#249]
Dear Lluis, could you please change the contact address on the landing page from info@wacclim.org to **wacclim@giz.de** ? 

GIZ doesn't allow to have the other address (which is hosted on zoho). It would be great if this could be implemented for ECAM 2.2 already, since we are receiving emails regarding ECAM support.

Thanks, Elaine
![Change_Contact](https://user-images.githubusercontent.com/45791540/80198325-32592580-8620-11ea-9b9d-a5266e1ccab4.png)

**Comment by holalluis** [comment]
done! please verify the changes and close the issue. thank you

**Comment by ElaChe00** [comment]
Dear Lluis, thanks for the change. Landing page looks good.
