### ISSUE TITLE
Links to creative commons web from ecam not working

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#250]
![Captura de pantalla 2020-04-24 a las 18 46 37](https://user-images.githubusercontent.com/1082644/80236882-15424800-865c-11ea-8f9c-caa04081f5f0.png)

![Captura de pantalla 2020-04-24 a las 18 48 08](https://user-images.githubusercontent.com/1082644/80236932-27bc8180-865c-11ea-83a8-614ab9e8db42.png)

**Comment by ElaChe00** [comment]
Dear Lluis, the links "www.wacclim.org" and "wacclim@giz.de" shouldn't lead to Creative Commons, but the WaCCliM Website and the email field. Please replace the links with the "normal links". 

Unfortunately, I don't know who gave you the links in the first place, but I think they can be fixed.

Thanks! Elaine

**Comment by holalluis** [comment]
solved in v3
