### ISSUE TITLE
Feedback button

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#253]
(For ECAM 3.0) Dear Lluis, would it be feasible to include a feedback button on the ECAM page? I have been receiving more and more ECAM requests and it would be interesting for us to get some feedback. It could be a small tab at the Bottom?

Something like this:
![Feedback tab](https://user-images.githubusercontent.com/45791540/80358674-143c3100-887d-11ea-9c15-5be952b761cb.png)

When you click on it, the following opens:
![Feedback tab1](https://user-images.githubusercontent.com/45791540/80359143-b65c1900-887d-11ea-8b5f-b5df18d31ffb.png), showing "Feedback", "Support" and "Report Issues".

"Feedback":
![Feedback tab2](https://user-images.githubusercontent.com/45791540/80359768-97aa5200-887e-11ea-832e-925776f86be7.png). A simple rating would already help us to estimate what people think about ECAM.

"Support" opens a chat bot, but this could also include an improved FAQ.

"Report Issues" enables you to take a screenshot and share this with us, with the option to get back to the preson who shared the issue.
![Feedback tab3](https://user-images.githubusercontent.com/45791540/80359844-b7da1100-887e-11ea-8c53-f13460ba53ec.png)

I don't know how feasible this would be for ECAM, but I believe that this function would be very valuable.

**Comment by holalluis** [comment]
Hi Elaine, this feature can't be implemented since ecam is designed as a "serverless" tool, meaning we don't have a system to store and process feedback from users. Since this is an open source tool, users should be encouraged to open issues here in github

**Comment by ElaChe00** [comment]
Isn't it possible to use this interface but sence this feedback automatically to wacclim@giz.de 

not everyone is familiar with github and not everyone has or wants an account on github. I want to ensure that people give feedback anyway. So would there we a possibility to integrate this and send the results automatically via email to us?

**Comment by holalluis** [comment]
maybe we can adapt this piece of text and rename it to something like "do you have questions or feedback?"
![image](https://user-images.githubusercontent.com/1082644/108415102-5cbe4400-722d-11eb-8842-a4220809f1e0.png)

**Comment by ElaChe00** [comment]
Yes! This is good! Please adapt.

"Do you have questions or feedback?"
