### ISSUE TITLE
Configuration - Adapt colour

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#255]
Hi Lluis, could you please adapt the colours of 'water supply' and 'wastewater'? Faecal Sludge Managament is already in the same colour as the buttons.

Blue colour code is: #58C1DB
Red colour code is: #ED6D57

![Configuration_AdaptColours](https://user-images.githubusercontent.com/45791540/89039247-fed61780-d341-11ea-94cd-ae7f0f126749.png)

Thanks
Elaine

**Comment by holalluis** [comment]
done
