### ISSUE TITLE
Change main icons of the stages

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#256]
Hi Lluis, currently we have this cloud as a "main" icon for the stages. See picture below:
![image](https://user-images.githubusercontent.com/45791540/89040577-49f12a00-d344-11ea-9ce7-f0267e6e947f.png)

The colour of the "cloud icons" are the same as the colours that VITI has chosen. I have edited the new "main icons" according to the colour of the stage icons and changed the symbol from a cloud to a water drop. 
![ECAM Stage Icons (1)](https://user-images.githubusercontent.com/45791540/89040638-5d9c9080-d344-11ea-8d99-5901548182b0.png)
![ECAM Stage Icons (2)](https://user-images.githubusercontent.com/45791540/89040646-5ffeea80-d344-11ea-84e0-74912f2397cf.png)
![ECAM Stage Icons (3)](https://user-images.githubusercontent.com/45791540/89040649-61301780-d344-11ea-80f7-6e2c61405f23.png)

Could you please replace them? Thanks

Please find attached the new icons.

**Comment by holalluis** [comment]
done 
![image](https://user-images.githubusercontent.com/1082644/91733987-9da49c80-ebaa-11ea-9fac-b06157345083.png)
