### ISSUE TITLE
Footer of landing page/ Home (Text + Logos)

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#257]
Hi Lluis, could you please replace the currenttext in this footer with the text below?
![LandingPage_Footer](https://user-images.githubusercontent.com/45791540/89041186-3e523300-d345-11ea-9bfe-58398d790836.png)
________________________________________
ECAM is a tool developed by ICRA for the WaCCliM Project* and holds a Creative Commons Attribution-ShareAlike 4.0 International License.

*WaCCliM is a joint initiative between GIZ and IWA. This project is part of the International Climate Initiative (IKI). The German Federal Ministry for the Environment, Nature Conservation and Nuclear Safety (BMU) supports this initiative on the basis of a decision adopted by the German Bundestag.
__________________________________________

Could you also make sure, that the logo all have a similar size? IWA is way bigger than every other logo- it shouldn't be bigger than the BMU, who's funding this project. Also the ICRA logo could be resized a tiny bit.

Thanks!

**Comment by holalluis** [comment]
is this ok? 
![image](https://user-images.githubusercontent.com/1082644/91733654-21aa5480-ebaa-11ea-9343-67d050809eea.png)

**Comment by ElaChe00** [comment]
Looks way better. Maybe reduce the size of the BMU logo a tiny bit?

**Comment by ElaChe00** [comment]
Looks way better. Maybe reduce the size of the BMU logo a tiny bit?

**Comment by ElaChe00** [comment]
Looks way better. Maybe reduce the size of the BMU logo a tiny bit?

**Comment by ElaChe00** [comment]
Looks way better. Maybe reduce the size of the BMU logo a tiny bit?

**Comment by ElaChe00** [comment]
Looks way better. Maybe reduce the size of the BMU logo a tiny bit?

**Comment by ElaChe00** [comment]
Looks way better. Maybe reduce the size of the BMU logo a tiny bit?

**Comment by holalluis** [comment]
now?
![image](https://user-images.githubusercontent.com/1082644/91742764-101b7980-ebb7-11ea-9e40-1e2e9f189f3f.png)

**Comment by ElaChe00** [comment]
Hey Lluis, looks good, but for some reason, the logos are not located in the middle. They are more to the left. 

![image](https://user-images.githubusercontent.com/45791540/91827762-8fed2680-ec3f-11ea-8211-80c4ca5952d8.png)

**Comment by holalluis** [comment]
yes, now they are correctly centered. thank you
