### ISSUE TITLE
Adapt colours of the tables in the stages according to the colour of the icons (WS, WW, FSM)

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#258]
Hi Lluis, could you please adapt the colours of the tables within the stages according zo zhe colour of the icons of Water Supply, Wastwater and Faecal Sludge Managament? Currently, all of them are blue (see screenshots)

![ColourofTables in WS](https://user-images.githubusercontent.com/45791540/89042993-2203c580-d348-11ea-9ee2-2df175c05d09.png)

![ColourofTables in WW](https://user-images.githubusercontent.com/45791540/89043059-38118600-d348-11ea-8eb9-fd124c2168e4.png)

This seems to be minor. But I believe that it is more user fiendly, if the colours are repetitiv.
I envisision somethin like the following:

![ColourofTables in WW_new](https://user-images.githubusercontent.com/45791540/89042887-f7197180-d347-11ea-8a1c-9a812402c8a5.png)

![ColourofTables in FSM new](https://user-images.githubusercontent.com/45791540/89042902-ff71ac80-d347-11ea-8e90-16ad6b3b7d2f.png)

WW Colour Codes: #ED6D58 and #F4AEA8
FSM Colour Codes: #94C122 and #D2E19D

Thanks

**Comment by holalluis** [comment]
done
![image](https://user-images.githubusercontent.com/1082644/91737228-186fb680-ebaf-11ea-9004-29f4b5f870c2.png)
![image](https://user-images.githubusercontent.com/1082644/91737265-24f40f00-ebaf-11ea-8cd5-f2bba97d1323.png)
