### ISSUE TITLE
Serviced Population in Water Supply

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#259]
Hi Lluis, could you please include "Serviced Population" in WS under the stage "Distribution?" Thanks
![image](https://user-images.githubusercontent.com/45791540/89165837-6aee9080-d579-11ea-9d34-9357cd345b9c.png)

![image](https://user-images.githubusercontent.com/45791540/89165864-76da5280-d579-11ea-89e6-6878e555b440.png)

**Comment by holalluis** [comment]
done, frontend reconnected and backend adapted for all formulas related
![image](https://user-images.githubusercontent.com/1082644/91742629-d6e30980-ebb6-11ea-82e8-3bdc94fd8363.png)
