### ISSUE TITLE
Wastewater Treatment Stage

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#261]
Hi Lluis,

The efficiency of BOD Removal of wastewater treatment should be adjustable to the real conditions (e.g. in ECAM v2.2 it is fixed 90% (see calculation of effluent BOD load: wwt_bod_effl = 0.10 * wwt_bod_infl) but treatment plants have different treatment efficiencies, so that the effluent BOD load has to be calculated manually) - the same counts for the calculation of the faecal sludge treatment effluent BOD load.

![image](https://user-images.githubusercontent.com/45791540/89168529-485e7680-d57d-11ea-8629-f12a0659d6e1.png)

• Suggestion to add a variable for % efficiency of WWTP for calculating the estimation of BOD effluent and should also be taken into account for the estimations of BOD removed as sludge (the same procedure for FS treatment).

• This could then also automatically recalculate the volume of treated ww (out of the ww conveyed to TP) and should be reflected in the information box of treated ww.

**Comment by holalluis** [comment]
for now, as temporary solution, I've just deleted the estimation, so the user will enter the effluent BOD manually. I think that adding a new input for % efficiency just adds an extra step that is not necessary. Let's see when the reordering of inputs and outputs for v3 is finished if there's a way of estimating it.
