### ISSUE TITLE
Configuration: Being able to select and deselect all stages

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#262]
Hi Lluis, we have discussed this briefly during our call. It would be great to be able to deselect AND select all stages when pressing on the buttons "Water Supply", Wastewater" and "Faecal Sludge Management":

![image](https://user-images.githubusercontent.com/45791540/89275559-b7ea6980-d642-11ea-9cdd-2ff839ad17a6.png)

Currently, you can only select all the stages at once.

**Comment by holalluis** [comment]
Hi Elaine, the way it works now it is already how it is expected, for example you can activate just water supply level but without abstraction, treatment or distribution stages.
![image](https://user-images.githubusercontent.com/1082644/91732268-4ac9e580-eba8-11ea-9d1f-54f16d3f75c2.png)
