### ISSUE TITLE
Amount of CO2,eq emissions due to N2O emission from land application of urine

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#263]
the number marked has no description/related unit
![image](https://user-images.githubusercontent.com/1082644/95111453-ce469b80-073f-11eb-8381-163981163544.png)

**Comment by ElaChe00** [comment]
Dear Lluis, I couldn't find the above mentioned equation in ECAM.  I don't find anything with "wwo_KPI_GHG_urine". But I found "fsr_wwo_KPI_GHG_urine" 🐰 

![image](https://user-images.githubusercontent.com/45791540/100872210-bd957600-34a1-11eb-8385-b42f0f9d0b32.png)

I would assume that 0.01 is correction or emission factor, see page 11 (Chapter 11 IPCC 2006)

![image](https://user-images.githubusercontent.com/45791540/100878330-54fec700-34aa-11eb-8732-1a0114709d63.png)

What do you think?

**Comment by holalluis** [comment]
ok, I've added it like this:
![image](https://user-images.githubusercontent.com/1082644/104572211-09683d00-5654-11eb-9275-a2239fa8cac8.png)
