### ISSUE TITLE
Amount of CO2,eq emissions due to N2O emission from sludge stockpiling

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#264]
marked number not documented / not related unit
![image](https://user-images.githubusercontent.com/1082644/95112255-01d5f580-0741-11eb-8e7b-42665e22d5f1.png)

**Comment by ElaChe00** [comment]
Dear Lluis, this information is given in the [ECAM 2.2 Methodology Guide](https://wacclim.org/library/ecam-methodology-guide/). Page 50, see below.

![image](https://user-images.githubusercontent.com/45791540/100871300-57f4ba00-34a0-11eb-9344-fa04e9a15d98.png)

Source of this number is therefore: 

Majumder, R., Livesley, S., Gregory, D., & Arndt, S. (2014, 05 15). Biosolids stockpiles are a significant point source for greenhouse gas emissions. Journal of Environmental Management, 143, pp. 34-43. doi:http://dx.doi.org/10.1016/j.jjenvman.2014.04.2016

**Comment by holalluis** [comment]
thanks, I've created a data structure to hold centralized the documentation. This is the first entry, looks like these in the user interface:
![image](https://user-images.githubusercontent.com/1082644/104570647-809cd180-5652-11eb-89ee-74ecfd35f2b0.png)

and the code is simply:

![image](https://user-images.githubusercontent.com/1082644/104570814-ac1fbc00-5652-11eb-8a9e-4370e2db5290.png)
