### ISSUE TITLE
On-Site Sanitation Icon (size is correct, but icon is not transparent)- please use VITI's .svg version

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#265]
Dear Lluis, thanks for adjusting the size of the icon. I have noticed that the icon is 1) transparent and 2) of low quality. Below you can see, that OSS's icons background is not white, but transparent.
![image](https://user-images.githubusercontent.com/45791540/100869829-e9166180-349d-11eb-8ae8-ef7b49670df4.png)

Please replace the current icon with the on-site icon provided by VITI

Thanks a lot!

**Comment by ElaChe00** [comment]
[OnSite Sanitation Logos.zip](https://github.com/icra/ecam/files/5802491/OnSite.Sanitation.Logos.zip)

**Comment by holalluis** [comment]
thanks for the icons, done
