### ISSUE TITLE
Remove population from"more"

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#267]
Dear Lluis,

"Population" is not used under "more", correct? Could you please delete this part, thanks!

![image](https://user-images.githubusercontent.com/45791540/101465489-4c8e0c80-3940-11eb-8788-e0663dbfa0bc.png)

![image](https://user-images.githubusercontent.com/45791540/101465513-5283ed80-3940-11eb-9984-bd18ae88faad.png)

**Comment by holalluis** [comment]
ok, done
