### ISSUE TITLE
Fuel type soure

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#268]
Dear Lluis, please find below the links and source of the fuel type table:
![image](https://user-images.githubusercontent.com/45791540/101476050-6f72ed80-394d-11eb-9e4e-af9dd73e1372.png)

![image](https://user-images.githubusercontent.com/45791540/101515817-102dd100-397f-11eb-9cdb-c7135143e486.png)

Document: 2006 IPCC Guidelines for National Greenhouse Gas Inventories, 
![image](https://user-images.githubusercontent.com/45791540/101477196-30de3280-394f-11eb-902b-1ee2d3a5bc11.png)

**Introduction** Link: https://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/2_Volume2/V2_1_Ch1_Introduction.pdf

**Chapter 2** Link: https://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/2_Volume2/V2_2_Ch2_Stationary_Combustion.pdf

**Chapter 3:** 
https://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/2_Volume2/V2_3_Ch3_Mobile_Combustion.pdf

**GHG Protocol:**
https://ghgprotocol.org/sites/default/files/Emission_Factors_from_Cross_Sector_Tools_March_2017.xlsx

Below an example of where the numbers came from (presumably):

**Diesel**: 3 _(Chapt. 2, p.52, table 2)_| 3.9 _(Chapt. 3, p. 3.21, table. 3.3.2)_ | 0.6 _(Chapt. 2, p.52, table 3)_| 3.9 _(Chapt. 3, p. 3.21, table 3.3.2)_ | 74100 (Chapt. 1 p.1.23, Table 1.4)  | 0.84 _(GHG Protocol)_ | 43 _(p.1.18, table 1.2)_

**Comment by holalluis** [comment]
added
