### ISSUE TITLE
Landing Page | Introduction text should be in the middle of the field

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#269]
Hi Lluis, I hope you are doing well! 

Since the "Urban Water Cycle" graphic is always changing its size (depening on the size of the window), it would be good to have the introduction text centered in the middle **OR** keep a static size of the UWC graphic

Currently it looks off: 
![image](https://user-images.githubusercontent.com/45791540/103877619-9ef45180-50d5-11eb-87bd-fb1a68af8739.png)

![image](https://user-images.githubusercontent.com/45791540/103877711-baf7f300-50d5-11eb-828e-47b055377a65.png)

Another possibility would be to make the two headlines centered, like this:

![image](https://user-images.githubusercontent.com/45791540/103878317-8d5f7980-50d6-11eb-8612-bcd988c715a4.png)

**Comment by holalluis** [comment]
solved
