### ISSUE TITLE
"Wastewater" should be renamed to "Sanitation"

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#273]
Hey Lluis,

we had a discussion on the terminology a while back and we agreed on renaming "wastewater" to "sanitation". This way onsite sanitation does not get lost.

![image](https://user-images.githubusercontent.com/45791540/103880012-db757c80-50d8-11eb-8180-af07e12b78f6.png)

Could you please add this to the current tool? Thanks!

**Comment by holalluis** [comment]
ok, done
