### ISSUE TITLE
Report function

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#274]
Hey Lluis,

I know the report function is not done yet, but I figured that the preview is actually quite neat. Maybe we can keep the page 50/50. One half the the web report and the other half showing how the report would look like?

![image](https://user-images.githubusercontent.com/45791540/103880259-2becda00-50d9-11eb-8070-906245a2962d.png)

I am aware that the current preview is a placeholder :D

**Comment by holalluis** [comment]
they way it works now (as a first approach) is that when you click the report, gets full screen. if you click it again, it goes back to original view. Let me know if you find this confusing or it is ok @ElaChe00

**Comment by ElaChe00** [comment]
Hey @holalluis , I think it's a great start. I didn't get it right away, but it seems easy to me. However, we might want to include a little be more instruction. Maybe;

"Click on the report to your left to activate / deactivate printable mode and press CTRL+P"

Maybe for now (:

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/104607916-9c6b9c00-5681-11eb-8674-aa5f2273bf05.png)
done

**Comment by holalluis** [comment]
solved
