### ISSUE TITLE
Results | For now, remove flow diagram

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#275]
Hey Lluis,

for now it would be better to **remove the flow diagram from the results.** We haven't decided on the design and place yet. I think it might be confusing to leave it there. Let's remove it for now and add a better version later?

![image](https://user-images.githubusercontent.com/45791540/103880451-69e9fe00-50d9-11eb-8026-5479972582dd.png)

**Comment by holalluis** [comment]
ok, I moved it to "more"
