### ISSUE TITLE
Remove GWP values from "Get started"/"Configuration"

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#277]
Hey Lluis, I feel that these values (see screenshots) are confusing. Just remove them from there. If people want to know more, they can click on "more info".

![image](https://user-images.githubusercontent.com/45791540/104586795-40dfe500-5666-11eb-896f-75dc41e7c2f8.png)

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/104595994-a5ee0780-5673-11eb-9700-f480eba96cac.png)
done
