### ISSUE TITLE
Total Volatile Solids | ECAM 2.2 vs. ECAM 3.0

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#278]
Hey Lluis, I think there is a mistake under "Treatment". See below. 
In ECAM 2.2 it is 70% , in ECAM 3.0 it says 0.7%

![image](https://user-images.githubusercontent.com/45791540/104588903-5dc9e780-5669-11eb-8873-bd4139c8104a.png)

![image](https://user-images.githubusercontent.com/45791540/104588952-7508d500-5669-11eb-9697-9215f067eb04.png)

Typo?

**Comment by holalluis** [comment]
thanks for noticing, I forgot a 100 in the estimation formula, when changing the structure of tables in v3 for this particular input, now I've added it.
![image](https://user-images.githubusercontent.com/1082644/104595416-e1d49d00-5672-11eb-8d9d-9da33bb15b04.png)
