### ISSUE TITLE
Remove colour of "Avoided Emissions"

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#279]
Dear Lluis, the bright green is pulling too much attention away from the actual results. Could you remove the colour please? It could be the same colour as the background or simply grey.

![image](https://user-images.githubusercontent.com/45791540/104589730-98804f80-566a-11eb-8a1e-71de93681ed3.png)

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/104595761-5576aa00-5673-11eb-9d00-76fc588b0cec.png)
like this?

**Comment by ElaChe00** [comment]
Yes! I think this is great. Can the rectangle that is currently blue and shows the numbers also be black/grey (same colour as the border or "more info" ?

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/104607731-68907680-5681-11eb-978a-f9532ff9792c.png)
done
