### ISSUE TITLE
Discussion on title of "Get Started" - issue of saving files

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#280]
Dear Lluis, is is only possible to save the file under "Get Started?", if so - I would rename it again to "Configuration". But we can discuss this together.

**Comment by holalluis** [comment]
I can put a new button to save elsewhere, just let me know where you think it could fit

**Comment by ElaChe00** [comment]
I had discussions with other collegues and projects and we favour "Configuration" over "Getting started". Please adapt accordingly.

It has several reasons. One is that this page is not only relevant to get started. You always have to go back to it if you want to see the results of another assessment.

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/107795220-aeac2900-6d58-11eb-9f09-6a994bf8cc27.png)

ok done

**Comment by ElaChe00** [comment]
![image](https://user-images.githubusercontent.com/45791540/107795305-c5eb1680-6d58-11eb-8727-22cd00af9d24.png)

Could you please add another "Save File" button to the inventory

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/107797359-28ddad00-6d5b-11eb-8973-9ee2c1b58807.png)
done
