### ISSUE TITLE
Decimal places in results / Reports

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#281]
Hey @holalluis , I've noticed that it is difficult to read the numbers in the diagrams sometimes. Is there  a way to prevent this?

![image](https://user-images.githubusercontent.com/45791540/104603502-c8385300-567c-11eb-96e8-0938f1698e53.png)

Further, we should be consequent with the number of decimal places. I believe that one place after the comma is enough.

**Comment by holalluis** [comment]
a solution for this is increasing the size of the circles

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/104607357-0a639380-5681-11eb-90c5-c52132e4a46a.png)
i've increased the size of the circle to 200, displayed only 1 decimal, and only display the text if the "slice" is greater than 5%

**Comment by holalluis** [comment]
solved
