### ISSUE TITLE
Decimal places in report diagrams

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#282]
Hey @holalluis , I've noticed that it is difficult to read the numbers in the diagrams sometimes. Is there  a way to prevent this?

![image](https://user-images.githubusercontent.com/45791540/104603502-c8385300-567c-11eb-96e8-0938f1698e53.png)

Further, we should be consequent with the number of decimal places. I believe that one place after the comma is enough.

**Comment by holalluis** [comment]
duplicate https://github.com/icra/ecam/issues/281
