### ISSUE TITLE
Add Iraq to countries

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#283]
Hi Lluis, since I was working with consultants from Iraq, I've noticed that the country was missing.

Could you please add the emissions grid factor: 0.820614626 kgCO2/kWh  Source: https://ecometrica.com/assets/Electricity-specific-emission-factors-for-grid-electricity.pdf 

and the protein value: 22.10 kg/pers/year (Source FAO: https://ourworldindata.org/country/iraq) .

BOD5 Generation: 40 g/person/day

**Comment by holalluis** [comment]
done
