### ISSUE TITLE
Report | Align graphics in report + add graphic of serviced population + only include inputs that are given

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#285]
Hi Lluis, ECAM 3.0 has come a long way! So many positive developments!
Is it possible to aligne all the graphics? Currently they are not in line. See screenshot:
![image](https://user-images.githubusercontent.com/45791540/105021874-5b8cd200-5a49-11eb-9833-067c06c04aaa.png)

Is it also possible to include the graphic of serviced population?
![image](https://user-images.githubusercontent.com/45791540/105021991-7e1eeb00-5a49-11eb-8b26-97191dc28495.png)

I was also wondering, if it is possible to ONLY include the data in the report, where a substage has been created for? Sometimes utilities only  assess stage "Distribution" and and "Treatment"/"Discharge". When they click on the report, however, the would have several pages filled with zeros or nothing (see screenshot):

![image](https://user-images.githubusercontent.com/45791540/105022349-f38abb80-5a49-11eb-9600-459ae2b863a0.png)

**Comment by holalluis** [comment]
solved
