### ISSUE TITLE
Bar Diagramm not displayed correctly

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#286]
Hey @holalluis ,

I have noticed that the bar diagramm is not displayed correctly. The numbers cannot be read (See screenshot). It's the same effect for GHG and energy.

![image](https://user-images.githubusercontent.com/45791540/105022621-419fbf00-5a4a-11eb-988b-83378656cd94.png)

![image](https://user-images.githubusercontent.com/45791540/105022659-4cf2ea80-5a4a-11eb-8276-dfa5536a5f96.png)

**Comment by holalluis** [comment]
solved, when number is greater than 9999 (4 digits) it gets converted to scientific notation (with exponent)
![image](https://user-images.githubusercontent.com/1082644/105189550-5d33c400-5b35-11eb-9add-750f0abe921f.png)
