### ISSUE TITLE
Compare Assessments | Not working

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#288]
Hey @holalluis 

I have used the "replace" button to insert my information (that I have saved before)
![image](https://user-images.githubusercontent.com/45791540/105024117-02726d80-5a4c-11eb-8aa5-92410a3d1b6c.png)

When I click on assessments, id doens't compare the information that I have uploaded, but it does compare the ones ..that have been created BEFORE I have uploaded my files:

![image](https://user-images.githubusercontent.com/45791540/105024050-ef5f9d80-5a4b-11eb-80c5-a61ffcd2ca62.png)

**Comment by holalluis** [comment]
hi elaine, sorry the comparison function is still not finished, today I'll be working on it

**Comment by ElaChe00** [comment]
Hey @holalluis , thanks for the information. While you are on it. it would be great if Inputs AND Outputs could be compared with each other. Maybe it is possible to make a button for both and then users can switch. 

I, myself, am only interested in the outputs and the graphs of GHG emissions and energy consumption. However, comparing inputs is also very handy.

**Comment by holalluis** [comment]
done
