### ISSUE TITLE
Inventory | Make stages to buttons

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#289]
Hey @holalluis , could you replace the following with the buttons I have created and also give them the same function as "create substage"? This goal is to reflect the colours and symbols of the results page:
![image](https://user-images.githubusercontent.com/45791540/105031096-166e9d00-5a55-11eb-95f5-afbf59774aa4.png)

I was thinking of something like this:
![image](https://user-images.githubusercontent.com/45791540/105030814-a6601700-5a54-11eb-8909-d05cf8658c28.png)

For this, the spacing of ALL stages should be the same. Currently, they are not:
![image](https://user-images.githubusercontent.com/45791540/105030997-ef17d000-5a54-11eb-8a11-0480756fa890.png)

**Comment by holalluis** [comment]
solved
