### ISSUE TITLE
Frontpage formatting

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#290]
Hey @holalluis, I am currently a little bit slow with commenting since my laptop is being repared. Anyhow. Thanks for all the changes! It's looking great.

I am having some trouble with the l**anding page**. The logos are unproportionally huge?

Top: 
![image](https://user-images.githubusercontent.com/45791540/105749496-c5264800-5f43-11eb-8f35-7a014c9b6274.png)

Bottom:
![image](https://user-images.githubusercontent.com/45791540/105749534-d1120a00-5f43-11eb-9472-5133fa91fc86.png)

**Comment by holalluis** [comment]
Dear @ElaChe00, this is unexpected. Does it still appear as big when you reload the page?
Is the screenshot I attach the expected size?
![image](https://user-images.githubusercontent.com/1082644/105875293-eb102300-5ffd-11eb-9ae2-803b15856015.png)

**Comment by ElaChe00** [comment]
Yes, the screenshot show the logos how they should look like.
But in my browser ...it looks all unproportional. I have reloaded the page several times.

I am also not accessing the page from my computer, but another one that I have borrowed

Von: Lluís Bosch <notifications@github.com>
Gesendet: Dienstag, 26. Januar 2021 17:43
An: icra/ecam <ecam@noreply.github.com>
Cc: Cheung, Elaine GIZ <elaine.cheung@giz.de>; Mention <mention@noreply.github.com>
Betreff: Re: [icra/ecam] Frontpage formatting (#290)


Dear @ElaChe00<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FElaChe00&data=04%7C01%7Celaine.cheung%40giz.de%7Cca5ee749c645474d38b708d8c2197ae0%7C5bbab28cdef3460488225e707da8dba8%7C0%7C0%7C637472761977299004%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Nr8hMjG3X59MjC8uOzrVGqlrPhs7h%2BwNwDzhfuKkapc%3D&reserved=0>, this is unexpected. Does it still appear as big when you reload the page?
Is the screenshot I attach the expected size?
[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1082644%2F105875293-eb102300-5ffd-11eb-9ae2-803b15856015.png&data=04%7C01%7Celaine.cheung%40giz.de%7Cca5ee749c645474d38b708d8c2197ae0%7C5bbab28cdef3460488225e707da8dba8%7C0%7C0%7C637472761977309009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pCeNbghYwEb4gj9cw04Vpp%2BcVZCMrmfLBfDTup8JbvY%3D&reserved=0>

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ficra%2Fecam%2Fissues%2F290%23issuecomment-767671985&data=04%7C01%7Celaine.cheung%40giz.de%7Cca5ee749c645474d38b708d8c2197ae0%7C5bbab28cdef3460488225e707da8dba8%7C0%7C0%7C637472761977309009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Z9ORyneo06NGyA%2BfYsoRYL%2FplOiu3Ar0eGOkZsFxMP0%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAK5LSNGLJW75UVSW5S62TEDS33WKFANCNFSM4WSFQIEA&data=04%7C01%7Celaine.cheung%40giz.de%7Cca5ee749c645474d38b708d8c2197ae0%7C5bbab28cdef3460488225e707da8dba8%7C0%7C0%7C637472761977318996%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Q%2B46a1bS4PMwRO79Z%2B%2B8KWMd1%2Bo93B3QQDCCgGhCIFU%3D&reserved=0>.

________________________________
Deutsche Gesellschaft fuer Internationale Zusammenarbeit (GIZ) GmbH;
Sitz der Gesellschaft Bonn und Eschborn/Registered offices Bonn and Eschborn, Germany;
Registergericht/Registered at Amtsgericht Bonn, Germany; Eintragungs-Nr./Registration no. HRB 18384 und/and Amtsgericht Frankfurt am Main, Germany; Eintragungs-Nr./Registration no. HRB 12394;
USt-IdNr./VAT ID no. DE 113891176;
Vorsitzender des Aufsichtsrats/Chairman of the Supervisory Board: Martin Jaeger, Staatssekretaer/State Secretary;
Vorstand/Management Board: Tanja Goenner (Vorstandssprecherin/Chair of the Management Board), Ingrid-Gabriela Hoven, Thorsten Schaefer-Guembel

**Comment by holalluis** [comment]
I've set the size to 90% of the width of the page; before it was unset. Let me know if you still see it unproportional.

**Comment by holalluis** [comment]
I've manually set the size of logos, please check now

**Comment by ElaChe00** [comment]
It's better, but now the IWA and ICRA logo are bigger again:

![image](https://user-images.githubusercontent.com/45791540/106460093-17f78680-6493-11eb-8fa1-96fc1ee9c6f5.png)

It should be like this one here:
https://github.com/icra/ecam/issues/290#issuecomment-767671985
