### ISSUE TITLE
Results | Summary Page

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#291]
Hey @holalluis 

is it possible to integrate this from the VITI report (see screenshot):
![image](https://user-images.githubusercontent.com/45791540/105750335-ecc9e000-5f44-11eb-9f7a-a50f9adaf21d.png)

Currently, there is no indication of what we are looking at:
![image](https://user-images.githubusercontent.com/45791540/105750503-1e42ab80-5f45-11eb-8cdb-5bc833e65b3e.png)

**Comment by holalluis** [comment]
Hi, the problem I'm facing is that the web looks very "crowded" (I can't find the exact word in english) if I put "total ghg emissions" and "total energy consumption" in every row, I think i like this solution though, what do you think?

![image](https://user-images.githubusercontent.com/1082644/106295934-54d43b00-6251-11eb-8932-f998ccf43cd6.png)

**Comment by ElaChe00** [comment]
I actually love your solution! Could you also make it bold? That would be perfect. Currently, it's a little bit lost.

![image](https://user-images.githubusercontent.com/45791540/106460540-cb607b00-6493-11eb-9c35-c5775418329e.png)

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/107799847-44968280-6d5e-11eb-854d-d0bf83282843.png)
