### ISSUE TITLE
Results | Summary Table | Units

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#293]
Hey Lluis,

is it possible to adjust the results automatically? 
Say, if the results are higher than 1 million that it turns automatically into tons?

![image](https://user-images.githubusercontent.com/45791540/105753277-b68e5f80-5f48-11eb-9d69-915f6375e394.png)

Also, please don't show the numbers after the decimal point.

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/108212440-2b128380-712e-11eb-9b5c-ea207d6fd4df.png)

**Comment by ElaChe00** [comment]
@holalluis AMAZING! Looks great. Something minor. Can you make the "T" of tons to a lower case letter? "t"

![image](https://user-images.githubusercontent.com/45791540/108217441-df62d880-7133-11eb-9758-7753a7e220a0.png)

Thanks!

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/108218656-2dc4a700-7135-11eb-8367-fb3fc4079567.png)
ok done

**Comment by ElaChe00** [comment]
Perfect, thanks!
