### ISSUE TITLE
Further Assessment [No / Yes]

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#294]
Hey @holalluis , I have noticed that nothing is selected in the further assessment, see screenshot:
![image](https://user-images.githubusercontent.com/45791540/105847510-f9e6dd80-5fdd-11eb-84e0-69450bb9fbeb.png)

Only if you click on it, the no or yes is selected:
![image](https://user-images.githubusercontent.com/45791540/105847560-09662680-5fde-11eb-8937-05d034b45722.png)

I think it would be good to have everything on "no".

**Comment by holalluis** [comment]
done please check

**Comment by ElaChe00** [comment]
Yes, it is fixed. Thanks!
