### ISSUE TITLE
in compare assessments table : remove stages with no substages across all assessments

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#296]

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/106297201-bfd24180-6252-11eb-97c7-822098f71dcd.png)

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/108212213-e5ee5180-712d-11eb-9b8c-0a8dff58ee71.png)

**Comment by holalluis** [comment]
done please check

**Comment by ElaChe00** [comment]
Yes, I think this can be closed
