### ISSUE TITLE
idea for graphs and grouping

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#297]
![image](https://user-images.githubusercontent.com/1082644/106150950-220c4300-617c-11eb-8dcb-75ba28d00f46.png)
![image](https://user-images.githubusercontent.com/1082644/106150974-27698d80-617c-11eb-9f5a-834fa9867926.png)

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/106305190-ab934200-625c-11eb-8456-e29cc582f7de.png)

**Comment by ElaChe00** [comment]
Looks good. Is it possible to have the stages fully displayed?
![image](https://user-images.githubusercontent.com/45791540/108221824-7d58a200-7138-11eb-9d46-fd24741c90fe.png)

Abstraction, Treatment, Distribution, Collection, WW Treatment, On-Site Sanition?

**Comment by holalluis** [comment]
yes, I did put "ws" or "ww" at the begginig though, because otherwise the "ws Treatment" and "ww Treatment" had the same name and they got combined in the same "subdivision" of each column
![image](https://user-images.githubusercontent.com/1082644/108407180-aefa6780-7223-11eb-86cc-318e43f4ec84.png)

**Comment by ElaChe00** [comment]
Ok! Yes, I think this is better!
