### ISSUE TITLE
Compare Assessments | add similar table as the one from report 

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#298]
Please add a table that is similar to the one from the report to the "Compare Assessments".

![image](https://user-images.githubusercontent.com/45791540/106153359-c1323a00-617e-11eb-9c49-c7632e87aa8f.png)

It should go on top-

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/108422154-7912ae80-7236-11eb-81a1-e81c726ecd4a.png)
done please check

**Comment by ElaChe00** [comment]
Amazing!

If you could only remove the decimal places again? It makes the table less crowded. Thanks!
![image](https://user-images.githubusercontent.com/45791540/108478240-878fb300-7294-11eb-86f3-2c60260c8cc1.png)

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/108526539-892b9c00-72d1-11eb-9344-e94ce807f03a.png)
done, please check

**Comment by ElaChe00** [comment]
Good!
