### ISSUE TITLE
Numbers after decimal points to be removed (in "compare assessments")

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#299]
please remove the numbers after the decimal point. 

+

more than 1,000,000 kgCO2 should be converted to tons automatically

![image](https://user-images.githubusercontent.com/45791540/106153805-3b62be80-617f-11eb-9217-2d6007c0bc86.png)

**Comment by holalluis** [comment]
decimals removed, now I'll be focusing on automatic unit change
![image](https://user-images.githubusercontent.com/1082644/108104129-306ac200-708b-11eb-8b99-c43a5395043d.png)

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/108211957-a1fb4c80-712d-11eb-97ca-71dedd356781.png)

**Comment by ElaChe00** [comment]
Perfect!
