### ISSUE TITLE
Results | Summary | GHG Charts - Align pie chart

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#300]
Please align the pie chart in the results (see report as reference)

![image](https://user-images.githubusercontent.com/45791540/106154091-85e43b00-617f-11eb-88b2-557112d7f18c.png)

**Comment by holalluis** [comment]
done please check

**Comment by ElaChe00** [comment]
Not aligned yet (for me).
Further, now the box with explaination seems really big:

![image](https://user-images.githubusercontent.com/45791540/106290503-d6749a80-624a-11eb-9b6e-c41d6889f9f5.png)

**Comment by holalluis** [comment]
sorry i did not update the server, please check now

**Comment by ElaChe00** [comment]
It is aligne now. Could you also make sure, the stages are in 2 rows and not in 3 as indicated above? They take a lot of space.

**Comment by holalluis** [comment]
I've reduced the name in the table, please check now
![image](https://user-images.githubusercontent.com/1082644/106292132-c5c52400-624c-11eb-9d96-96aa53ebdb40.png)

**Comment by ElaChe00** [comment]
Super! Thanks
