### ISSUE TITLE
Stage buttons to relpace function of "create new substage"

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#301]
![image](https://user-images.githubusercontent.com/45791540/106154548-0440dd00-6180-11eb-8ab7-a3af39737d70.png)

- Please remove button "create new substage" and give the stage button the function
- Add title of stage button to e.g. "+ Treatment" or "+ Abstraction"
- Once you click on the stage button, the use should automatically go to the newly created stage.

**Comment by holalluis** [comment]
done, please check

**Comment by ElaChe00** [comment]
Perfect! Works well! Thanks
