### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#303]
Dear @holalluis , I talked to my colleagues regarding the filters. They (and also me) find the filters quite confusing. I like the idea of differentiaing between GHG and energy, but I find it unecessary to a have a filter for everything. We should max have 3-4 filter.

Therefore, I suggest the following for the stages:

**Water Abstraction:**
_Filter "GHG Emissions" including:_
![image](https://user-images.githubusercontent.com/45791540/107268349-515a6400-6a48-11eb-83c6-cab2a46a767e.png)
![image](https://user-images.githubusercontent.com/45791540/107268376-561f1800-6a48-11eb-9428-786fd2bc7598.png)

_Filter "Energy Performance": including_
![image](https://user-images.githubusercontent.com/45791540/107268541-8ff01e80-6a48-11eb-8f98-90374a6a0ee9.png)
![image](https://user-images.githubusercontent.com/45791540/107268376-561f1800-6a48-11eb-9428-786fd2bc7598.png)
![image](https://user-images.githubusercontent.com/45791540/107268586-a4341b80-6a48-11eb-87fd-33cb3b860996.png)

_Filter "Pump Efficiency": including_
![image](https://user-images.githubusercontent.com/45791540/107268926-202e6380-6a49-11eb-9977-6b54b5b9ab4f.png)

**Water Treatment:**
_Filter "GHG Emissions" including:_
![image](https://user-images.githubusercontent.com/45791540/107268740-e4939980-6a48-11eb-9f1d-3bb4f724f0cb.png)
![image](https://user-images.githubusercontent.com/45791540/107268764-ebbaa780-6a48-11eb-82df-caf9309b38ed.png)

_Filter "Energy Performance": including_
![image](https://user-images.githubusercontent.com/45791540/107268740-e4939980-6a48-11eb-9f1d-3bb4f724f0cb.png)
![image](https://user-images.githubusercontent.com/45791540/107268764-ebbaa780-6a48-11eb-82df-caf9309b38ed.png)
![image](https://user-images.githubusercontent.com/45791540/107268846-05f48580-6a49-11eb-87af-04bb08b3b17a.png)

_Filter "Pump Efficiency": including_
![image](https://user-images.githubusercontent.com/45791540/107268962-2e7c7f80-6a49-11eb-893e-2b17c620f3fa.png)

**Water Distribution:**
_Filter "GHG Emissions" including:_
![image](https://user-images.githubusercontent.com/45791540/107269086-5c61c400-6a49-11eb-8548-91af5ee95a3d.png)
![image](https://user-images.githubusercontent.com/45791540/107269135-6e436700-6a49-11eb-98ee-f98650e55469.png)

_Filter "Energy Performance": including_
![image](https://user-images.githubusercontent.com/45791540/107269086-5c61c400-6a49-11eb-8548-91af5ee95a3d.png)
![image](https://user-images.githubusercontent.com/45791540/107269135-6e436700-6a49-11eb-98ee-f98650e55469.png)
![image](https://user-images.githubusercontent.com/45791540/107269347-c4b0a580-6a49-11eb-8813-5a552bc55395.png)

_Filter "Pump Efficiency": including_
![image](https://user-images.githubusercontent.com/45791540/107269214-8fa45300-6a49-11eb-9bc0-8017c7817dd4.png)

**Sanitation Collection:**
_Filter "GHG Emissions" including:_
![image](https://user-images.githubusercontent.com/45791540/107269625-283ad300-6a4a-11eb-95d1-faa2afe90d4f.png)
![image](https://user-images.githubusercontent.com/45791540/107269658-2ffa7780-6a4a-11eb-8001-fccfd2c8da72.png)

_Filter "Energy Performance": including_
![image](https://user-images.githubusercontent.com/45791540/107269716-46a0ce80-6a4a-11eb-9148-1964eaa27ef6.png)
![image](https://user-images.githubusercontent.com/45791540/107269727-4accec00-6a4a-11eb-992b-03b11e91dfef.png)

_Filter "Pump Efficiency": including_
![image](https://user-images.githubusercontent.com/45791540/107269811-6cc66e80-6a4a-11eb-8508-b70a8d44b323.png)

**Sanitation Treatment:**
_Filter "GHG Emissions" including:_
![image](https://user-images.githubusercontent.com/45791540/107269862-81a30200-6a4a-11eb-93a1-e29f60a280ce.png)
![image](https://user-images.githubusercontent.com/45791540/107270061-c0d15300-6a4a-11eb-92fe-07f7242555da.png)
![image](https://user-images.githubusercontent.com/45791540/107270121-d5155000-6a4a-11eb-9a57-1d523c7ebf85.png)

_Filter "Energy Performance": including_
![image](https://user-images.githubusercontent.com/45791540/107270410-32a99c80-6a4b-11eb-9dd8-e159af2a7bfd.png)
![image](https://user-images.githubusercontent.com/45791540/107270453-405f2200-6a4b-11eb-8237-4844c0e14228.png)

_Filter "Pump Efficiency": including_
![image](https://user-images.githubusercontent.com/45791540/107270484-49e88a00-6a4b-11eb-83ea-8531ab38ec78.png)

_Filter "Sludge Management": including_
![image](https://user-images.githubusercontent.com/45791540/107270546-608ee100-6a4b-11eb-9f92-a7faa187e801.png)
![image](https://user-images.githubusercontent.com/45791540/107270617-756b7480-6a4b-11eb-8fad-9612d9fa3cf2.png)

**Onsite Sanitation:**
_Filter "GHG Emissions" including:_
![image](https://user-images.githubusercontent.com/45791540/107270749-a186f580-6a4b-11eb-88ff-3ac97071cff7.png)
![image](https://user-images.githubusercontent.com/45791540/107270978-e1e67380-6a4b-11eb-9005-9e32cdd60f9e.png)
![image](https://user-images.githubusercontent.com/45791540/107271028-f4f94380-6a4b-11eb-8f21-55bbe4f8589d.png)
![image](https://user-images.githubusercontent.com/45791540/107271045-fb87bb00-6a4b-11eb-9be5-b01cc61d7590.png)
![image](https://user-images.githubusercontent.com/45791540/107271069-02aec900-6a4c-11eb-9af0-bc93b8ba5c58.png)

_Filter "Energy Performance": including_
![image](https://user-images.githubusercontent.com/45791540/107271118-12c6a880-6a4c-11eb-9b24-ae14b084e5a9.png)
![image](https://user-images.githubusercontent.com/45791540/107271140-18bc8980-6a4c-11eb-835c-c36d03f43e81.png)
![image](https://user-images.githubusercontent.com/45791540/107271150-1ce8a700-6a4c-11eb-8c3a-e92dde88fb1b.png)

_Filter "Sludge Management": including_
![image](https://user-images.githubusercontent.com/45791540/107271287-4c97af00-6a4c-11eb-963d-8c62fb24c110.png)

We can add other filters if necessary, but for now i would keep 'em simple.

Definitely remove filters like (population, costs, discharge etc for now)

**Comment by ElaChe00** [comment]
![image](https://user-images.githubusercontent.com/45791540/108085800-ffcc5d80-7075-11eb-9112-9ac9599b707f.png)

- Remove "Filters" button
- Remove "on/off" Button , because filters should always be shown
- When entering the system or stage, all filter should be deactivated
- Add new button called "Show all inputs" to deactivate the stages and show all inputs

- The box of the filter should have the same function as the title. Meaning if you click on the filter itgets activated, if you click on another filter e.g. 2 filters are activated

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/108210899-61e79a00-712c-11eb-820e-9e473d512b7c.png)
done please check

**Comment by holalluis** [comment]
Please note that I did not change that when clicking a filter does not disable the other ones (as discussed). The reason of this is that during testing felt weird having to click twice to change the filter. We can further discuss after testing it in its current state.

**Comment by ElaChe00** [comment]
Your comment is well noted, @holalluis . However, I cannot check the filters since the server hasn't been updated 👯

**Comment by holalluis** [comment]
it is updated, maybe the cache is holding the previous version, please press F12 to open the dev-tools, and check this option:
![image](https://user-images.githubusercontent.com/1082644/108219046-9e6bc380-7135-11eb-8a57-47d26d0d85d6.png)
then refresh the page

**Comment by ElaChe00** [comment]
That's what caused trouble! Thanks. it works now!

I was wondering: **Are " costs" the only inputs that are not assigned to a filter?**
If so, "other" can be renamed to "Costs".

But I thought that there where more inputs that weren't assigned to a filter or am I wrong?

**Comment by holalluis** [comment]
ok! What if we move all the inputs and questions with the yellow labeled under the "Other" label?

**Comment by ElaChe00** [comment]
Exactly, that's what I was thinking. let's do this! I think that's good !

**Comment by holalluis** [comment]
done please check

**Comment by ElaChe00** [comment]
Looks good!
