### ISSUE TITLE
Replace FlowChart 

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#306]
Hey Lluis, please replace the flow chart here:
![image](https://user-images.githubusercontent.com/45791540/107662874-041a0480-6c8b-11eb-9cf5-902d15c73445.png)

with this one for now:

![image](https://user-images.githubusercontent.com/45791540/107662831-fb293300-6c8a-11eb-81f2-dcd0659bf9c3.png)

SVG file: [FlowChart Replacement.zip](https://github.com/icra/ecam/files/5966681/FlowChart.Replacement.zip)

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/107794779-2594f200-6d58-11eb-90b5-20f82005296d.png)
done
