### ISSUE TITLE
Adapt ECAM 3.0 "More" Page

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#307]
Hola @holalluis 

the "More" page is currently looking like this:
![image](https://user-images.githubusercontent.com/45791540/107660619-c0be9680-6c88-11eb-92ae-6cf7e543bac0.png)
 For the beta-tesing, I kindly ask you to do the following:

- Remove "Help" (there won't be any help for now ;) )
- Remove "UNFCCC Categories" unless it can be fixed!
- Remove "Development" for now

**This will leave the following buttons:**
- About ECAM
- Flow Diagram
- Constants
- Benchmarks
- Equations
- Data Tables
- Non Revenue Water
- Fuel Types

Could you please use the following buttons? It should look like this:
![image](https://user-images.githubusercontent.com/45791540/107666162-7e985380-6c8e-11eb-8e64-317125c7c2c9.png)

PNG File:
![ECAM3 0_MorePage_Button](https://user-images.githubusercontent.com/45791540/107798546-9807d100-6d5c-11eb-95df-3978b00b2d85.png)

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/107988864-300df080-6fd1-11eb-9a07-8aaa12619616.png)
done

**Comment by ElaChe00** [comment]
The buttons work and the hover effect is simple! Good.
