### ISSUE TITLE
unfccc categories

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#310]
work in progress

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/108556878-fb16dc00-72f7-11eb-9382-81f4027df105.png)

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/108556922-0c5fe880-72f8-11eb-9203-a0933aede283.png)

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/108557753-4bdb0480-72f9-11eb-9844-2d33b26069a5.png)
bar chart in "compare scenarios"

**Comment by holalluis** [comment]
we can change the colors of each category

**Comment by ElaChe00** [comment]
Hey Lluis, thanks for the implementation. I am not sure what the different IDs are standing for.... labeling should be adapted. ECAM 2.2 can provide an orientation:
![image](https://user-images.githubusercontent.com/45791540/108692159-8fea2700-74fc-11eb-9399-a49d995bb2ca.png)

We don't need:
![image](https://user-images.githubusercontent.com/45791540/108692209-9e384300-74fc-11eb-99e8-aaa1a6128a82.png) - it's confusing.

As of colours: We can use the Report colours:
![image](https://user-images.githubusercontent.com/45791540/108692305-b90ab780-74fc-11eb-863b-f891ec758a22.png)

red: #D00B34
green: #46BA55
yellow: #EFA922
blue: #30A5D8

**Comment by holalluis** [comment]
done, please check
![image](https://user-images.githubusercontent.com/1082644/108750176-027cf600-7541-11eb-8f34-d786bb89e9a3.png)
![image](https://user-images.githubusercontent.com/1082644/108750215-0d378b00-7541-11eb-9c6d-ccf8e1fbd969.png)
![image](https://user-images.githubusercontent.com/1082644/108750245-16285c80-7541-11eb-85ab-ff6b671a08e9.png)

**Comment by ElaChe00** [comment]
My mistake, I don't know why I wrote red... I meant purple for "Waste" ( #85077C )
Can you remove the titles "UNFCCC_5D" etc please?  No one can really refer to them. It's sufficient to have the epxlaination

**Comment by holalluis** [comment]
done, please check

**Comment by ElaChe00** [comment]
That's it! Close please
