### ISSUE TITLE
Remove decimal places in emissions shown in substages

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#311]
@holalluis . could you please remove the decimal places in the interim results of the substages? See screenshot:

![image](https://user-images.githubusercontent.com/45791540/108224997-cc540680-713b-11eb-8c50-09833410d0e4.png)

**Comment by holalluis** [comment]
ok, do you want to remove it also in the totals?
![image](https://user-images.githubusercontent.com/1082644/108412989-c0933d80-722a-11eb-9be4-b210adb30df5.png)

**Comment by ElaChe00** [comment]
Yes, also there. Sorry, forgot to highlight it with a circle ;)
Remove it everywhere, where you come across it. Thanks!

**Comment by holalluis** [comment]
ok done
