### ISSUE TITLE
Outputs | Be consistent with upper and lower case letters

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#312]
Hey Lluis, could you please dapt the following (low priority, but should be fixed).

**Abstraction stage**
![image](https://user-images.githubusercontent.com/45791540/108262489-48af0f80-7165-11eb-93f8-7c1f44c6d97e.png)

**Treatment stage**
![image](https://user-images.githubusercontent.com/45791540/108262562-60869380-7165-11eb-9b24-d91e1e2f4acd.png)

**Distribution stage**
![image](https://user-images.githubusercontent.com/45791540/108262614-6f6d4600-7165-11eb-8364-013180d59a15.png)

**Collection stage**
![image](https://user-images.githubusercontent.com/45791540/108262666-80b65280-7165-11eb-9402-48162bd66f73.png)

and so on...

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/108265727-70a07200-7169-11eb-8b2e-2a82939b1128.png)
solved please check

**Comment by ElaChe00** [comment]
Thanks. Please check the systems (water supply and sanitation) too:

**Water supply system**
![image](https://user-images.githubusercontent.com/45791540/108266331-44392580-716a-11eb-8a5b-a4f89b29b6c3.png)

**Sanitation system**
![image](https://user-images.githubusercontent.com/45791540/108266393-5adf7c80-716a-11eb-80ac-12b62f2341a6.png)

**Comment by holalluis** [comment]
ok fixed, please check

**Comment by ElaChe00** [comment]
Thanks! I think it's better this way
