### ISSUE TITLE
Compare Assessments | Rename buttons of diagrams

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#313]
![image](https://user-images.githubusercontent.com/45791540/108417683-93e22480-7230-11eb-8c93-e7d5e45f3fcf.png)

From left to right:

- Table: inputs & outputs
- Bar chart: total GHG emissions
- Bar chart: emissions by GHG
- Bar chart: emissions by stage
- Bar chart: total energy consumption

(I hope it's not too long.....for buttons)

**Comment by holalluis** [comment]
done please check
![image](https://user-images.githubusercontent.com/1082644/108422580-09e98a00-7237-11eb-8abe-2192b365a0dc.png)

**Comment by ElaChe00** [comment]
Superbe!

Ist it possible to make it like this (but centered):

Table:
inputs & outputs

Bar chart:
total GHG emissions

etc.

Meaning that Table or Bar Shart are in the first line/row, and the description comes in the second line. This way we have 2 rows in every button!

**Comment by holalluis** [comment]
yes! done
![image](https://user-images.githubusercontent.com/1082644/108525110-0b1ac580-72d0-11eb-9a12-e758c945c2cf.png)

**Comment by ElaChe00** [comment]
Yes! Definitely better!
