### ISSUE TITLE
Update Protein Value vor Peru

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#316]
Dear Lluis, 
could you please update the protein value of Peru? According to FAO (2018) the value has increased to **28.4 kg/person/year** (converted from 77.81 g/capita/day).

![image](https://user-images.githubusercontent.com/45791540/111294809-fd482e00-864a-11eb-82eb-c91c2834a9f9.png)

Source: http://www.fao.org/faostat/en/#data/FBS/visualize

**Comment by holalluis** [comment]
done, please check
![image](https://user-images.githubusercontent.com/1082644/111369405-52119600-8697-11eb-946a-3e358b01c99e.png)

**Comment by ElaChe00** [comment]
For some reason it says?
![image](https://user-images.githubusercontent.com/45791540/111481242-0ad8e300-8733-11eb-9b4b-b9866d71edba.png)

But 77.81 * 365 = 28.40

**Comment by holalluis** [comment]
24.455 is the previous value, probably you have to refresh the cache

**Comment by ElaChe00** [comment]
Can see it now
