### ISSUE TITLE
Need for first-time-tutorial / Tips

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#317]
Hi Lluis, 

we need a function that shows what to do and where to click. Many users are missing a clear line or "next steps". 

Since we wanted to avoid a next button, I think we should try to integrate the "tips" as suggested by VITI:

![image](https://user-images.githubusercontent.com/45791540/112134731-4ceba400-8bcd-11eb-8bcb-3dc6987e6030.png)

![image](https://user-images.githubusercontent.com/45791540/112134752-5248ee80-8bcd-11eb-94a9-4a81395b9480.png)

**Comment by ElaChe00** [comment]
This fact sheet could also give some orientation:
[ECAMv3_Factsheet_EN.pdf](https://github.com/icra/ecam/files/6341675/ECAMv3_Factsheet_EN.pdf)

![image](https://user-images.githubusercontent.com/45791540/115359698-3847ff00-a1bf-11eb-8c84-0345a5835cf8.png)

Once it is possible to add tips, I can write the text for more buttons :)

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/119732005-ee1a0380-be77-11eb-92a1-b2e2b94cd6ae.png)
![image](https://user-images.githubusercontent.com/1082644/119732015-f3774e00-be77-11eb-8974-304306334e14.png)

hi, I've started doing the tips. A problem that I have is that I find very difficult to make them float, for now they are inline with other elements and they disappear once you click "OK"

**Comment by ElaChe00** [comment]
Nice! But I like it so far!!

**Comment by ElaChe00** [comment]
![image](https://user-images.githubusercontent.com/45791540/120181568-86fca600-c20d-11eb-9d00-2a5fc9a522e5.png)

Rename to "Include tips for new ECAM users"

**Comment by holalluis** [comment]
done, please check
