### ISSUE TITLE
General stage is not intuitiv - add icon

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#318]
Dear Lluis,

many have said that the general stage is not intuitiv (as we thought at the beginning).
I suggest to include icons there. It can simply be a small water drop.

See files attached:
[GeneralStages.zip](https://github.com/icra/ecam/files/6189007/GeneralStages.zip)

It should look like this:
![image](https://user-images.githubusercontent.com/45791540/112137248-4f033200-8bd0-11eb-84e1-0f0744d8968d.png)

**Comment by holalluis** [comment]
done, please check

**Comment by ElaChe00** [comment]
Way better! I like it very much. Is it possible to give every stage button the same hover effect (zoom/size incrase)? This way we would be consistent with the effect on this part.

**Comment by holalluis** [comment]
done, please check

**Comment by ElaChe00** [comment]
great. Thanks
