### ISSUE TITLE
Energy consumption and emission factor should also be at the bottom

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#319]
Dear Lluis,

it is confusing that that **energy consumed from grid** and **emission factor from grid electricity** are always found at a different places, even though those to are the only constant inputs.

The simply this, please make those two the **last inputs of every stage** (right before the questions). I would actually prefer them to be the first inputs, but in some stages population has to be added ...and this data is more important.

**Comment by holalluis** [comment]
done, please check

**Comment by ElaChe00** [comment]
Great, Thanks
