### ISSUE TITLE
OnSite Sanitation | Delete variables that are not being used 

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#320]
Hi @holalluis , could you please delete the **following variables,** since there are not being used? Thanks

- Volume  of uncollected wastewater conveyed to onsite treatment | wwo_vol_unco_ons
- Volume of treated wastewater | wwo_vol_unco_tre
- Volume of discharged effluent   to water body | wwo_vol_disc
- CH4 emission factor (untreated wastewater) | wwo_ch4_efac_unt
- Main containment type | wwo_type_con
- Main treatment type | wwo_type_tre
- Main disposal type | wwo_type_dis
- Type of faecal sludge disposed | wwo_fslu_typ

**Comment by holalluis** [comment]
done, please check. Resetting cache is needed
