### ISSUE TITLE
Change function of stage buttons

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#322]
Dear @holalluis - back to the roots.

We might need to give the original funtion back to the stage buttons:
![image](https://user-images.githubusercontent.com/45791540/112281808-c398a800-8c86-11eb-99d7-4b00f9c0a136.png)

So instead of creating a new stage, it should jump to the first substage.

This means that a "Add substage" button needs to be added again

**Comment by holalluis** [comment]
done, please check

**Comment by ElaChe00** [comment]
perfect
