### ISSUE TITLE
Delete Bin | Warning message before substage will be removed

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#323]
Dear Lluis, could you please include the warning message again. So that before a sub stage is being deleted a pop-up windows asks "Do you want to delete this substage?"

![image](https://user-images.githubusercontent.com/45791540/112282041-022e6280-8c87-11eb-83ff-c8aa2200b379.png)

**Comment by holalluis** [comment]
the message is already there,  only displayed when emissions are greater than zero

**Comment by ElaChe00** [comment]
okay

**Comment by ElaChe00** [comment]
okay
