### ISSUE TITLE
WW Treatment | Change unit of Biogas

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#324]
Hi lluis, it is easier to work with m³ than with kg.

![image](https://user-images.githubusercontent.com/45791540/112283047-0313c400-8c88-11eb-8f2b-938a9b1087fb.png)

The unit should be m³. Not sure how the calculation needs to be adapted accordingly, but in ECAM 2.2 we didn't use kg.

**Comment by holalluis** [comment]
The equations were adapted from a PhD thesis (from Laura Snip), so the equations were different, they worked in kg. I dont' know how to convert from kg to m3 (probably with the equation PV=nRT, but I'm not sure, in this case we would need to ask for temperature and pressure of the gas to know the volume) so maybe @lcorominas can help us here

**Comment by ElaChe00** [comment]
We have discussed this, right? What is the current status. Has Lluis Coromonias found a way for the conversion?

**Comment by holalluis** [comment]
we've discussed this with Lluís C., now we have the biogas produced in Nm3, please check it. Now is for wastewater treatment only, the biogas in onsite treatment will be adapted using the same changes

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/116449574-9a0d0680-a85a-11eb-9e50-1119c4ef3375.png)

**Comment by holalluis** [comment]
status: reproducing the same changes in onsite treatment

**Comment by ElaChe00** [comment]
Thanks. Definitely better!

Could you please put "biogas" under "Energy Performance" Thanks!

**Comment by holalluis** [comment]
done
