### ISSUE TITLE
Possibility to change units in results (and everywhere)

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#325]
Dear Lluis, is it possible to integrete a button to change between units kg -> t ? 
This would also be helpful, also for the report, where the numbers are quite long...

![image](https://user-images.githubusercontent.com/45791540/112283765-c72d2e80-8c88-11eb-8426-18d761b7c92d.png)

**Comment by holalluis** [comment]
I can do that. But, what if some numbers are small and others are large?

**Comment by ElaChe00** [comment]
I think this is only complicated when numbers are smaller than 0 right? Maybe you can add 3 decimal places in this case? What do you think? I am also not sure myself yet, but we can discuss this together

**Comment by holalluis** [comment]
done, please check
![image](https://user-images.githubusercontent.com/1082644/117348703-cc49e400-aeaa-11eb-830e-19e652294958.png)

**Comment by ElaChe00** [comment]
Thanks!
