### ISSUE TITLE
Size of Bar Diagrams

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#326]
Hi Lluis, the width of the bar diagrams should be smaller.
At the same time, the font should be bigger. It is still difficult to read.

![image](https://user-images.githubusercontent.com/45791540/112320822-ad531200-8caf-11eb-870e-b13fa24d606d.png)

**Comment by holalluis** [comment]
Hi Elaine this is a difficult request, which would be the correct size for all number of scenarios and/or screen sizes?

**Comment by holalluis** [comment]
Dear Elaine, is the new chart library default width of columns and size of text ok?

**Comment by ElaChe00** [comment]
Hey Lluis, the new chart library is so much better! Thanks a lot.
Also, I like that we can see the absolute numbers:
![image](https://user-images.githubusercontent.com/45791540/115682594-e9809d80-a355-11eb-915c-7cbc468e5d56.png)

Very nice.

Now, only the percentages of the line charts are missing, but this is another issue, so we can close this one.
