### ISSUE TITLE
Compare Assessments | Difference between inputs & outputs not clear

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#327]
Dear Lluis, under "Compare Assessments" - Table, the difference between inputs & outputs is not clear. 
I am actually not clear myself...

**Comment by ElaChe00** [comment]
![image](https://user-images.githubusercontent.com/45791540/112321575-716c7c80-8cb0-11eb-90f0-1065aee3b310.png)

![image](https://user-images.githubusercontent.com/45791540/112321602-76c9c700-8cb0-11eb-8e0d-043835ee872f.png)

**Comment by holalluis** [comment]
Hi, I've fixed the behaviour of the summary table, please check now

**Comment by ElaChe00** [comment]
Hey @holalluis , I believe that the users problem ist, that input and outputs are shown in one table. That makes it not so clear. I believe it would be better to have 2 separate tables to make it clearer (Might be difficult due to space to have both on one page). But maybe it would be better to try to separate those.

What do you think?

Because right not "Summary" is stillt shown , even though one has selected only inputs):
![image](https://user-images.githubusercontent.com/45791540/115355563-13ea2380-a1bb-11eb-9500-4c555cc3049c.png)

 At the same time, "General" is shown, even though only outputs are selected:
![image](https://user-images.githubusercontent.com/45791540/115355657-2c5a3e00-a1bb-11eb-8769-b08f32af8a6e.png)

I think it would be better to have both of different pages instead on one. Maybe different buttons (instead of a filter).

**Comment by holalluis** [comment]
Dear Elaine, the summary table is much clearer now, take a look at it and let me know what you think. Thanks!

**Comment by ElaChe00** [comment]
Very impressive! I t's definitely more information and might be exactly what we need. I am looking forward to see updates on this!

**Comment by holalluis** [comment]
now i'm implementing the unit change for this section

**Comment by holalluis** [comment]
merged with #325
