### ISSUE TITLE
"Hide" Outputs

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#329]
Dear Lluis, as discussed during our last call, it would improve user-friendliness if we could "hide" the outputs in the inventory. This way, the page is not overloaded with information.

Something like this?
![image](https://user-images.githubusercontent.com/45791540/113114262-729b2d80-920b-11eb-8efa-6977f9eee673.png)

**Comment by holalluis** [comment]
Dear Elaine, I've done a first version, please check and let me know if it works for you
![image](https://user-images.githubusercontent.com/1082644/113748914-5581c580-9709-11eb-9905-b97fd7fdc80a.png)

**Comment by ElaChe00** [comment]
Great! Can you give it a grey hover effect please?

**Comment by holalluis** [comment]
done, please check

**Comment by ElaChe00** [comment]
Perfect
