### ISSUE TITLE
display number in line chart (% variation wrt to prev assessment)

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#330]
Dear Lluis, as discussed during our last call, it would be great to have a digramm that actually compares one result to another.

People are interested in the percentage difference apart from the absolute numbers. We can include this in the bar chart or add it to the line graph like this or both..:
![image](https://user-images.githubusercontent.com/45791540/113115413-b3e00d00-920c-11eb-99a2-1c9374c60eea.png)

It should also be possible to select the numbers you want to compare:
![image](https://user-images.githubusercontent.com/45791540/113115439-bb071b00-920c-11eb-92a8-fd326ca34de7.png)

**Comment by holalluis** [comment]
Hi Elaine, as a quick way to achieve this with the existing code for bar charts I implemented this bar chart below the total GHG by assessment:
![image](https://user-images.githubusercontent.com/1082644/113885882-7f49f380-97c0-11eb-8ac8-cf4f4da1485b.png)

It has a red bar in case ghg increased and a green bar in case ghg decreased, let me know if it works for you

**Comment by ElaChe00** [comment]
Hey lluis, it would actually be good to have a percentage rather then another bar chart. 

Even if the line chart is not possible , it would be good to show how much has increased or decreased from one year to another..

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/114072444-93662180-98a2-11eb-9ed6-c91f4f0c04ab.png)

Hi Elaine I've added a line chart with a new chart library, now I'm figuring out if numbers can be displayed without the need of hovering with the mouse

**Comment by ElaChe00** [comment]
Great! I think once one can see the numbers (in percent) we are good. Because absolute numbers will be shown it the graph above. In the line chart, only the percentages are of relevance. I am looking forward to see the results. Thanks!

**Comment by holalluis** [comment]
Hi, since this is a limitation of the chart js library (https://www.chartjs.org/docs/latest/charts/line.html) I think we can close this, and if in future versions of the library they add this feature we can add it
