### ISSUE TITLE
Include sources (of the equation) directly in the equation

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#331]
Dear Lluis, this might need some further work from Lluis' side, but I will include this "issue" here already. Just so that we don't forget.

We want to move away from a document with sources to having all the sources in the tool. With the option that you suggested (to show the page of the IPCC report directly. But showing the page in ECAM would already be the luxurious version...

**Comment by holalluis** [comment]
Hi Elaine, for now I've added a button in "more" that takes you to a list of all documents for IPCC 2006 and IPCC 2019 refinement
![image](https://user-images.githubusercontent.com/1082644/113886145-bae4bd80-97c0-11eb-9c96-8c0cbbf04f57.png)

This is the list of all documents, they are stored in the ecam repository so they are available
![image](https://user-images.githubusercontent.com/1082644/113886196-c46e2580-97c0-11eb-92cc-e5f8b1f77af9.png)

The purpose of this is that there exists a nice way of going directly to a page of a pdf file that is being browsed through the browser itself. When I have an example completed I'll write it here

**Comment by holalluis** [comment]
currently we have a student that is being introduced to ecam and will do this task

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/118846843-69564500-b8cd-11eb-97d6-5cb6082b0454.png)

tables now have reference

**Comment by holalluis** [comment]
now that the framework for having references inside equations is working I close this issue and we can open issues for missing references for specific equations
