### ISSUE TITLE
Add a "Frequent Asked Questions (FAQ)" section

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#332]
I think is necessary a FAQ section

**Comment by ElaChe00** [comment]
I have already reserved a place on www.wacclim.org for the FAQ, but I agree, it would be good to have a spot directly in the tool.

**Comment by ElaChe00** [comment]
Hey Lluis, I was thinking that we could add a page, not with videos, but actually with short gifs?
Below, we could add a button with FAQ.
![image](https://user-images.githubusercontent.com/45791540/117783280-af166c00-b242-11eb-8c33-1ca2efa62787.png)
 
Then we can list different questions that you can "unfold" when you click on them:
Under the questions should be a short description and a gif.

**"How do I start an assessment?"**
![How to start an assessment](https://user-images.githubusercontent.com/45791540/117785342-c6eeef80-b244-11eb-8290-6cbb21022403.gif)

1. Click on "Start your assessment".
2. Choose a name for your assessment e.g. "Utility X 2020".
3. Select the time period. This input will be the basis for most calculations made in ECAM.
4. Select the country the utility is located in.
5. If needed, adapt values of emission factor for grid electricity, annual protein consumption per capita or BOD5 generation.
6. Click on "Access inventory" to input your data


**"How do I open an existing file?"**
![How to load a file](https://user-images.githubusercontent.com/45791540/117785734-26e59600-b245-11eb-901a-f6709a65e75e.gif)
1. Click on "Configuration" to load or save a file
2. Choose between "Replace" or "Append"
3. Select an existing .json file from your computer and press "open"
4. Your existing .json file will be loaded.

**Comment by ElaChe00** [comment]
Me too! I think this could work. I will try to create several HQ gifs and questions and will share them here, so you can easily implement them. One by one :)

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/119548309-5db7c200-bd96-11eb-8d7c-a3997d810159.png)
done, please check, I've put some placeholder questions for now

**Comment by ElaChe00** [comment]
![image](https://user-images.githubusercontent.com/45791540/120156763-96222a80-c1f2-11eb-8e99-03f6951a3521.png)

Rename to "Frequently Asked Questions"

**Comment by holalluis** [comment]
done, please check

**Comment by ElaChe00** [comment]
We will probably need to cluster the questions a bit.

There are some _general questions_ and some _related to the use of ECAM._

**Comment by ElaChe00** [comment]
Is it possible to "close one questions" if you "open another question"?
