### ISSUE TITLE
More detailed summary

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#334]
Dear Lluis, we should think about how we can illustrate certain emissions in the summary.
![image](https://user-images.githubusercontent.com/45791540/115552588-c948d400-a2ac-11eb-951a-c161b8760772.png)

We have removed most of it to keep it simple for the beta-testing phase, but now we should include information regarding "Avoided emissions" again. 

Or e.g. in On-Site sanition, the user wants to know where which emissions occur, otherwise ECAM is useless to them. It should be clear how many emissions come from "open defecation" or from "Containtment" or from "treatment" etc

**Comment by holalluis** [comment]
duplicated #341
