### ISSUE TITLE
CH4 factor "Treatment" | Remove OSS factors

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#335]
Hey Lluis, could you remove the CH4 factors for OSS please?

![image](https://user-images.githubusercontent.com/45791540/115553701-02ce0f00-a2ae-11eb-9acb-f79501c14435.png)

 **Septic Tank** or **Pit Latrine** would belong to "On-Site Sanitation"? We can also discuss this together.

**Comment by holalluis** [comment]
fixed, please check

**Comment by ElaChe00** [comment]
Yes, I think this is better. Hopefully it works for everyone. But for those, who want to evaluate septic tanks and latrines, I would tell them to activate the onsite sanitation stage.
