### ISSUE TITLE
Total nitrogene load in the effluent | Manuel input or correction value?

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#336]
Hey Lluis, is there a possibility to adapt the value of efficiency?

![image](https://user-images.githubusercontent.com/45791540/115554375-acad9b80-a2ae-11eb-8762-03b68f33fd77.png)

I am referring to this comment made during the **beta-testing:**
_"The default value proposed for the situation I tested (a primary+ secondary treatment only) seems off. It assumes a 40% removal of N whereas secondary plants can have a 60 to 70% removal depending on the load and temperatures… In France most plant have a low loading rate with no tertiary treatment and remove 60 to 80% of N that way. It would be good to make the correction or clarify “high-rate secondary biological treatment” rather than “primary + secondary”"_

I don't know whether this is feasible?

**Comment by holalluis** [comment]
easiest solution is: convert wwt_bod_effl from kg to percentage and adapt equations

**Comment by holalluis** [comment]
Dear Elaine now I realize that the comment refers to Nitrogen, not BOD. What we have is this:
![image](https://user-images.githubusercontent.com/1082644/115735776-097e8400-a38b-11eb-9491-4b82c750c9d6.png)

so this is the variable that should be changed, not the BOD in the effluent, is this right?

**Comment by holalluis** [comment]
Dear Elaine, I've added the IPCC reference to this variable, so the user can check the exact table that the IPCC suggests those values. I guess that that's as far as we can go to tell those values
![image](https://user-images.githubusercontent.com/1082644/117700440-50131180-b1c6-11eb-8fb9-6965ed83ab7a.png)

**Comment by ElaChe00** [comment]
Hey Lluis, is there a way to insert percentages instead of KG? The user could calculate their own kq (if the efficiency deviates from the provided numbers 100%, 90%, 60%, 20%). However, this would require a calculater or extra excel sheet.

Is there a simpler way or would this be too complicated?

**Comment by holalluis** [comment]
Dear Elaine, I think this is too much, adding a new window for just this case, I would just use it how it is, I think it's not too complicated for a normal user to calculate a percentage using whatever tool he/she wants
