### ISSUE TITLE
Units in "Compare Assessments"

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#337]
Hi Lluis, the units might need to get adapted:
![image](https://user-images.githubusercontent.com/45791540/115555326-a9ff7600-a2af-11eb-884a-831e730babcf.png)

It only shows "kg" not even "kgCO2eq". It should be possible to select whether:
![image](https://user-images.githubusercontent.com/45791540/115555441-cc918f00-a2af-11eb-935b-8835542fc7cb.png)

For our reporting in WaCCliM, kgCO2eq/ serviced population is most relevant :)

**Comment by holalluis** [comment]
#325 Duplicated
