### ISSUE TITLE
Start new assessment

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#338]
Dear Lluis, in the feedback of the ecam beta-testing phase, there where several comments regarding the intuitivity of starting an assessment. Maybe we should be clearer here:

I suggest that when you click on "Start your assessment"

![image](https://user-images.githubusercontent.com/45791540/115556439-f6978100-a2b0-11eb-9fc8-e6d10808124c.png)

this window is automatically opened:
![image](https://user-images.githubusercontent.com/45791540/115556528-129b2280-a2b1-11eb-8a6d-91b0f6e7d305.png)

Currently, you will have to click on the assessment to open the fields. 

Further, **load file** and **save file** are quite prominent. Maybe we can make this a little bit smaller or place it somewhere else? On the side? Vertically?

![image](https://user-images.githubusercontent.com/45791540/115556758-49713880-a2b1-11eb-9467-16328447e3ba.png)

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/115612861-05e7f000-a2ec-11eb-883b-02af81ad3262.png)
![image](https://user-images.githubusercontent.com/1082644/115612920-14360c00-a2ec-11eb-8d3f-3c0fa09ade8b.png)
done, would something like this work?

**Comment by ElaChe00** [comment]
Yes! This looks great! 
Maybe change "File" to "Load existing file"?

**Comment by holalluis** [comment]
#342 duplicated
