### ISSUE TITLE
upgraded results / summary table

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#341]
![image](https://user-images.githubusercontent.com/1082644/115794406-3ef89100-a3ce-11eb-95a5-3ea37bf84198.png)

**Comment by holalluis** [comment]
work in progress
![image](https://user-images.githubusercontent.com/1082644/116336169-65586b00-a7d8-11eb-9d7a-b93e27f0e81f.png)

**Comment by holalluis** [comment]
unit change implemented
![image](https://user-images.githubusercontent.com/1082644/116460358-46ed8080-a867-11eb-9830-572d8ab81f2a.png)

**Comment by holalluis** [comment]
Dear Elaine, I've added the option we've discussed today, let me know if works for you
![image](https://user-images.githubusercontent.com/1082644/117343839-01533800-aea5-11eb-8483-dd3f198dfa59.png)

**Comment by ElaChe00** [comment]
- Please change label to "Show emissions in CO2, CH4 and N2O"

The fefault should be that the numbers are not shown, when you go to this table. Only if you click on the filter, the shares will be shown.

- Could you please increase the size of the font + make "Total GHG emissions", "Water supply" and "Sanitation" bold?
![image](https://user-images.githubusercontent.com/45791540/117787357-ae7fd480-b246-11eb-9489-32d59a9d3756.png)

- Could you also make the stages bold please and increase the size of the indiviual emissions sources?
- Could we see, how everything would look like if the font were white for all the information given?
- Could we have a table showing energy consumption per level AND stage? (as we had in ECAM 2.2) This information is missing now. We "only" have the diagrams of energy consumption per substage
![image](https://user-images.githubusercontent.com/45791540/117788130-657c5000-b247-11eb-803a-4cca91f61187.png)

**Comment by holalluis** [comment]
Dear Elaine,
I've added the summary table for energy consumption, plese have a look, it is displayed clicking the circled buttons
![image](https://user-images.githubusercontent.com/1082644/118013588-8da4a580-b352-11eb-9f4b-858d6f0cb18e.png)

**Comment by ElaChe00** [comment]
Very nice!
