### ISSUE TITLE
Steps to "Inventory" are not clear (enough)

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#343]
Dear Lluis, I have noticed that some comments mentioned that the way from "configuration" to "inventory" is not clear (enough.) 

Is it possible to add a prominent button under "BOD5 generation" that says:
"Access inventory to insert input data"

Could look like this:
![image](https://user-images.githubusercontent.com/45791540/116057584-3c709280-a67f-11eb-8e95-cd7adda63d95.png)

**Comment by holalluis** [comment]
Dear Elaine, I'm in the process of adding the button, but I see that is kind of redundant with the little button in "options", Maybe we can remove the little one and keep this new big one, what do you think?
![image](https://user-images.githubusercontent.com/1082644/116290365-ac703d00-a793-11eb-8032-0ffafa7a9b4d.png)

**Comment by ElaChe00** [comment]
Hey Lluis, thanks for adding the button so fast! I agree with you. Please remove the little "inventory" button. Thx

**Comment by holalluis** [comment]
done, please check
