### ISSUE TITLE
Rename "~no substages" 

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#344]
![image](https://user-images.githubusercontent.com/45791540/116076247-45b82a00-a694-11eb-85f1-49f3e4527995.png)

Could you please change the text to:

"Create substage to insert further information"

**Comment by holalluis** [comment]
I added a mouse-over tooltip, following the same principle of the loading file section: to keep it simple for experienced users, and also intuitive for new users. 
![image](https://user-images.githubusercontent.com/1082644/116447950-d63f6780-a858-11eb-83bc-a22dfb011bce.png)
