### ISSUE TITLE
Results - Charts Serviced Population

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#345]
![image](https://user-images.githubusercontent.com/45791540/116077603-f246db80-a695-11eb-9bef-eab5cd8a450c.png)

Please add the "grey" as a colour to the legend, next to "Resident population"

**Comment by holalluis** [comment]
the grey part it's not exactly the resident population, the resident population is the total (grey + blue) or (grey + red)... We need to figure out a way to represent the grey part, or I can simply label it as "non-serviced population"

**Comment by holalluis** [comment]
fixed please check
