### ISSUE TITLE
Same bar charts in "Results" and "Compare Assessments"

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#346]
Dear Lluis, currently there are two different types of bar charts.

In **results** we have these:
![image](https://user-images.githubusercontent.com/45791540/116087438-24aa0600-a6a1-11eb-8db4-d497968f6248.png)
Here, we cannot activitate or deactivate GHGs and we can't really see the absolute numbers

In **Compare assessments** we have the new (and better) ones:
![image](https://user-images.githubusercontent.com/45791540/116087714-6d61bf00-a6a1-11eb-8766-5afb7bab9898.png)

Would be good to have the same bar charts.

**Comment by holalluis** [comment]
done, please check

**Comment by ElaChe00** [comment]
Perfect
