### ISSUE TITLE
ECAM freezes?

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#349]
Dear Lluis, it's the first time that I am encountering this issue and it also does not happen everytime:

I have tried to load a file (produced in ECAM 3.0) and now I cannot select/ click on buttons anymore. When I click on "refresh", the page is not loading. I have to empty the cache to make it work again.

Is this what happened to you before too?

**Comment by holalluis** [comment]
Dear Elaine, I've faced this too. I'm currently looking for the cause, it seems to be related to the navigation history tools from the browser itesel (ecam keeps track of the pages visited in the history of the browser, but in reality it is a single page app)

**Comment by holalluis** [comment]
I did change a little bit the code that manages history navegation between "ecam pages", this is because ecam is a single page app. Since then, I've never encountered the bug again in several days of testing, I close for now but we can reopen if it happens again
