### ISSUE TITLE
"Load an assessment from Excel"

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#350]
![image](https://user-images.githubusercontent.com/45791540/117794762-d4f53e00-b24d-11eb-9cec-c285b1f73aa2.png)

Change name to:
_Load assessment from Excel file_

Rename steps to:

1) Download ECAM input template: (add and rename button to "ECAM Template") 
2) Fill out template file
3) Upload filled file: (button)

**Comment by holalluis** [comment]
done please check
