### ISSUE TITLE
UNFCCC Category

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#351]
Dear Lluis, we might need some input from Lluis C. here.

I would remove two categories here, since they do not apply to us:
![image](https://user-images.githubusercontent.com/45791540/117795193-3c12f280-b24e-11eb-9a77-c47625be9e2b.png)

![image](https://user-images.githubusercontent.com/45791540/117795985-f571c800-b24e-11eb-9b60-5211488165d4.png)

"Waste - Incineration" , "Waste - Solid Waste Disposal" and "Waste - Biological Treatment of Solid Waste" do not belong here. This is referring to "actual" dormestic solid waste.

What are your thoughts?

Further, I would make the difference in colour between energy (elecitricity) and Energy (transport) a little bit more apparent.

**Comment by holalluis** [comment]
Do we have a final decision on these?

**Comment by ElaChe00** [comment]
Well, Lluis C. said he would look into it ;) But I guess, we just decide between you and me.

Please remove everything except :
![image](https://user-images.githubusercontent.com/45791540/119977186-61c32a00-bfb8-11eb-9762-d1a478970a74.png)
![image](https://user-images.githubusercontent.com/45791540/119977150-566ffe80-bfb8-11eb-9bc1-af772c279bee.png)

**Comment by holalluis** [comment]
hide for now, in: summary, report and compare assessments

**Comment by holalluis** [comment]
done, please check
