### ISSUE TITLE
Update emission factors for grid electricity

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#353]
Dear Lluis, since the EF for grid electricity are quite dated, we should think about replacing them. I couldn't find a complete list with all countries, but maybe we could update the ones that we have?

Also, each country should have a footnote to indicate the source. Currently, it is not clear which numbers come from where.

See example below:

Algeria - EF<sup>1</sup>
Angola - EF<sup>1</sup>
Argentina - EF<sup>2</sup>

References
<sup>1</sup> Reference Example
<sup>2</sup> Reference Example

Since the sources would be different for the values, the following indication of source wouldn't work anymore. One source does no apply to all values anymore if we update certain countries:
![image](https://user-images.githubusercontent.com/45791540/117872095-8de36900-b29e-11eb-875a-ba54b164e29f.png)

__________________________

There is a 2020 EF list, which could be purchased:
https://www.iea.org/data-and-statistics/data-product/emissions-factors-2020#emissions-factors 
![image](https://user-images.githubusercontent.com/45791540/117871327-8b344400-b29d-11eb-9f1b-f4b192b05a0c.png)

I will need to discuss with the team whether it makes sense to purchase this one.

Otherwise, here is a list from 2019 (only a few countries):
https://www.carbonfootprint.com/docs/2019_06_emissions_factors_sources_for_2019_electricity.pdf

or here:
https://www.iges.or.jp/en/publication_documents/pub/data/en/1215/IGES_GRID_EF_v10.10_20210223.xlsx (I will also attach this file)
[IGES_GRID_EmissionFactors.xlsx](https://github.com/icra/ecam/files/6461484/IGES_GRID_EmissionFactors.xlsx)

Possible to have EFs from different sources (but we have to be transparent)

**Comment by holalluis** [comment]
Dear Elaine, I think we should associate emission factors for electricity to years, so when the user selects a country and an assessment period, the emission factor for that specific year is written in the text field. So, the ideal would be having all the emission factors for all years for all countries. The user should view the different emission factors for the different years in a "more info" button, something like this:
![image](https://user-images.githubusercontent.com/1082644/118721763-8df9e080-b82b-11eb-9fb9-2e1875c8fbcb.png)
we can discuss this next meeting

**Comment by ElaChe00** [comment]
This is also a good idea. Not sure I grasp it completely, but we can discuss is on thursday.
here is another list with emissions factors from the EIB:
https://www.eib.org/attachments/strategies/eib_project_carbon_footprint_methodologies_en.pdf

**Comment by ElaChe00** [comment]
Discussed: EF from EIB (2020) will be implemented, replacing the ecometrica (2020) EFs.

**Comment by ElaChe00** [comment]
Looks good. Could you please adapt the sources:

[1.  European Investment Bank (2020): Methodologies for the assessment of project GHG emissions and emission variations.](https://www.eib.org/attachments/strategies/eib_project_carbon_footprint_methodologies_en.pdf#page=36)

[2. Food and Agriculture Organization of the United Nations (2021): FAOSTAT Database. ](http://www.fao.org/faostat/en/#data/FBS/visualize)

[3. IPCC (2006): Guidelines for National Greenhouse Gas Inventories, Vol. 5 Waste, Chapter 6, p. 22 (2019 revision)](https://ecam.icradev.cat/ecam/v3/frontend/docs/2019-ipcc/5_Volume5/19R_V5_6_Ch06_Wastewater.pdf#page=22)

[4. Countries of the World (2021): List of currencies of the world.](https://www.countries-ofthe-world.com/world-currencies.html)

**Comment by holalluis** [comment]
done, please check
