### ISSUE TITLE
Onsite: _Influent BOD load (wwo_bod_infl)_ in two equations

### ISSUE THREAD

**Issue by sebakoe** [icra/ecam#357]
Dear Lluis,
I am a co-worker of Elaine and she suggested that it would be easier, if I post the issues/bugs/etc. I have found directly here. I will mainly look at the Onsite Sanitation stage. /Sebastian

The variable _Influent BOD load (wwo_bod_infl)_ is used in two calculations _wwo_KPI_GHG_containment()_ and _wwo_KPI_GHG_tre()_. But it should only be used for one.

I would suggest to use _wwo_bod_infl_ only for _wwo_KPI_GHG_tre()_ . So that it fits with with _Effluent BOD load_. 

The calculation of estimation value (and description) for _Influent BOD load_ needs then to be adjusted as well and should be the same value as _BOD removed as faecal sludge (wwo_bod_rmvd)_ for that specific substage and not be based on the onsite population because:
•	There is already some BOD removal within the containments;
•	And only the BOD which is removed as faecal sludge can reach the treatment plant.

To calculate _wwo_KPI_GHG_containment()_ I would suggest a new variable named "_BOD load entering the containments (wwwo_bod_cont)_". For this one you could use the desciption and calculation of estimation value from _Influent BOD load (wwo_bod_infl)_ as it is right now.

Here the adjustments to the equations in short:

wwo_KPI_GHG_containment(){
      let co2   = 0;
      let n2o   = 0;
      let ch4   = (~**wwo_bod_infl**~ **wwo_bod_cont**-wwo_bod_rmvd)*wwo_ch4_efac_con*ct_ch4_eq;
      let total = co2+n2o+ch4;
      return {total,co2,n2o,ch4};
    }

wwo_KPI_GHG_tre(){
      let co2   = 0;
      let ch4   = (**wwo_bod_infl**-wwo_bod_slud)*wwo_ch4_efac_tre*ct_ch4_eq;
      let n2o   = wwo_tn_infl*wwo_n2o_efac_tre*ct_n2o_co*ct_n2o_eq;
      let total = co2+ch4+n2o;
      return {total,co2,ch4,n2o};
    }

p.s.: nice work so far with ECAM v3 ;-)

**Comment by holalluis** [comment]
Hi Sebastian, nice to meet you. Thank you for your feedback :) I'll address this issue next Monday

**Comment by holalluis** [comment]
Hi @sebakoe, I've implemented the changes, please check them (https://ecam.icradev.cat/ecam/v3/) and let me know if everything looks ok. Here's a screenshot of the new variable added:
![image](https://user-images.githubusercontent.com/1082644/118544988-50775380-b756-11eb-877b-0a8f92afd0b7.png)

**Comment by sebakoe** [comment]
Hi Lluis, that looks good. The only thing in this regards is now the need for adjusting the description text of _www_bod_infl_ "BOD5 load entering the ~containment before any~ treatment. It can be estimated from the ~population~ BOD5 removed as faecal sludge". 
Then this issue can be closed.

**Comment by holalluis** [comment]
done, thanks!
