### ISSUE TITLE
Onsite: _Effluent BOD load (wwo_bod_effl)_ dropdown menu

### ISSUE THREAD

**Issue by sebakoe** [icra/ecam#358]
_Effluent BOD load (wwo_bod_effl)_ still refers to containments in its dropdown menu, but it should refer to the treatment like _Effluent BOD5 load (wwt_bod_effl)_ in the wastewater treatment section.

**Comment by holalluis** [comment]
Dear Sebastian, which options should have the dropdown menu for _wwo_bod_effl_? Thank you

**Comment by holalluis** [comment]
I'm using this table from IPCC:
![image](https://user-images.githubusercontent.com/1082644/118332588-9b9d2680-b50a-11eb-90e1-3c48b9b7e5a2.png)
https://ecam.icradev.cat/ecam/v3/frontend/docs/2019-ipcc/5_Volume5/19R_V5_6_Ch06_Wastewater.pdf#page=28

![image](https://user-images.githubusercontent.com/1082644/118332860-03ec0800-b50b-11eb-86da-030bb85f3cf3.png)

**Comment by sebakoe** [comment]
Lluis, thanks for your reply. 
I just saw (and interpret) that the IPCC is basically refering to supernatant/overflow from the containments. So we can and should keep that dropdown menu as it is, but change the name into _Effluent BOD5 load (containment)_, and add a fitting description - to avoid confusion.

Furthermore since we are having treatment of faecal sludge also in Onsite, we should have a seperate _Effluent BOD5 load (treatment)_, which than should have a dropdown list like wastewater treatment (the first 4 options in the list from IPCC), because a faecal sludge treatment plant works in some sense like a wastewater treatement plant. The calculation/estimation of _Effluent BOD5 load (treatment)_ should then of course be based on the Influent BOD5 load for faecal sludge treatment. This depends on how [issue #357 ](https://github.com/icra/ecam/issues/357) will be solved.

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/119549498-92784900-bd97-11eb-84e5-655bff061088.png)

![image](https://user-images.githubusercontent.com/1082644/119549536-9a37ed80-bd97-11eb-98fb-8f22c9c4d55f.png)

Hi I did the changes, is this ok now? thanks!

**Comment by sebakoe** [comment]
I'll look at it latest tomorrow morning

**Comment by sebakoe** [comment]
looks good
