### ISSUE TITLE
Summary Table | Rearrange order of "emission source"

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#362]
Hey Lluis, could you please rearrange the order of the "Emission sources"?

Currently, it looks like this:
![image](https://user-images.githubusercontent.com/45791540/119018749-b7864980-b99c-11eb-834c-77a900a6b3c6.png)

It makes more sense to rearrange it to:

**Collection**
- Electricity (indirect)
- Fuel engines
- Generation in sewers
- Discharge to water body (untreated)

**Treatment:**
- Electricity (indirect)
- Fuel engines
- Fuel (digester)
- Treatment process
- Sludge management
- Biogas
- Discharged water
- Truck transport of reused water

**Onsite:**
- Electricity (indirect)
- Fuel engines
- Fuel (digester)
- Containment
- Treatment process
- Biogas
- Effluent discharge
- Truck transport of faecal sludge
- Dumping
- Land Application
- Landfilling
- Open defecation
- Urine application

**Comment by holalluis** [comment]
done please check

**Comment by ElaChe00** [comment]
Okay. Order is better! Thanks.

I will close this issue...but might open another one regarding appearange of the table. I think there is still room for improvement. The different elements are still very small and difficult to read
