### ISSUE TITLE
hide "zero valued" fields in results and compare assessments

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#363]
![image](https://user-images.githubusercontent.com/1082644/119716010-f288f100-be64-11eb-9610-7c27149e0574.png)
![image](https://user-images.githubusercontent.com/1082644/119716072-ff0d4980-be64-11eb-9eb0-8e089a81a3a5.png)
done, please @ElaChe00 check

**Comment by ElaChe00** [comment]
Nice! One question: this function currently does not apply to the summary does it?
![image](https://user-images.githubusercontent.com/45791540/119976950-1f015200-bfb8-11eb-9617-0f9895696abf.png)

**Comment by holalluis** [comment]
Yes, sorry, I forgot to add it in the summary, I will add it

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/120015328-841e6d00-bfe3-11eb-94f9-c863d946c4ef.png)
done, please check

**Comment by ElaChe00** [comment]
Great! Looks good. Another question: Is there a particular reason why the width of the columns change?

If you hide the zeros, the columns are narrower?

![image](https://user-images.githubusercontent.com/45791540/120230788-5ab64900-c250-11eb-872c-6fed4f792b2d.png)

![image](https://user-images.githubusercontent.com/45791540/120230807-60ac2a00-c250-11eb-9a8c-0a4017940f20.png)

**Comment by holalluis** [comment]
This is because some long descriptions of the variables disappear, since they are all 0. Then, the table readapts the size. If you want I can set the table width to a fixed % of the width of the window

**Comment by ElaChe00** [comment]
Yes, I would prefer this. Please make a fixed % of the width of the window

**Comment by holalluis** [comment]
I've set the width of the table as the 100% of the available space, please check
