### ISSUE TITLE
population table could cause confusion

### ISSUE THREAD

**Issue by sebakoe** [icra/ecam#365]
The population table on the right side could cause confusion. It should be clear that _Serviced Population_ is actually a part of _Population connected to sewers_ and not additional. Maybe through an indent or renaming it, e.g. _Serviced population connected to sewers_.

![image](https://user-images.githubusercontent.com/84188310/119954262-194b4280-bf9f-11eb-814e-f5dab9500b45.png)

e.g.

Population connected to sewers | 362,252
 -- thereof serviced population | 253,576
Population with onsite treatment | 859,752

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/120013151-b084ba00-bfe0-11eb-875a-6d48a37daaed.png)

Hi, I've added an arrow to indicate this. Thank you
