### ISSUE TITLE
Onsite: Order

### ISSUE THREAD

**Issue by sebakoe** [icra/ecam#366]
I think it would be good to adjust the order, so that is inline with the filters and also how you would normally proceed with the assessment. It would also be good to have the options directly after the mandatory fields.

1. population with onsite sanitation system (I would also rename _Population with onsite treatment_ into _Population with onsite sanitation systems_
2. containment + transport (--> Evaluate transport of faecal sludge should also come when using the fiilter "Containment")
3. treatment
4. disposal / end-use
5. OD
6. Energy performance

![image](https://user-images.githubusercontent.com/84188310/119957909-cd020180-bfa2-11eb-8bed-d370308b73f9.png)
![image](https://user-images.githubusercontent.com/84188310/119959555-64b41f80-bfa4-11eb-8f2f-6be7b16810f7.png)

**Comment by holalluis** [comment]
thank you, I've changed it, you can check it here https://ecam.icradev.cat/ please, let me know if is ok now
