### ISSUE TITLE
Filters somehow contra intuitive

### ISSUE THREAD

**Issue by sebakoe** [icra/ecam#367]
For me the input filters are not so intuitive, because due to their square form they suggests being "multiple choice"  - meaning when klicking on them (the large field including the text) it is rather switching between them, than to choosing all the inputs you want. (I know when klicking within the square you can choose multiple inputs - but for that you have to be very precise)

![image](https://user-images.githubusercontent.com/84188310/119965407-84e6dd00-bfaa-11eb-9414-9f6988c04940.png)

**My suggestion is:** multiple selection of the input filters, by klicking on the large field including the text - or alternatively using STRG or SHIFT to enable multiselect

**Comment by holalluis** [comment]
There is a meditated reason for being like this. Most of the time you just want to change category, so you click the big square that switches category (1 click), like normal tabs. Only a few times you will want to combine categories, then you just click the little checkboxes, this way you get the best functionality of both (tabs and checkboxes)
