### ISSUE TITLE
Add to FAQ |  "How do I start an assessment?"

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#368]
**"How do I start an assessment?"**

1. Click on "Start your assessment".
2. Choose a name for your assessment e.g. "Utility X 2020".
3. Select the assessment period. This input will be the basis for the calculations.
4. Select the country the utility is located in.
5. If needed, adapt values of emission factor for grid electricity, annual protein consumption per capita or BOD5 generation.
6. Click on "Access inventory" to insert your input data

![How to start an assessment](https://user-images.githubusercontent.com/45791540/120164512-f1f0b180-c1fa-11eb-9c4f-68a0c8887e0e.gif)

**Comment by holalluis** [comment]
done, please check

**Comment by ElaChe00** [comment]
Looks good. A minor request. Could you please increase the spacing between the lines?
![image](https://user-images.githubusercontent.com/45791540/120231059-df08cc00-c250-11eb-9fd0-82b12bb90147.png)

The lines are really close to each other, making it hard to read them.

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/120232191-55a6c900-c253-11eb-9338-ea32c9ebb9e5.png)

Now with 10px separation between steps.

The problem of increasing the size of the animation is that it looks pixelated because it is already 100% of its original size.

**Comment by ElaChe00** [comment]
Okay, no problem! That's good to know. I will generate animations that will be bigger. Will keep this issue open until I have produced a new one :)

**Comment by ElaChe00** [comment]
Hey Lluis, check this out. This file should be larger :
![How-to-start-an-assessment](https://user-images.githubusercontent.com/45791540/120324614-1d50ca80-c2e7-11eb-9d03-8f5c24dcaf96.gif)

**Comment by holalluis** [comment]
done, please check
