### ISSUE TITLE
"Potabilization chain" still not clear

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#369]
Dear Lluis, please add the information regarding the abbreviations. I cannot find them here:
![image](https://user-images.githubusercontent.com/45791540/120165532-f79ac700-c1fb-11eb-9c67-f96e83fd26ea.png)

nor here: 
![image](https://user-images.githubusercontent.com/45791540/120165572-008b9880-c1fc-11eb-852d-b6e7a3efa2d5.png)

**When you hover over the field:**
![image](https://user-images.githubusercontent.com/45791540/120165634-0da88780-c1fc-11eb-8dae-31be099586a3.png)

There should be an explaination:

-	Pre-oxidation (Pre-ox)
-	Coagulation (C)
-	Filtration (F)       
-	Sedimentation (S)
-	Filtration (Filt)
-	Desinfection (Des)

**Comment by holalluis** [comment]
Dear Elaine, Filtration appears 2 times "F" and "Filt"

**Comment by ElaChe00** [comment]
I am a little bit confused myself. It might be "Flocculation". I followed the information in the inception reports.

There were probrably errors in the ECAM inception reports (see attached page 74)
[2015 ECAM Inception Report.pdf](https://github.com/icra/ecam/files/6571851/2015.ECAM.Inception.Report.pdf)

Or in the report below page 19. 
[2015 ECAM Concept.pdf]
(https://github.com/icra/ecam/files/6571859/2015.ECAM.Concept.pdf)

**Comment by holalluis** [comment]
Ok, I've added the descriptions below the name of the variable
![image](https://user-images.githubusercontent.com/1082644/120232016-f052d800-c252-11eb-903e-9cfaa2a9ab89.png)

Maybe we could contact some creator of the original spreadsheets, to see if we can confirm these abbreviations. In the meantime we can leave this issue open

**Comment by ElaChe00** [comment]
But we haven't solved the issue with the 2 F's yet.

Let's ask LLuis Corominas later.

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/120346627-d6210480-c2fb-11eb-9b03-4f896fc8d35f.png)
