### ISSUE TITLE
Inventory "Treatment" - Why is there sludge?

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#370]
Dear Lluis,

I came across this field:
![image](https://user-images.githubusercontent.com/45791540/120166306-bbb43180-c1fc-11eb-8a8c-4faf09b40188.png)

Why is there sludge? Shouldn't this go into "WW Treatment"?

**Comment by ElaChe00** [comment]
As discussed, please remove sludge

**Comment by holalluis** [comment]
done, please check
