### ISSUE TITLE
Add to FAQ | "Who should use ECAM?"

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#373]
**Who should use ECAM?**

ECAM is meant for water and wastewater utility managers, technicians, consultants, climate change experts, academics and policy makers working on issues regarding water, energy and climate change. ECAM may be used by anyone who is interested in assessing an utility's energy performance and greenhouse gas emissions to identify areas of improvement.

**Comment by holalluis** [comment]
done, please check
