### ISSUE TITLE
Add to FAQ | "Do all energy sources result in carbon emissions?"

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#376]
**Do all energy sources result in carbon emissions?**

No. Renewable sources of electricity such as hydropower, wind and solar are carbon-free. The emission factor for grid electricity measures the kilograms (kg) of carbon dioxide (CO2) emitted per kWh of electricity generated from fossil fuels per IPCC guideline (2006). The emission factors for electricity delivered to customers from a mix of generation sources usually take into account the average annual contribution of the different sources (from fossil fuels and renewables).

**Comment by holalluis** [comment]
done, please check
