### ISSUE TITLE
Add to FAQ | "What are Climate-Carbon Feedbacks (CCF)?"

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#377]
**What are 'Climate-Carbon Feedbacks' (CCF)?**

The **C**limate-**C**arbon **F**eedback (CCF) refers to the effect that a changing climate has on the carbon cycle, which impacts atmospheric CO2 and turn changes the climate further. In concrete terms: when CO2 is emitted, the atmospheric CO2
pool increases. A fraction of this excess atmospheric CO2 is taken up by the ocean and the terrestrial biosphere (the “carbon sinks”), but as long as a part of the excess CO2 stays in the atmosphere, it warms the climate. In turn, this warming climate slows down the uptake of the atmospheric CO2 by the sinks. This slowing-down constitutes a positive feedback – i.e. a warming climate is warmed further through the feedback ([Ciais et al., 2013](https://www.researchgate.net/publication/340503493_Carbon_and_Other_Biogeochemical_Cycles)).

**Comment by holalluis** [comment]
done, please check

**Comment by ElaChe00** [comment]
Currently the source appears twice.
![image](https://user-images.githubusercontent.com/45791540/120276106-9255dd00-c2b2-11eb-95d4-abfd3b57d6ae.png)

I think it is sufficient to mention it once.

**Comment by holalluis** [comment]
done, please check
