### ISSUE TITLE
Add to FAQ | "What is ECAM?"

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#378]
**What is ECAM?**

The “**E**nergy Performance and **C**arbon Emissions **A**ssessment and **M**onitoring Tool” (**ECAM**) offers unique capabilities for assessing greenhouse gas emissions and energy consumption at a system-wide level. Gain greater insights by identifying areas to reduce greenhouse gas emissions, increase energy savings and improve overall efficiencies to reduce costs.

ECAM was developed by the Catalan Institute for Water Research (ICRA) within the scope of the project “Water and Wastewater Companies for Climate Mitigation” (WaCCliM), a joint initiative between the Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) GmbH and the International Water Association (IWA). WaCCliM is part of the International Climate Initiative (IKI). The German Federal Ministry for the Environment, Nature Conservation and Nuclear Safety (BMU) supports this initiative on the basis of a decision adopted by the German Bundestag.

**Comment by holalluis** [comment]
done, please check
