### ISSUE TITLE
Add to FAQ | "What is biogas valorisation?"

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#379]
**What is biogas valorisation?**

Biogas consists primarily of methane (CH4; typically between 50-75%) and carbon dioxide (CO2). These gases are produced during anaerobic digestion; the formula below shows the chemical reaction that takes place in an anaerobic digester:

C6H12O6 → 3CO2 + 3CH4

The released gases can be used as fuel. With gas engines, the biogas can be converted to electricity and heat, so that the wastewater treatment plant can produce its own energy. This process is called **biogas valorisation**; it is the transformation of biomass to valuable materials and energy. Throughout this process it is possible to create energy neutral or even energy friendly wastewater treatment facilities.

**Comment by holalluis** [comment]
done, please check

**Comment by ElaChe00** [comment]
Currently it looks like this:
![image](https://user-images.githubusercontent.com/45791540/120277046-d0073580-c2b3-11eb-869c-e053d3c2e972.png)
.
.
.
.
.
**It should look like this:**

![image](https://user-images.githubusercontent.com/45791540/120276974-b82fb180-c2b3-11eb-94b4-4d55b05d7768.png)

**Comment by holalluis** [comment]
done, please check
