### ISSUE TITLE
Add to FAQ | "What is an ‘Emission Factor’" (EF)?

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#380]
**What is an ‘Emission Factor' (EF)?**

The emission factor is a coefficient to convert e.g. the consumption of grid electricity into GHG emissions (kgCO2/kWh), which will be associated with each unit of electricity provided by an electricity system. It is a parameter to determine the baseline emissions.

**Comment by holalluis** [comment]
done, please check
