### ISSUE TITLE
Replace "UNFCCC Category" with "IPCC Category"

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#385]
Focus of June 2021

**Comment by holalluis** [comment]
reference: https://ecam.icradev.cat/ecam/v3/frontend/docs/2019-ipcc/1_Volume1/19R_V1_Ch08_Reporting_Guidance.pdf#page=9

**Comment by holalluis** [comment]
https://ecam.icradev.cat/ecam/v3/backend/ipcc_categories.js this file list all ecam emissions and all IPCC categories (work in progress)

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/121936908-6a528900-cd4a-11eb-8c3b-ae604a65cda5.png)

**Comment by holalluis** [comment]
view created and charts restored
![image](https://user-images.githubusercontent.com/1082644/121950614-29627080-cd5a-11eb-877e-4d470087f60e.png)

**Comment by ElaChe00** [comment]
Could be a point for discussion.

**Comment by ElaChe00** [comment]
Hey @holalluis , please hide the **"GHG emissions by IPCC category"** "for now". 

We are also hiding the categories under **More**. Let's add this back once we have discussed it. Thanks.

![image](https://user-images.githubusercontent.com/45791540/122966695-e6bc1c00-d389-11eb-824f-87db3dd51775.png)

**Comment by holalluis** [comment]
OK, It's hidden

**Comment by holalluis** [comment]
moved to #467
