### ISSUE TITLE
ECAM 3.0 slow down?

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#386]
Dear Lluis, there is something I have noticed only starting from today. It takes several mili seconds before a button reacts to a click. Is it only my computer or do you encounter the same issue)

**Comment by ElaChe00** [comment]
I restarted my computer, and now it seems to work better. Have you encountered this before? @holalluis

**Comment by holalluis** [comment]
I've never faced this, although keep in mind that in the meantime the library that renders the graphic interface (called Vue) is in development mode. This gives advices when errors occur. Is possible that when I turn the library to production mode goes faster. Do you still experience some slowdown after restarting ?
![image](https://user-images.githubusercontent.com/1082644/120490050-60c73980-c3b8-11eb-8994-38d4d2a9e85c.png)

**Comment by ElaChe00** [comment]
No, I only encountered it once. Might have been due to my computer. Probably was an issue of my laptop!
