### ISSUE TITLE
landing icon includes text in english

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#392]
![image](https://user-images.githubusercontent.com/1082644/120840865-0cb08680-c56b-11eb-9363-6e337dfc900e.png)

@ElaChe00 can we have an image without text? This is in order to avoid having a different image for every language

**Comment by ElaChe00** [comment]
Sure! its possible. I will need to send it via email, since SVG is not supported

**Comment by holalluis** [comment]
thanks! received
