### ISSUE TITLE
Add Button "Print Report"

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#405]
Instead of short-key tip, please add a "Print Report" Button.

![image](https://user-images.githubusercontent.com/45791540/121691227-0d936c00-cac7-11eb-8a4d-b301bba61543.png)

**Comment by holalluis** [comment]
done please check
![image](https://user-images.githubusercontent.com/1082644/121708338-c06bc600-cad7-11eb-97fa-23e58d134263.png)

**Comment by ElaChe00** [comment]
Great!!
