### ISSUE TITLE
Compare Assessments | Total energy consumtion - add variation

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#406]
Hey Lluis, please add the same graph (in yellow) for the variation (in %) as in Total GHG emissions.

![image](https://user-images.githubusercontent.com/45791540/121691370-39165680-cac7-11eb-8a66-19154e0e19a6.png)

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/121705467-f0fe3080-cad4-11eb-9b3b-7a7e6a493e63.png)
done please check

**Comment by ElaChe00** [comment]
Yes! perfect.
