### ISSUE TITLE
FAQ - General Questions & ECAM-related Questions

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#408]
Hey Lluis,

can we split this section into two parts?
![image](https://user-images.githubusercontent.com/45791540/121707052-7d5d2300-cad6-11eb-8e40-47d4092d1b74.png)

One called "General Questions" and one called "ECAM-related" Questions.

**Comment by holalluis** [comment]
which questions would go under each category?

**Comment by holalluis** [comment]
I've sorted them like this: let me know if it's ok
![image](https://user-images.githubusercontent.com/1082644/121735433-69291e00-caf6-11eb-801d-0d5381eef99c.png)

**Comment by ElaChe00** [comment]
Yes, this is good for now!

I am wondering if we should sort the order according to a system? not sure here. But minor. Can be changed another time. I will continue to add more GIFs.
