### ISSUE TITLE
calculation of wwo_fslu_emp seems incorrect

### ISSUE THREAD

**Issue by sebakoe** [icra/ecam#411]
I am concerned that the following equation to estimate _wwo_fslu_emp_ might not be complete since the units do not result in the needed m³. Right now they result in days*m³/kg. I think the BOD generation per person per day _BOD_pDay_ is missing in this formular. (or instead of the population and the days _wwo_bod_cont_ could be used which reflects the BOD generation over the assessment period).

Can you reference where the factor 0.3 comes from?

![grafik](https://user-images.githubusercontent.com/84188310/121801829-b19d2480-cc39-11eb-9846-b0a7991818c8.png)

**Comment by holalluis** [comment]
0.3 is kg/person/day, I'll modify the code to reflect this. Thanks

**Comment by holalluis** [comment]
done, 
![image](https://user-images.githubusercontent.com/1082644/121913208-7c73fd80-cd31-11eb-850e-ebcfd4c228b3.png)
