### ISSUE TITLE
Configuration?

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#412]
Hey lluis, I am not sure what this is or why this was included:
![image](https://user-images.githubusercontent.com/45791540/121859783-6d248e00-ccf8-11eb-98e5-e38160f0df26.png)

For the last, if the default is one, why doesn't it say 1.1 then?
For the other fields, it's not really clear what to fill in. I wouldn't add to many more input fields where no one really knows what to insert

**Comment by holalluis** [comment]
Hi Elaine, I see a bug here, for new assessments those values have a default value, but now I see that for loaded files they are undefined, I'll solve this

**Comment by holalluis** [comment]
BTW this was included bc of a petition from a mail that was called "feedback from Peru", they asked for the ability to change those values, before they were constants

**Comment by holalluis** [comment]
Maybe I'll include the reference (the exact page and table from IPCC where these values come from)

**Comment by holalluis** [comment]
Dear Elaine, I've included links with all the references for every variable
![image](https://user-images.githubusercontent.com/1082644/121934769-029b3e80-cd48-11eb-831f-6a20c41e6330.png)

**Comment by ElaChe00** [comment]
Yes! Now it makes sense. But can you remove the parameter names please?
![image](https://user-images.githubusercontent.com/45791540/122007016-ce5f6680-cdb7-11eb-8f91-647767a25138.png)

Or are they necessary for some reason?

**Comment by holalluis** [comment]
done, please check
