### ISSUE TITLE
Unify spelling of GitHub

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#418]
hey Lluis, is there an easy and fast way to unify the spelling?

Just realized it is spelled **GitHub** and nit github...

We definitely need to adapt it on the landing page:
![image](https://user-images.githubusercontent.com/45791540/122014829-d8856300-cdbf-11eb-8f7d-9054f857d5c0.png)

**Comment by holalluis** [comment]
I did a quick search over all the files and changed "github" to "GitHub"
