### ISSUE TITLE
Rearrange "More" page

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#419]
Hey Lluis, 

please rearrange the buttons of the "More" page.

![image](https://user-images.githubusercontent.com/45791540/122018939-9bbb6b00-cdc3-11eb-9ad6-76a55ffaaa1c.png)

### New order:

Left column:
- About ECAM                
- Flow Diagram              
- Equations                     
- Data tables                   
- Documentation            

Right column:
- FAQs
- Non revenue water
- Constants
- Benchmarks

I would remove IPCC categories (for now)

**Comment by holalluis** [comment]
done please check (ipcc button only visible if DEV MODE is enabled)
