### ISSUE TITLE
"About ECAM" - Adapt title and add FAQs button

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#420]
Hey Lluis, please adapt the name from "About" to "About ECAM" in the headline:
![image](https://user-images.githubusercontent.com/45791540/122021230-c73f5500-cdc5-11eb-97d3-b1b498800b23.png)

.
.
.
.
.

.

Further, please include a big button FAQs Button here:
![image](https://user-images.githubusercontent.com/45791540/122021484-fd7cd480-cdc5-11eb-863a-1aaadb10bbdc.png)

.
.
![image](https://user-images.githubusercontent.com/45791540/122021738-3fa61600-cdc6-11eb-8644-25aae7416f82.png)

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/122047319-4b9ed180-cde0-11eb-8b94-7ffa2798d4aa.png)
done please check
