### ISSUE TITLE
FAQ | What happened to the "Feacal Sludge Management" component?

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#423]
**What happened to the "Feacal Sludge Management" component?**

Users who worked with the feacal sludge management (FSM) component in ECAM 2.2 might have realized that we have applied major changes here. Now, FSM falls under "**Onsite sanitation**". The inputs almost completely remained the same.

![image](https://user-images.githubusercontent.com/45791540/122033817-30789580-cdd1-11eb-9ea9-a0ddfcd0ed49.png)

**Comment by holalluis** [comment]
done, please check
