### ISSUE TITLE
FAQ | What is new in ECAM 3.0 compared to ECAM 2.2?

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#424]
In this part, I would include some screenshots. I will probably add more information later ......(it's too much to compile for today).

Please insert all the text and pictures below under the question **"What's new in ECAM 3.0?"**

### **Modified user interface**
The reason why we have changed the user interface was to make ECAM more **user-friendly** and **easy-to-use.** To achieve this, there are some major changes that have been applied to the user interface of ECAM:
- **Landing page**: From here, you can easily "Start your assessment" to evaluate your utility's energy performance or CO2 footprint. Further, you can activiate "Tips  for new users" include pop-ups that gudie you through the tool. The new navigation bar is placed on the top and includes the pages: **Configuration**, **Inventory**, **Results**, **Compare assessments** and **More**.

![image](https://user-images.githubusercontent.com/45791540/122024708-f7d4be00-cdc8-11eb-9ffd-c1d638bdc397.png)

- **Configuration**: One of the biggest changes that we applied to ECAM is the possibility to manage and edit several assessments in the tool. Until now, when you started assessing the greenhouse gas emissions or energy consumption of your utility in ECAM 2.2, the tool only allowed you to make one assessment at a time. Hence, only one assessment could be saved in a JSON file. 
 
Now, to make things easier and more compact, the updated ECAM version allows the users to edit more than one assessment or save numerous assessments in one JSON file. 

![image](https://user-images.githubusercontent.com/45791540/122030818-623c2d00-cdce-11eb-9150-ffc206e3ae92.png)

In addition, you can load a saved JSON file to continue your assessment or you can merge different json files into one file by using the button "Append to current list"

![image](https://user-images.githubusercontent.com/45791540/122031047-9b749d00-cdce-11eb-9295-e74945ae6cfa.png)

Another novelty is the function "Load assessment from Excel file". 
Steps: 
1) Download ECAM input template.
2) Fill out template file.
3) Upload filled file.

### **Urban water cycle stages**
- **Inventory**: To evaluate your CO2 footprint or energy performance, you must insert the required input data for the systems (**Water supply** and **Sanitation**) and respective stages (**Abstraction**, **Treatment**, **Distribution**, **Collection**, **Treatment**, **Onsite sanitation**) that you would like to assess.

![image](https://user-images.githubusercontent.com/45791540/122032443-eba02f00-cdcf-11eb-82ff-29566dee84cf.png)

### **Compare assessments**
The option "Compare assessments" allows the user to compare assessments of different time periods or different utilities. You can visualize the greenhouse gas emissions and energy consumption in different ways:
- Overview of inputs & outputs
- Total GHG emissions
- Emissions by gas (CO2, N2O, CH4)
- Emissions by stage in bar charts
- Emissions by IPCC category
- Total energy consumption

### **Reporting function**
You can download the **assessment that you are **currently editing**** as PDF. You just have to click on "**Results**" in the navigation bar and select "**Report**". This report includes all the inputs and outputs as well as diagrams of your assessment.
![image](https://user-images.githubusercontent.com/45791540/122065358-2adf7780-cdf2-11eb-9e1c-1a350e579e2b.png)

**Comment by holalluis** [comment]
done please check

**Comment by ElaChe00** [comment]
Okay, can you rename it to: "**What's new in ECAM 3.0?**"

**Comment by ElaChe00** [comment]
Please adapt all the text and pictures below under the question **"What's new in ECAM 3.0?"**

### **Modified user interface**
The reason why we have changed the user interface was to make ECAM more **user-friendly** and **easy-to-use.**
To achieve this, there are some major changes that have been applied to the user interface of ECAM:
- **Landing page**: From here, you can easily "Start your assessment" to evaluate your utility's energy performance or CO2 footprint. Further, you can activate "Tips  for new users" to include pop-ups that guide you through the tool. The new navigation bar is placed on the top and includes the pages: **Configuration**, **Inventory**, **Results**, **Compare assessments** and **More**.

![image](https://user-images.githubusercontent.com/45791540/122024708-f7d4be00-cdc8-11eb-9ffd-c1d638bdc397.png)


- **Configuration**: One of the biggest changes that we applied to ECAM is the possibility to manage and edit several assessments in the tool. Until now, when you started assessing the greenhouse gas emissions or energy consumption of your utility in ECAM 2.2, the tool only allowed you to make one assessment at a time. Hence, only one assessment could be saved in a JSON file. 
 
Now, to make things easier and more compact, the updated ECAM version allows the users to edit more than one assessment or save numerous assessments in one JSON file. 

![image](https://user-images.githubusercontent.com/45791540/122030818-623c2d00-cdce-11eb-9150-ffc206e3ae92.png)

In addition, you can load a saved JSON file to continue your assessment or you can merge different JSON files into one file by using the button "Append to current list"

![image](https://user-images.githubusercontent.com/45791540/122031047-9b749d00-cdce-11eb-9295-e74945ae6cfa.png)

Another novelty is the function "Load assessment from Excel file". 
Steps: 
1) Download ECAM input template.
2) Fill out template file.
3) Upload filled file.


### **Urban water cycle stages**
- **Inventory**: To evaluate your CO2 footprint or energy performance, you must insert the required input data for the systems (**Water supply** and **Sanitation**) and respective stages (**Abstraction**, **Treatment**, **Distribution**, **Collection**, **Treatment**, **Onsite sanitation**) that you would like to assess.

![image](https://user-images.githubusercontent.com/45791540/122032443-eba02f00-cdcf-11eb-82ff-29566dee84cf.png)

- **Feacal sludge management:** Users who worked with the feacal sludge management (FSM) component in ECAM 2.2 might have realized that we have applied major changes here. Now, FSM falls under "Onsite sanitation". The inputs almost completely remained the same.


### **Compare assessments**
The option "Compare assessments" allows the user to compare assessments of different time periods or different utilities. You can visualize the greenhouse gas emissions and energy consumption in different ways:

- **Total GHG emissions**
![image](https://user-images.githubusercontent.com/45791540/122194162-79921d80-ce95-11eb-82ac-0c06f8428784.png)
![image](https://user-images.githubusercontent.com/45791540/122195840-fe316b80-ce96-11eb-93bc-d26c695ba064.png)

- **Emissions by gas (CO2, N2O, CH4)**
![image](https://user-images.githubusercontent.com/45791540/122194970-397f6a80-ce96-11eb-8562-a1572e40efcb.png)

- **Emissions by stage in bar charts**
![image](https://user-images.githubusercontent.com/45791540/122195201-6e8bbd00-ce96-11eb-94ca-29412b11f8b3.png)

- **Emissions by IPCC category**
![image](https://user-images.githubusercontent.com/45791540/122194768-05a44500-ce96-11eb-8472-83a8445327c7.png)

- **Total energy consumption**
![image](https://user-images.githubusercontent.com/45791540/122194825-15238e00-ce96-11eb-9a2e-c2839ab6f8ad.png)


### **Reporting function**
You can download the **assessment that you are **currently editing**** as PDF. You just have to click on "**Results**" in the navigation bar and select "**Report**". This report includes all the inputs and outputs as well as diagrams of your assessment. This way you will always be able to understand or reconstruct assessment of the past.
![image](https://user-images.githubusercontent.com/45791540/122065358-2adf7780-cdf2-11eb-9e1c-1a350e579e2b.png)

Use the **sankey diagram** to visualize the emission flow path:
![image](https://user-images.githubusercontent.com/45791540/122197667-b7447580-ce98-11eb-85b3-d45c6448232a.png)

### **2019 Refinement to the 2006 IPCC Guidelines for National Greenhouse Gas Inventories**
The world has committed to reducing greenhouse gas emissions to tackle climate change. IPCC's inventory guidelines enable all countries to estimate levels and trends of greenhouse gas emissions. Even though the IPCC Guidelines were first published in 2006, they continue to provide a technically sound methodolgical basis for preparing national greenhouse gas inventories. The 2019 Refinement updates and supplements the 2006 IPCC Guidelines.
ECAM 3.0 takes into account emission factors and other parameters that have been updated in the 2019 Refinement. Notable changes can be found in the guidance on CH4 and N2O emissions from wastewater.


### **Programming language**
Now, ECAM 3.0 is 100% JavaScript. Previous PHP codes were replaced so that the tool can run 100% in the browser, without needing server or storing information.  This way, any web server program will work (e.g. Apache, Nginx).

**Comment by holalluis** [comment]
done please check. I've tuned a little bit the "programming language" fragment :)

**Comment by ElaChe00** [comment]
hahaha :D Good! I had no idea what i was writing :D
