### ISSUE TITLE
Report | Same width for all fields?

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#426]
![image](https://user-images.githubusercontent.com/45791540/122077252-de009e80-cdfb-11eb-873c-f62a094eea0e.png)

Hey Lluis, is it possible to make the labels the same width? But it looks very messy this way :-/

**Comment by holalluis** [comment]
I'm not sure how it would look when there are more substages, I can try to set the label to a fixed percentage of the width of the screen

**Comment by ElaChe00** [comment]
Is it possible to make the grey fields the same size too AND narrower?

![image](https://user-images.githubusercontent.com/45791540/122189603-59f8f600-ce91-11eb-9ead-8db059cda679.png)

They don't have to be that wide, otherwise it will be tricky, when we have 3 sub stages .

**Comment by holalluis** [comment]
Now they have an automatic sizing. I think this is better than having a fixed width, because every substage can have different number of  substages, here is an example:
![image](https://user-images.githubusercontent.com/1082644/122266116-bed83e80-ced9-11eb-9155-d9325325759f.png)

**Comment by ElaChe00** [comment]
I agree. I like what you did there! Works for me
