### ISSUE TITLE
Change description of wwt_mass_slu & wwt_bod_slud

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#429]
@ElaChe00 

 
![grafik](https://user-images.githubusercontent.com/33861734/122208685-e57b8280-cea3-11eb-961d-227ddd833762.png)
![grafik](https://user-images.githubusercontent.com/33861734/122208712-ef04ea80-cea3-11eb-8fc1-1da68beaada8.png)

Both inputs are relevant for anaerobic and aerobic treatment, the linked equation in IPCC is however only for aerobic systems. I think it would be better to change the description to “BOD5 (organic component) removed from wastewater (in the form of sludge). (Sj in eq. 6.1 IPCC 2019)”

Link to page 17.

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/122264586-fc3bcc80-ced7-11eb-917f-d22d686511c5.png)
thanks!

For the amount of raw sludge I see that there is no "general" equation, isn't it?
