### ISSUE TITLE
Consider implementing country-specific values for F_NON_CON

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#430]
@ElaChe00 

![grafik](https://user-images.githubusercontent.com/33861734/122209215-9255ff80-cea4-11eb-99f6-851bc11e6296.png)

In IPCC this value is country specific. IPCC does not mention a default value.  
 
![grafik](https://user-images.githubusercontent.com/33861734/122209276-a3067580-cea4-11eb-890b-06a019ee7290.png)

**Comment by holalluis** [comment]
Dear Ranjin, in table 6.11 there are default values
![image](https://user-images.githubusercontent.com/1082644/122258756-b24fe800-ced1-11eb-9578-7a659587358d.png)
I took 1.1 but I'm not sure which one should be

**Comment by Ranf16** [comment]
> 
> 
> Dear Ranjin, in table 6.11 there are default values
> ![image](https://user-images.githubusercontent.com/1082644/122258756-b24fe800-ced1-11eb-9578-7a659587358d.png)
> I took 1.1 but I'm not sure which one should be

I didn't see that table, my bad. 1.1 should be correct in this case. Thanks
