### ISSUE TITLE
Missing-inputs bug with wwo_bod_rmvd

### ISSUE THREAD

**Issue by sebakoe** [icra/ecam#437]
Hi Lluis,

when using the estimated value (or any manual value) for _wwo_bod_rmvd_ (instead of the dropdown list) the input field for _wwo_bod_rmvd_ will be hidden after switching to another (sub) stage and back and ~Missing_inputs occurs in the output field for _wwo_KPI_GHG_containment_

The same problem occurs with _wwo_bod_effl_. This bug is probably caused by ignoring the dropdown list for each variable.

I have anyway some concerns with the dropdown list of _wwo_bod_rmvd_, which I understand is based on Equation 6.3D (NEW) and Table 6.6B of the 2019 IPCC revision. But this equation and table are referring to the BOD removed from the systems through the effluent, not through the desludging. (Until now, effluent from containments now not considered in ECAM v3) Because of the decomposition of the organics within the containments and since not all containments might be desludged over the assessment period, I would remove the dropdown list, since I think the estimation based on the volume of faecal sludge emptied and BOD concentration of faecal sludge is appropriate and enough - because both values can be monitored by the utility.

**Comment by holalluis** [comment]
Hi @sebakoe, I'm looking into it, thanks

**Comment by holalluis** [comment]
Hi @sebakoe the bug has been solved and the dropdown menu for wwo_bod_rmvd has been removed, let me know if it works for you. 
![image](https://user-images.githubusercontent.com/1082644/123865800-a5e57980-d92c-11eb-8cdb-6438a7fafede.png)
thanks!

**Comment by sebakoe** [comment]
Thanks @holalluis, it looks good and nice of implementing the "custom value" in the dropdown list, this seems to work well
