### ISSUE TITLE
Tip | List of assessments

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#438]
Hey @holalluis , please adapt the text of this tip:
![image](https://user-images.githubusercontent.com/45791540/122540872-58623600-d029-11eb-904e-1589a3fb8774.png)
 to:

**Tip: List of assessments**
Below you can see the list of assessments. You can only edit one assessment at a time. Click on the assessment that you would like to edit. It will turn blue once you have selected it. If you want to unfold country specific information, click on the assessment again or on the button "settings".

**Comment by holalluis** [comment]
done, please check
