### ISSUE TITLE
Tip | Duplicate assessment

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#440]
This tip should go here:
![image](https://user-images.githubusercontent.com/45791540/122552875-28219400-d037-11eb-9800-b5702e8262f7.png)

**Tip: Duplicate assessment**
You can duplicate an assesment by clicking on the button above. You can use this feature if you want to create multiple assessments where the majority of inputs remain the same, but only a few of the inputs need to the adapted.

**Comment by holalluis** [comment]
done, please check
