### ISSUE TITLE
Tip | Highlight mode

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#441]
This one goes to Inventory

![image](https://user-images.githubusercontent.com/45791540/122557976-c9134d80-d03d-11eb-93bb-a16f48bacfba.png)

**Tip: Highlight mode**
Activate the "Highlight mode" and hover over the outputs to see which inputs are required for the calculation and vice versa.

**Comment by holalluis** [comment]
done, please check

**Comment by ElaChe00** [comment]
The font colour here is grey.
Can you make it black? Like the others?

![image](https://user-images.githubusercontent.com/45791540/122928555-47d3f780-d36a-11eb-930a-4e67b07c1378.png)

**Comment by holalluis** [comment]
done, I didn't notice, thanks!
