### ISSUE TITLE
Tip under Inventory | Filter function

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#442]
This goes under Inventory and **should appear in every stage**

![image](https://user-images.githubusercontent.com/45791540/122563681-c5cf9000-d044-11eb-98b9-a168ed468f4a.png)

**Tip: Filter function**
Activate the filters by ticking the boxes to select the fields that you would like to assess.

**Comment by holalluis** [comment]
done, please check

**Comment by ElaChe00** [comment]
Looks great. Could you please add the "full-stop" after the sentence.

**Comment by holalluis** [comment]
done
