### ISSUE TITLE
Tip under Inventory | 

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#443]
![image](https://user-images.githubusercontent.com/45791540/122567160-acc8de00-d048-11eb-80d1-906e6ecd3a30.png)

**Tip: Create substage**
Create a substage to insert the data for your assessment.

**Comment by holalluis** [comment]
done, please check

**Comment by ElaChe00** [comment]
Looks great. Could you please add the "full-stop"?

Create a substage to insert the data for your assessment**.**

**Comment by holalluis** [comment]
done
