### ISSUE TITLE
When starting a new assessment the inventory is not empty

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#445]
@ElaChe00 

When I open a new tab and start a new assessment there is already input data in the inventory and hence the emissions are not zero. 

![grafik](https://user-images.githubusercontent.com/33861734/122906316-50203880-d352-11eb-8695-434eccbc8a87.png)

It seems that some energy consumption is present even though I did not enter it. Below is a screenshot from collection stage. In other stages it's the same

![grafik](https://user-images.githubusercontent.com/33861734/122906404-68905300-d352-11eb-8e76-9f520b4edf89.png)

Note: I tried this with Firefox and MS Edge (which is based on Chrome).

**Comment by ElaChe00** [comment]
This is new. @holalluis  : I have checked both versions. The dev. version and ECAM v3. The input data seem to appear in both. Could you please make sure the outputs are zero at the very beginning? Thanks

**Comment by Ranf16** [comment]
by the way, deleting browser cache does not help.

**Comment by ElaChe00** [comment]
My comment was referring to the tips, @Ranf16  + this is another issue.

**Comment by holalluis** [comment]
yes, don't worry, this is default info I put for having quick development cycle (edit code, refresh page to check the changes) in "non-dev" mode all inputs will be at 0

**Comment by holalluis** [comment]
If you want to start a fresh new assessment while we are in dev mode just create a new one from configuration, as a quick solution
