### ISSUE TITLE
ECAM does not open on landing page

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#446]
@ElaChe00 
I guess this will be set up when moving the tool to the final URL but I wanted to mention it nevertheless.

When I open the URL https://ecam.icradev.cat/ecam/v3/ it opens the inventory page displayed below, and not the landing page. 

![grafik](https://user-images.githubusercontent.com/33861734/122906876-e5bbc800-d352-11eb-9641-4c13ae361b42.png)

**Comment by ElaChe00** [comment]
Please empty your cache (for several reasons):

1) You see the old tips.
2) @holalluis is constanlty working on ECAM ! you will need to empty your cache daily.

Regarding your comment. Yes. This is the dev. mode.
![image](https://user-images.githubusercontent.com/45791540/122907320-49de8c00-d353-11eb-95b1-5054cf888baa.png)
 You can also deactivate it.
