### ISSUE TITLE
Background color is not always white

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#447]
@ElaChe00 
In windows I have set up a custom color profile. When I open ECAM now, the background color is not always white but grey. See screenshots.

![grafik](https://user-images.githubusercontent.com/33861734/122950026-6d69fc80-d37c-11eb-8e74-6c3ee17342c6.png)

![grafik](https://user-images.githubusercontent.com/33861734/122950081-778bfb00-d37c-11eb-86c9-734ebb8c4d5f.png)

![grafik](https://user-images.githubusercontent.com/33861734/122950139-82df2680-d37c-11eb-8d2e-8350370472fc.png)

![grafik](https://user-images.githubusercontent.com/33861734/122950210-9094ac00-d37c-11eb-977c-d3bf7b547667.png)

**Comment by holalluis** [comment]
please try now, I've set the background to white instead of default

**Comment by ElaChe00** [comment]
@Ranf16  could you please check? Thanks
 For me everything appears white.

**Comment by Ranf16** [comment]
Yes, now it's white
