### ISSUE TITLE
Report | Order of stages in pie chart 

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#449]
Hey @holalluis , I realized that the colour order of the pie shart is a little bit odd. Water and sanitation are "mixed". Is it possible the have all the WS stages next to each other and all the WW stages next to each other? Rearrangement

![image](https://user-images.githubusercontent.com/45791540/122965743-d6f00800-d388-11eb-98f4-c70d599effe2.png)

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/122994565-e4b58580-d3a8-11eb-8a0c-24b7aa16eee8.png)

I see it like this... maybe the chart library is sorting from big to small number.... I'll check it

**Comment by holalluis** [comment]
I've found that using another library for charts (the same we are using for bar charts) this problem disappears, but we lose the ability to print the numbers in the slices of the pie chart, it would look like this:
![image](https://user-images.githubusercontent.com/1082644/123863457-eb547780-d929-11eb-9a0d-771e4a2af381.png)

Would this be ok?

**Comment by ElaChe00** [comment]
I think it would be better to have the percentages.

**Comment by ElaChe00** [comment]
Okay. go ahead and implement the  new library

**Comment by holalluis** [comment]
good news, I could solve the ordering issue with the first version of pie charts, so no need of changing library, this avoids a great amount of code changed

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/124306774-2a234100-db67-11eb-9d71-0b44b29cadc6.png)
