### ISSUE TITLE
Rename function to "hide zero values"

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#450]
![image](https://user-images.githubusercontent.com/45791540/122966395-8dec8380-d389-11eb-97b9-f3d5e7b9daf3.png)
![image](https://user-images.githubusercontent.com/45791540/122966425-9a70dc00-d389-11eb-8359-457b0c763c05.png)
![image](https://user-images.githubusercontent.com/45791540/122967487-cb9ddc00-d38a-11eb-8b14-bca4956c853b.png)

Hey @holalluis could you please rename this function to:

**Hide zero (0) values in results**

**Comment by holalluis** [comment]
done, please check

**Comment by ElaChe00** [comment]
Please hide it in the Table of the Results too :) Thanks!

![image](https://user-images.githubusercontent.com/45791540/123112343-eb420c80-d43d-11eb-9314-be6b48f35248.png)

**Comment by holalluis** [comment]
done, please chec
