### ISSUE TITLE
Tip | Hide zero (0) values

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#451]
![image](https://user-images.githubusercontent.com/45791540/122966878-2420a980-d38a-11eb-95be-87a5943b0d30.png)

**Tip: Hide zero (0) values**
Enable the box above to hide zero (0) values in the report.

**Comment by holalluis** [comment]
done, please check

**Comment by ElaChe00** [comment]
Please hide it in the Table of the Results too :) Thanks!

![image](https://user-images.githubusercontent.com/45791540/123112343-eb420c80-d43d-11eb-9314-be6b48f35248.png)
