### ISSUE TITLE
More | Scientific Literature

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#452]
Hey @holalluis , please hide the sources by default. It should look like this when you click on Scientific Literature.

![image](https://user-images.githubusercontent.com/45791540/122967660-fd16a780-d38a-11eb-86a8-a22c081226a2.png)

Are we still using the FAO Statistics sheet? We have recently updated our information (see in configuration)
Food and Agriculture Organization of the United Nations (2021): FAOSTAT Database. Therefore, please remove the excel sheet from here.

Further, please adapt the sources accordingly for consistency:

- SYLVIS (2009): The Biosolids Emissions Assessment Model (BEAM).
- Andreoli, C. Sperling, M. & Fernandes, F. (2007): Sludge Treatment and Disposal.
- Snip, L. (2010): Quantifying the Greenhouse Gas Emissions of Waste Water Treatment Plants.
- IPCC (2006 &2019): Guidelines for National GHG Inventories.

**Comment by holalluis** [comment]
done, please check
