### ISSUE TITLE
Tip | Assessment comparison

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#453]
![image](https://user-images.githubusercontent.com/45791540/122985840-f003b380-d39e-11eb-8b64-3b5519504cb7.png)

**Tip | Assessment comparison**
Select the assessments that you would like to compare with each other. Please note that the order of the selection determines the order of the compared assessments. E.g. If you have 3 assessment for the years 2018, 2019 and 2020, you will need to select the assessments in this particular order. If you select 2019, 2020 and 2018, the order would be different.

**Comment by holalluis** [comment]
done, please check
