### ISSUE TITLE
ECAM 3.0 Translation to Spanish should be finalized by July 14.

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#454]
@holalluis : it would be great to finalize the last changes by **July 1** so that our colleagues can start the Spanish translation?

**Comment by holalluis** [comment]
Hi, I think we need to close first the open issues that involve changes in the text, I think we are pretty close

**Comment by ElaChe00** [comment]
We don't have time to delay the translation. Therefore, my colleague Caro will start with the translation and we will share the file for the current state and adjust it afterwards (if further changes occur).

Hope this works for you.

@holalluis

**Comment by ElaChe00** [comment]
Dear @holalluis 
[2. ECAM ES .json.zip](https://github.com/icra/ecam/files/6765835/2.ECAM.ES.json.zip)

attached you can find the “final” Spanish translation file of Caro and Bianca.
Please note that some technical terms are still missing. 

We have discussed them during our last call and would appreciate your support here:
•	Stabilization pond
•	Anaerobic pond
•	Anaerobic lagoon
•	Facultative pond

According to ECAM 2.2: Stabilization pond and Anaerobic pond are the same, so the translation to Spanish would be “Laguna anaeróbica”. According to ECAM 3.0 Anaerobic pond is the same as facultative pond, so the translation again (if we follow ECAM 2.2. logic) would be “Laguna Anaeróbica”. But in the IPCC 2019 Refinement Wastewater treatment and discharge Chapter 6, you can see that the terms refer to different things (you can see in the following picture).
 
![image](https://user-images.githubusercontent.com/45791540/124507088-54763800-ddcd-11eb-96d7-9b34abca8140.png)

How should we proceed here??

**Comment by holalluis** [comment]
Dear Elaine, thanks for the file, I'll add it to ecam. Please keep in mind I'm creating all the new tags for the V3 modifications we've been doing these months.

For the translation I would do the following:
- "pond" : "estanque"
- "lagoon" : "laguna"

**Comment by ElaChe00** [comment]
Hey Lluis, is there a way to access the Spanish Translation now or only via the translation tool?

**Comment by ElaChe00** [comment]
@holalluis  the Spanish version is not on the official website yet (since you do last minute changes on https://ecam.icradev.cat/ 

Should @Ranf16  work with https://ecam.icradev.cat/ for now? Might be better, right?

**Comment by holalluis** [comment]
deployed also in wacclim.org/ecam
