### ISSUE TITLE
Hide inputs of advanced assessment questions that are deactivated

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#455]
@ElaChe00 

The generated report lists predetermined inputs (e.g. power factor, % of biogas flared etc.) from the advanced assessments (evaluate pump efficency, biogas production etc.) even if these advanced assessment are all deactivated in the inventory and the user did not work with these inputs at all. I find this confusing and it makes the report look unnecessarily complex. 

Ideally, only the inputs from advanced assessments that are activated should be shown.

![grafik](https://user-images.githubusercontent.com/33861734/123183757-849b0e00-d492-11eb-93fe-5f5d6e6ff0d8.png)

**Comment by holalluis** [comment]
I've created this new input in the report to solve this issue
![image](https://user-images.githubusercontent.com/1082644/123851391-68c4bb80-d91b-11eb-8f81-54cf87163dce.png)
![image](https://user-images.githubusercontent.com/1082644/123851466-8134d600-d91b-11eb-8252-8894ccfbb71e.png)

**Comment by ElaChe00** [comment]
Hey @holalluis , please change the wording to 

"Hide optional input fields if they are disabled in all substages"

**Comment by holalluis** [comment]
ok, done, please check

**Comment by ElaChe00** [comment]
good! 

I am wondering, if we can think of a solution for "Missing inputs":
![image](https://user-images.githubusercontent.com/45791540/124443738-37664880-dd7e-11eb-909e-6de5af564556.png) 

It could be hidden with the "0's"`?

**Comment by holalluis** [comment]
done, please check: in report and compare scenarios

**Comment by ElaChe00** [comment]
Better! Thanks!
