### ISSUE TITLE
Inputs with many digits are not fully displayed

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#456]
@ElaChe00 
On a normal laptop screen larger numbers don't fit the width of the input cell. Numbers can be still entered but you can't see afterwards the full number that has been entered. 

Can't the width be increased a bit, maybe by reducing the width of the column with the input name?

![grafik](https://user-images.githubusercontent.com/33861734/123222611-63f1a900-d4d0-11eb-9d50-362a1a999e3e.png)
![grafik](https://user-images.githubusercontent.com/33861734/123222819-9e5b4600-d4d0-11eb-8e5b-72ee0fe1952a.png)

**Comment by holalluis** [comment]
I've set a fixed minimum width of 30% of the available space, now at least 14 digits are always visible
![image](https://user-images.githubusercontent.com/1082644/123709027-a3bbe600-d86c-11eb-80c4-e6bf2bc09ec2.png)

**Comment by holalluis** [comment]
please check it to see if we can close the issue
