### ISSUE TITLE
Request: Rename CH4 EF (discharge) answer option / add additonal option for further treatment

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#458]
@ElaChe00 

ECAM can be used to assess a chain of different treatment substages, where the effluent of the first treatment substage is the influent of the second treatment substage etc. 

To relfect this option also in the inputs, I purpose to rename the CH4 emission factor option "Water body undefined (0)"   to "Discharge undefined (0)".

In addition you could also add an additional answer option "No discharge, inflow to further treatment process (substage) (0)" for the CH4 and N2O EFs.

![grafik](https://user-images.githubusercontent.com/33861734/123250381-46c9d400-d4ea-11eb-8fee-aaec94ebc3b2.png)
![grafik](https://user-images.githubusercontent.com/33861734/123250713-ac1dc500-d4ea-11eb-917b-afe9e9ac0942.png)

**Comment by holalluis** [comment]
ok, done
