### ISSUE TITLE
Selection in dropdown menu changes

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#459]
@ElaChe00 
There are some dopdown menus for estimating inputs that actually yield the same number, e.g. in the screenshot below several options are based on 25 or 40 gSS/inhabitant/day. When I select for example the option for trickling filter and go to another stage and come back later, the selection has changed to primary treatment (which has the same value). I think this is confusing for the users even though it does not affect the results

![grafik](https://user-images.githubusercontent.com/33861734/123269980-c31ae200-d4ff-11eb-9e12-5bec3c44b477.png)

**Comment by holalluis** [comment]
Dear Ranjin, we are aware of this bug, it's a duplicated from #360

**Comment by holalluis** [comment]
now it is solved
