### ISSUE TITLE
Missing translations: Units and drop-down menus in the detailed assessment

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#46]
1. The units that contain the words like "person", "day", "year", "BOD removed" are missing the corresponding translation.
2. The drop-down menus in the detailed assessment are still in English only.

**Wastewater Collection Stage:**

![image](https://user-images.githubusercontent.com/33861734/36721549-86725dda-1bab-11e8-8f9d-04a5844bb057.png)

**Wastewater Treatment Stage**

![image](https://user-images.githubusercontent.com/33861734/36722303-74d57f1a-1bad-11e8-9ccf-f9e18233572d.png)
![image](https://user-images.githubusercontent.com/33861734/36722345-92d7970a-1bad-11e8-8d06-7d2c92c85b1f.png)

![image](https://user-images.githubusercontent.com/33861734/36722457-d8360eee-1bad-11e8-9766-2abad3dd9adc.png)

![image](https://user-images.githubusercontent.com/33861734/36721912-7fb961ae-1bac-11e8-86c5-7aa241a53afa.png)

![image](https://user-images.githubusercontent.com/33861734/36721602-aa5bfb3e-1bab-11e8-944e-192b6a2068d6.png)

![image](https://user-images.githubusercontent.com/33861734/36721708-f598daea-1bab-11e8-9727-7339dc984509.png)

![image](https://user-images.githubusercontent.com/33861734/36722501-f6e84d02-1bad-11e8-8402-e163d5f9ca57.png)

**Discharge Stage**
![image](https://user-images.githubusercontent.com/33861734/36721967-a6577012-1bac-11e8-9142-ca1e9a4b64ca.png)

**Water abstraction**

![image](https://user-images.githubusercontent.com/33861734/36722573-29f13b00-1bae-11e8-9ecc-bbd005475c7f.png)

**Water Distribution**
![image](https://user-images.githubusercontent.com/33861734/36722136-0fae9cb6-1bad-11e8-9d07-bf0fc01c0eca.png)
![image](https://user-images.githubusercontent.com/33861734/36722160-26c9209c-1bad-11e8-89c8-4c0d7b3968a6.png)

**Comment by holalluis** [comment]
@Ranf16  this is partially being solved, we can discuss this wednesday

**Comment by holalluis** [comment]
old
