### ISSUE TITLE
Error in formulas for CH4 and N2O from WW treatment and onsite treatment!

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#460]
@ElaChe00 

I strongly believe that there is an error in this formula shown below. The BOD in the effluent needs to be substracted as well, not only the BOD removed with sludge. Otherwise the BOD in the effluent will be used twice to calculate emissions, namely in treatment and discharge. 

![grafik](https://user-images.githubusercontent.com/33861734/123346516-cbebd200-d558-11eb-9cd9-ae649420793c.png)

In ECAM V2.2 this was considered correctly. 
![grafik](https://user-images.githubusercontent.com/33861734/123396655-daaaa700-d5a1-11eb-893d-92ead7b091e3.png)

**Comment by Ranf16** [comment]
The same error exists also in the formula for treatment in onsite sanitation


![grafik](https://user-images.githubusercontent.com/33861734/123396866-17769e00-d5a2-11eb-8252-f29c49f614a7.png)

Here ECAM V.2.2 where BOD from effluent is substracted
![grafik](https://user-images.githubusercontent.com/33861734/123396972-32e1a900-d5a2-11eb-9a93-b59773c59031.png)

**Comment by Ranf16** [comment]
The same conceptual error is also present for the calculation of N2O emissions. In the formulas you need to substract from the N influent load the effluent load before calculating N2O emissions. Otherwise the mass balance is wrong and you use N load in the effluent to calculate emissions twice, namely from discharge and treatment. 


![grafik](https://user-images.githubusercontent.com/33861734/123429772-9fbb6a00-d5c7-11eb-895f-b9b9d34986de.png)

![grafik](https://user-images.githubusercontent.com/33861734/123430037-fcb72000-d5c7-11eb-830a-d62b0258c445.png)

**Comment by holalluis** [comment]
Dear Ranjin, I understand your concern, this may seem double accounting but, we've changed this in v3 because IPCC equations: emission factors are based on how much BOD (for CH4) and TN (for N2O) are present when the emissions occurs
- CH4 emission factors units are in kgCH4/kgBOD: this means kg of BOD that are present in the emission origin (for example in the treatment). The same kg of BOD that are in the effluent will have a different emission factor, that's why we don't have to subtract it.
- The same is for N2O: the units are in kgN2O-N/kgN: this means that the TN present in the treatment, some fraction will be converted to N2O. The same TN that then is in the effluent will have its own emission factor.

**Comment by Ranf16** [comment]
Hi Lluis,

Please consider the following examples:

Example: WWTP with 1 treatment stage: BOD inflow= 100; BOD effluent =0; EF=5 
- > GHG= 500


Example: WWTP with 2 treatment stages (effluent of first stage is inflow of second stage): 
Stage A: BOD inflow 100, BOD effluent 50, EF=5
-> Using current formula would give GHG 500
-> My proposal: GHG 250
Stage B: BOD inflow (from Stage B) 50, BOD effluent 0; EF 5
- >GHG 250

In both examples above the total BOD load to the WWTP is the same and also the Emission factors (i.e. same technology), however with the current formula we have all of a sudden more emissions which should not happen. 


Also consider the following example: The WWTP is not working properly and 90 % of the inflow BOD leaves the plant with the effluent. The emissions in this case should be comparable to the scenario if the WW would be discharged without treatment,. However, with the current formula  GHG would be calculated from the WWTP as if all the BOD would be treated there, and then again all the BOD is used to calculate GHG from the discharge. 

I don't think that Eq 6.1 in the IPCC report was intended to be applied like this. Maybe your are right that in their original formula the effluent concentration does not need to be substracted, but then I think ECAM needs to adapted to be somehow able to calculate the examples I gave above.

**Comment by Ranf16** [comment]
@ElaChe00 @holalluis 

Hi, 
I see the examples described in my last post an issue for delivering a meaningful training in 2 weeks because one of the main objectives will be to develop  detailed GHG assessment of 7 utilities with real data.  Can you please look into this? IMO this is urgent.

They way it is now, I think you can't use the substages for several treatment stages of the same WWTP, which is the main reason to have substages in the first place. Without substages we will be able to do only very simple assessments of utilities.

**Comment by holalluis** [comment]
ok I'll discuss with Lluis C. ASAP and tell you something @lcorominas

**Comment by holalluis** [comment]
Dear @Ranf16 we've discussed with Lluís C. and we found an email from a year ago where we had this same doubt (this is when we did the change in the formula). We asked to an IPCC expert and she said this: 

> In regard to your question on Eq. 6.1, and whether to subtract off TOW effluent, the answer has to do more with how the emission factors were calculated than what may seem more appropriate regarding the organics that are converted to methane.  Basically, the emission factors were calculated using real system data using the approach shown in Eq. 6.1. If you change the equation, the emission factors are no longer valid.

I'll forward you the entire mail chain

**Comment by holalluis** [comment]
Dear @Ranf16, I've did the changes discussed today (subtracting the effluent BOD and TN), and tested the results loading a file that resulted in negative emissions:
![image](https://user-images.githubusercontent.com/1082644/124302342-618eef00-db61-11eb-8f51-2c58342244c2.png)
We can solve this is if I force the number to be 0 if we get a negative result

@ElaChe00 is this solution ok?

**Comment by holalluis** [comment]
The other option is leaving it as negative, so this will make the user be aware that something with the inputs is wrong

**Comment by lcorominas** [comment]
leave it as negative; so that the user knows that has to either reduce the bodremoved as sludge or the effluent bod

**Comment by holalluis** [comment]
can we close this issue? or something more needs to be done? @Ranf16 @ElaChe00 @lcorominas
