### ISSUE TITLE
Electrical energy produced from biogas valorization is largely overestimated (i.e. impossible)

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#461]
@ElaChe00 
ECAM calculates now the electricity production from biogas valorization.
![grafik](https://user-images.githubusercontent.com/33861734/123413604-42b5b900-d5b3-11eb-8be2-4b60563c5b76.png)

The calculation is based only on the theoretical energy content; 
![grafik](https://user-images.githubusercontent.com/33861734/123414102-c374b500-d5b3-11eb-9c86-771230af0305.png)

However, in reality you will never be able to convert 100% of the energy contained in CH4 to electricity but only about 30%, the rest will be heat and losses.  See general example of a co-generation in the figure below. 

So you would need to multiply the current result with the electrical efficiency of a cogeneration facility (about 30% IMO)
![grafik](https://user-images.githubusercontent.com/33861734/123414465-34b46800-d5b4-11eb-9fa8-a16185586b7c.png)

**Comment by Ranf16** [comment]
Here another reference. Maybe this is useful.

![grafik](https://user-images.githubusercontent.com/33861734/123420254-9deba980-d5bb-11eb-8891-5599ac488146.png)

**Comment by holalluis** [comment]
is it ok if we add a 0.30 in the estimation formula? I can write in the description that the estimation assumes a 30% efficiency

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/123675768-642cd400-d843-11eb-85a7-e4e625412086.png)

**Comment by ElaChe00** [comment]
@holalluis : Is it possible to make an **input field** for this value (e.g. electric efficiency)? not all have 30% ...some might have 20% or 40% 

An input field would solve this problem.

CC: @Ranf16

**Comment by holalluis** [comment]
ok, I can add it, but it will be a input devoted only to calculate an estimation

**Comment by holalluis** [comment]
I've discussed with Lluís C. and we added this default value from a scientific publication The user can input whatever number, but at least we have a default value referenced
![image](https://user-images.githubusercontent.com/1082644/124169241-5034dc80-daa6-11eb-9903-3233790b8703.png)
![image](https://user-images.githubusercontent.com/1082644/124169287-5c209e80-daa6-11eb-8fbe-aaed07e9a294.png)

**Comment by Ranf16** [comment]
Hi, if possible I would define that by default the value is 30% but the user can adapt it.

Mit besten Grüßen / Best regards
Ranjin Fernando

________________________________
