### ISSUE TITLE
Onsite Outputs: GHGem from Truck transport of faecal sludge appears 2 times

### ISSUE THREAD

**Issue by sebakoe** [icra/ecam#462]
The GHG emissions from the truck transport of faecal sludge appears 2 times in the table:

1. as Truck transport of faecal sludge
2. within Sludge management

the total GHG emission only consider it one time, which is good.

To avoid any confusion the value should only be in the table one time. I don't have a strong opinion which way is the best.

If it is not too much effort, than a solution like 
<html>
<body>

Population connected to sewers | 362,252
-- | --
⤷ Serviced population | 253,57

</body>
</html>

might be good, and easy to understand. 

![image](https://user-images.githubusercontent.com/84188310/124135128-d12eac80-da83-11eb-8e46-c6a2ca7816e5.png)

**Comment by holalluis** [comment]
thanks for spotting, I've just removed it from this table, the equation is inside sludge management, as you say

**Comment by sebakoe** [comment]
it still appears, when I turn on _Evaluate transport of faecal sludge?_

**Comment by holalluis** [comment]
maybe you have to reset the cache to see the changes, I've tested it and it works

**Comment by holalluis** [comment]
depending on which browser you use, usually there is an option in the refresh button that says "empty the cache and force refresh", you have to press F12, then right-click the refresh button, let me know if you could do it
![image](https://user-images.githubusercontent.com/1082644/124152382-c2e88c80-da93-11eb-8ca2-daaf5b29f09b.png)

**Comment by sebakoe** [comment]
you're right, it works now
