### ISSUE TITLE
ECAM 3.0 on www.wacclim.org

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#464]
@holalluis : According to the timeline I have shared, it would be great to launch ECAM 3.0 on www.wacclim.org next week.

The training with the interamerican development bank (IDB) will take place in two weeks too.

**Comment by ElaChe00** [comment]
Launch to website, July 7 or 8.

**Comment by holalluis** [comment]
Dear Elaine I've updated ecam.icradev.cat to the definitve version for launching v3 to wacclim.org, can you just make a quick look and tell me if everything is ok?
