### ISSUE TITLE
Influent Load or Removed Load to be considered with EF

### ISSUE THREAD

**Issue by Sebastian-Rosenfeldt** [icra/ecam#473]
Hi everyone,

In one of the most recent updates of the beta-version and now implemented in the release-version, I noticed a methodological change that I believe is wrong. Specifically, it is about the loads of BOD and nitrogen that are used to lead to the emissions of the treatment process after multiplication with the emission factors. In the IPCC- Methodology is not explicitly stated whether the incoming load or the load converted by the process is involved. 

In IPCC (2019), it is only given: CH4-Emission = [Organics in wastewater of treatment – Organic Component removed in the form of sludge] x Emission Factor – CH4 recovered. In addition in the Annex 6A.5 is written “MCFs were calculated from data presented in studies, including measured CH4 emissions from wastewater treatment plant (not including sludge digesters), influent organics in wastewater, estimates of organics removed in sludge, and the IPCC default Bo value.” Therefore, I do not think it is right to apply the emission factor to the organic load removed.

And it is the same with the N2O emission factor. Although the reference units of the emission factors vary in the literature, it should be noted that it seems that the total emission factor N2O-N per N afluente has prevailed. In the publication “Reduktionspotential bei den Lachgasemissionen aus Kläranlagen durch Optimierung des Betriebes“ of the Environment Agency of Austria (Parravicini et al, 2005) we notice that for large wastewater treatment plants were observed emission factors of 0,003 to 2,6 % N2O / N affluent, corresponding to the default EF of 1,6 %.

![image](https://user-images.githubusercontent.com/87151409/124990577-f0df4b00-e016-11eb-946e-c32e3ff20708.png)

**Comment by holalluis** [comment]
Hi Sebastian, we discussed this change with @ElaChe00 @Ranf16 and @lcorominas. I think they can explain better why we changed it, we also agreed that we would put an explanation in the formula to explain why we decided to subtract the effluent  BOD and TN, but we didn't, this is something pending.

**Comment by lcorominas** [comment]
I agree with the comment from Sebastian. It is rather tricky... if we keep it as it is not (based on the removed load) the default emission factors remain no longer valid. I believe that IPCC should reconsider what they propose. i think that our current formula makes more sense (based on removed load), but the default emission factors should be recalculated (so expressed as removed load and not influent load); i think that it is not much effort to recalculate them if the data is available.

**Comment by ElaChe00** [comment]
Dear @Sebastian-Rosenfeldt , thanks for posting this issue. Also thanks to @lcorominas and @holalluis for adressing this. This  issues posted by @Ranf16 because there were major concerns regarding (but not only) the sub-stages and emissions being over-estimated: 

**Please see the whole post here: https://github.com/icra/ecam/issues/460**

**Comment by holalluis** [comment]
Hi @Sebastian-Rosenfeldt, after some discussion we've decided to fix the equations to stick with IPCC.
![image](https://user-images.githubusercontent.com/1082644/125781762-c3785efa-d78d-4fb4-8dc6-57f0baf959a0.png)
