### ISSUE TITLE
 https version of ECAM

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#474]
@ElaChe00 
When opening wacclim.org/ecam you are not automatically transfered to the https version of the tool. Instead it shows that the connection to the website is insecure.

![grafik](https://user-images.githubusercontent.com/33861734/125638542-beba8c1f-2e7f-441f-aa53-7c07ea52136f.png)

**Comment by holalluis** [comment]
this is something that administrators of the wacclim.org server must address, I cannot. However you can still go to https://wacclim.org/ecam/ direclty and it works

**Comment by ElaChe00** [comment]
I don't have this problem, sorry.
![image](https://user-images.githubusercontent.com/45791540/125674482-5de9a9cc-3351-46d4-b9c4-4c8379b42358.png)
