### ISSUE TITLE
Error when importing Excel template

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#478]
@ElaChe00 

When trying to import from the Excel template, the error below was reported by a participant from the training. See screenshot below.

![grafik](https://user-images.githubusercontent.com/33861734/126692765-f5c044b2-e581-408b-9e9f-1a6e6c6d2ac8.png)

I will ask for the Excel file that causes this problem and paste the link here later

**Comment by Ranf16** [comment]
Here is the link to the Excel file tht causes the problem:
https://1drv.ms/x/s!AkiwymoXqmgonF6-Ez9g8VOHWRq-?e=ILxkKd

The user also shared this message:

"Adjunto también la hoja del Excel que creo es la causante. Primeramente había cargado los datos en las columnas a la derecha. En el caso de Water Distribution no permite corregir porque están bloqueadas las celdas. Seguramente esto  podría producir un error, pero lo dejo en sus manos expertas. "

**Comment by holalluis** [comment]
Hi, I've had a look to this excel file,and it has problems: it seems like the user blocked the cells reserved to create substages, and wrote values that are not numbers, that's why we see this error
