### ISSUE TITLE
Spanish translation has errors and is partly incomplete

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#479]
There are a couple of issues that I saw but I didn't have time to systematically note them down. **The translation should be checked completely.**

Here is an important one because it changes the meaning:

hay un problema con la traducción del valor de lodos producido en la PTAR. En Español esta incorrecta, en ingles es correcto. Deben ingresar el valor del peso seco aunque dice  “Lodos producidos en la PTAR/EDAR (peso total)”. 

![grafik](https://user-images.githubusercontent.com/33861734/127928464-a8fdd322-b629-46be-a257-5858dc630a7f.png)

**Comment by Ranf16** [comment]
Missing translation

![grafik](https://user-images.githubusercontent.com/33861734/127928667-f558cf5c-38f0-4b13-9d14-5ad3d3e544bb.png)

**Comment by holalluis** [comment]
Thanks for noticing, these errors have been corrected
