### ISSUE TITLE
Annual protein consumption vs. supply

### ISSUE THREAD

**Issue by Anveizaga** [icra/ecam#483]
From Peru:

The tool ECAM loads the specific value for annual protein consumption per capita **in PERU** of 28,40065 kg/(person.year), corresponding to 77,87 g/(person.day). 

![image](https://user-images.githubusercontent.com/55831330/134345951-8a0efa8f-e684-48ae-81ac-f0264a65470e.png)

According to IPCC the equation to calculate the TOTAL NITROGEN IN DOMESTIC WASTEWATER is:

![image](https://user-images.githubusercontent.com/55831330/134346025-befb6a4d-339c-495b-82e2-8c7707e9e42b.png)

Where PROTEIN is the annual per capita protein consumption, calculated by
 
![image](https://user-images.githubusercontent.com/55831330/134346526-6fb51440-7882-4719-8703-dbd32a4b4bd2.png)

 
 
,considering the annual per capita protein supply, informed by FAOSTAT, adjusted with the fraction of protein consumed (FPC).
 
The 3-year average protein supply  (3-year average) for Peru is 76,7 g/capita/day, corresponding to 27,996 kg/(person.year). With the FPC for Latin America of 0,92, we would have protein consumption resulting in 25,756 kg/(person.year), about 9,3 % lower than suggested by ECAM.
 
We need to consider the FPC to calculate the protein consumption in the ECAM tool, when calculated the Total Nitrogen load in the influent (wwt_tn_infl). That way ECAM tool would be equivalent in this aspect to IPCC method again.
 
 
![image](https://user-images.githubusercontent.com/55831330/134346559-62c320d0-a50f-4da1-91f1-7ba5bb332a4e.png)

**Comment by holalluis** [comment]
Hi, the protein consumption table values have been updated with the info of FPC supplied. The values that appeared there were the protein supply, so in order to be protein consumption the have been multiplied by the FPC values for each country
