### ISSUE TITLE
Leap years not considered

### ISSUE THREAD

**Issue by Anveizaga** [icra/ecam#485]
The assessment period can be selected through default calenders. Unfortunately leap years, which should have 366 days, have 365 days according to the ECAM. This could affect the results when calculating per year.

**Comment by holalluis** [comment]
Dear Anveizaga,

In theory, ecam treats leap years correctly.
![image](https://user-images.githubusercontent.com/1082644/137888910-1cd4f006-9ae4-418a-ad24-0e99e07afd83.png)

Can you send an example where this is not calculated correctly? Thanks!
