### ISSUE TITLE
WW Treatment - Landfilling vs. Land application

### ISSUE THREAD

**Issue by Anveizaga** [icra/ecam#486]
In the section to assess **sludge sent to landifilling** in **Sanitation> treatment** some parameters refer to land application and not landfilling itself:

- _Total Volatile Solids (TVS) content of sludge sent to land application_ >**under landfilling**

- _N content of sludge sent to land application (% of dry weight)_ >**under landfilling**

![image](https://user-images.githubusercontent.com/55831330/140918597-d971b600-d0dd-4d9e-be3e-6db3b198d8dc.png)

**Comment by holalluis** [comment]
Dear @Anveizaga, this has been corrected. Thanks for noticing it
![image](https://user-images.githubusercontent.com/1082644/142865174-560f3e8a-c734-4975-b113-f5634434af10.png)
