### ISSUE TITLE
Onsite Sanitation Nitrogen Load (wwo_tn_infl)

### ISSUE THREAD

**Issue by pia-mars** [icra/ecam#489]
Hello, 

When entering data for the onsite sanitation page, the nitrogen load in influent (wwo_tn_infl) does not have the option to calculate automatically, like it does in the other stages. It would solve the problem to add the equation used for the other stages (for example wwt_tn_infl) to the onsite sanitation page as well.

Thanks!

![image](https://user-images.githubusercontent.com/98542668/163390469-1d69ab53-6cf0-436a-ae32-b02e7e8cb7d7.png)

**Comment by holalluis** [comment]
Hi, thanks for the suggestion, I've added it
![image](https://user-images.githubusercontent.com/1082644/202697866-742a7531-f5d7-42fd-9643-7b0a86305737.png)
and also the reference to the original equation from IPCC 
![image](https://user-images.githubusercontent.com/1082644/202697974-3c3ded71-0c7e-4a70-b12b-dab56f07b0ba.png)
