### ISSUE TITLE
Task 1: Fixing of the previous errors/bugs or amendments in ECAM V2.0  

### ISSUE THREAD

**Issue by harora16** [icra/ecam#49]
**1. Water abstraction stage:** 
![error 1](https://user-images.githubusercontent.com/38723394/39243441-b47f087c-488d-11e8-9de6-e411bfe83151.PNG)
**2. Water abstraction and distribution stage**
![error 2](https://user-images.githubusercontent.com/38723394/39243504-f3dcf4d4-488d-11e8-8992-c9333bd99de7.PNG)
**3. N20 from treatment is not calculating**
![error 3](https://user-images.githubusercontent.com/38723394/39243588-3d5a5228-488e-11e8-9138-d4b7ec18f37c.PNG)
**4. Waste Water Treatment**
![error 4](https://user-images.githubusercontent.com/38723394/39243692-a887f9ec-488e-11e8-8fd5-63d46d50e19a.PNG)
**5. Translate opportunities page.**  
**6. Pumping Edits**
   6.1 Abstraction Stage 
![error 1](https://user-images.githubusercontent.com/38723394/39254227-e17b6494-48a9-11e8-8b1e-24ef62c6ae07.PNG)
![error 2](https://user-images.githubusercontent.com/38723394/39254234-e50f6d30-48a9-11e8-9458-0147f0c0b46b.PNG)
   6.2 Drinking Water Treatment
![error 3](https://user-images.githubusercontent.com/38723394/39254273-02226a76-48aa-11e8-8481-39abc3d3b05c.PNG)
   6.3 Distribution
![error 4](https://user-images.githubusercontent.com/38723394/39254419-5931eb02-48aa-11e8-8d33-11306fe2c5c0.PNG)
![error 5](https://user-images.githubusercontent.com/38723394/39254448-6513094c-48aa-11e8-9a2c-e7df6c399f63.PNG)
  6.4 Collection
![error 6](https://user-images.githubusercontent.com/38723394/39254497-828b63a2-48aa-11e8-8e34-7f728a90261c.PNG)
   6.5 Wast Water treatment
Delete estimated pumping efficiency since it cannot be calculated with the given inputs.

**Comment by holalluis** [comment]
I've splitted each item here in new items
