### ISSUE TITLE
edit wxx_KPI_std_nrg_newp

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#65]
wsa_KPI_std_nrg_newp:function(){return 0.2725/this.wsa_pmp_exff},
wsd_KPI_std_nrg_newp:function(){return 0.2725/this.wsd_pmp_exff},
wwc_KPI_std_nrg_newp:function(){return 0.2725/this.wwc_pmp_exff},

![image](https://user-images.githubusercontent.com/1082644/40135835-97536d64-5946-11e8-8e25-ae9913828750.png)

**Comment by holalluis** [comment]
Should be all 3 edited the same way? @Ranf16

**Comment by Porro1jc** [comment]
look at the instructions for each and follow that.

**Comment by holalluis** [comment]
@Porro1jc In the instructions specifies this change for Abstraction (wsa) and Distribution (wsd), but **not** for Collection (wwc), that's why I'm asking.

**Comment by Ranf16** [comment]
Good that you saw this Lluis. Yes it should be done for all stages that assess pump opportunities.

**Comment by holalluis** [comment]
done
