### ISSUE TITLE
The numbers for populations are not zero if you create a new file or clear an existing file.

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#73]
If you create a new file or even if you clear an existing file there are the following numbers for the population already prefilled:

![image](https://user-images.githubusercontent.com/33861734/40260278-05baaf4c-5afa-11e8-95bb-71b7b7cd10be.png)

**Comment by holalluis** [comment]
Hi, I've set those default numbers because during testing I find myself entering these numbers, so I don't have to enter them every time I create a new system. I can set them to zero again when this iteration of development is finished if you want, or even we can discuss default values for them.

**Comment by Ranf16** [comment]
@Ranf16 @holalluis @harora16

Lluis, you forgot to take these prefilled population numbers out. Can you please still do it?

**Comment by holalluis** [comment]
yes, it is done
