### ISSUE TITLE
Add more treatment technologies to dropdown menu

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#84]
I need a more precise explanation

**Comment by holalluis** [comment]
![captura de pantalla 2018-05-30 a las 18 23 38](https://user-images.githubusercontent.com/1082644/40733713-9cef5ea4-6436-11e8-9879-5c70b63987c6.png)

**Comment by holalluis** [comment]
@Ranf16 @Porro1jc please keep in mind that if you provide a new technology, it would be good to provide the name in all the languages

**Comment by Porro1jc** [comment]
![image](https://user-images.githubusercontent.com/20580315/40854217-b1936b16-659e-11e8-9262-edc62cd3fd2b.png)

**Comment by holalluis** [comment]
@Porro1jc Jose, I cannot copy paste the thai text because it is an image, could you copy paste the text please? thanks

**Comment by Ranf16** [comment]
Here it is: ถังอิมฮอฟฟ์

**Comment by Porro1jc** [comment]
But we do not need to spend time translating now.

Sent from my iPhone

On Jun 4, 2018, at 6:08 PM, Ranf16 <notifications@github.com<mailto:notifications@github.com>> wrote:


Here it is: ถังอิมฮอฟฟ์
