### ISSUE TITLE
Outputs table is very wide and easily overlaps with inputs table. 

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#90]
Note: this is not high priority.

The outputs tables in Tier B are very wide and on a laptop screen with a view size more then 100% they overlap (see below). 

I'd recommend to make the tables if possible less wide so that there is more white space in between. 

![image](https://user-images.githubusercontent.com/33861734/40494609-901fa2a8-5f75-11e8-8582-46386313feb9.png)

**Comment by holalluis** [comment]
I agree, this is an issue I didn't know how to fix easily, but now I think I can do it
