### ISSUE TITLE
GHG due to non revenue water equations

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#92]
The discussion was: change name to "due to water losses"
wsa_SL_GHG_nrw
wst_SL_GHG_nrw
wsd_SL_GHG_nrw
wsd_SL_ghg_attr

Summary of formulas:
Water losses           is "wsd_vol_dist - wsd_auth_con"
Non revenue water is "wsd_vol_dist - wsd_bill_con"
![image](https://user-images.githubusercontent.com/1082644/40515043-94b80522-5fab-11e8-807c-647f96cf1d59.png)

**Comment by Porro1jc** [comment]
let's make this based on the water loss

**Comment by Porro1jc** [comment]
@holalluis @Ranf16 @harora16

Follow this format for each.  It is ok for now that variable has nrw in it.  Not a big deal...

![image](https://user-images.githubusercontent.com/20580315/40739749-0077843c-6415-11e8-9304-5425b8c851e3.png)

**Comment by holalluis** [comment]
ok. Please keep in mind that if I change the description in English, the french, spanish and thai will still have the "due to non revenue water" instead of water losses, so, it is better to change it now also, so please provide the translation for the other languages for this text change.

**Comment by Porro1jc** [comment]
We will not translate now we will worry about that at a later time

Sent from my iPhone

On May 30, 2018, at 2:26 PM, Lluís Bosch <notifications@github.com<mailto:notifications@github.com>> wrote:


ok. Please keep in mind that if I change the description in English, the french, spanish and thai will still have the "due to non revenue water" instead of water losses, so, it is better to change it now also, so please provide the translation for the other languages for this text change.

**Comment by holalluis** [comment]
ok, I've removed the old translation for languages other than english and added the language tag to the new tags to be translated

**Comment by holalluis** [comment]
done

**Comment by Porro1jc** [comment]
Maybe I am not understanding...  If we have things translated, we want to keep them, but for this version we will not show translations until we have everything translated for at least one language.  So I would do a save as on the text file so you do not have to retranslate that are already translated.

**Comment by holalluis** [comment]
yes, I've just deleted the tags which need to be retranslated because of the text change, and I will add them to the new ones, as if they were new language tags. I have not deleted the ones that already translated
