### ISSUE TITLE
Pump efficiency in Abstraction not working 

### ISSUE THREAD

**Issue by Porro1jc** [icra/ecam#96]
@Ranf16 @hemant @holalluis 

![image](https://user-images.githubusercontent.com/20580315/40553672-641a9aae-6011-11e8-9c5e-5ed73dd20646.png)

It should work the same as in distribution

**Comment by holalluis** [comment]
probably you have the pump head value at 0, it works for me

**Comment by Porro1jc** [comment]
ok thanks.
