### ISSUE TITLE
GHG summary: sum of emissions when selecting substage checkbox does not change

### ISSUE THREAD

**Issue by harora16** [icra/ecam#97]
untreated wastewater is reflected in GHG summary ( but as described by Ranjin in the video shared earlier the total values are still not changing if you select the sub stage option)

**Comment by holalluis** [comment]
The problem is that when there are mixed options checked (i.e. 2 stages checked, and 4 unchecked) it makes no sense to sum the stage values for the stages unchecked and the substage values for the stages checked, no?

**Comment by Ranf16** [comment]
It should b possible to have some boxes checked. The totals displayed should reflect the selection you have done with the checkboxes

**Comment by holalluis** [comment]
solved. Please check the GHG summary table. Note that the untreated wastewater emissions are taken into account regardless of if substages is selected or not, because they are calculated at whole Wastewater level
