### ISSUE TITLE
Water reuse - revise GHG avoided outputs 

### ISSUE THREAD

**Issue by Porro1jc** [icra/ecam#99]
@holalluis @Ranf16 @harora16

due to simplifying inputs basically combining nitrogen and phosphorus recovered for both reuse and sludge management we now only need one set of outputs for nutrient recovery.  See edits below...

![image](https://user-images.githubusercontent.com/20580315/40624867-04df7f1e-627d-11e8-9258-07e5fbc66a98.png)

![image](https://user-images.githubusercontent.com/20580315/40624910-38a2d54e-627d-11e8-999e-2a39860d9ec3.png)

**Comment by holalluis** [comment]
done. Please check and reopen the issue if still not correct
